In [1]:
import selenium
from selenium import webdriver
import time
import pandas as pd
import numpy as np
from selenium.common.exceptions import NoSuchElementException

In [91]:
driver = webdriver.Chrome(r'C:\Users\chromedriver.exe')

In [70]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

def get_yatra(dep_from, arr_to, dep_day, dep_mon, dep_year, fl_cl):
    urls = ('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class='+fl_cl+
    '&destination='+arr_to+'&destinationCountry=IN&flexi=0&flight_depart_date='+dep_day+'%2F'+dep_mon+'%2F'+dep_year+'&hb=0&noOfSegments=1&origin='
    +dep_from+'&originCountry=IN&type=O&unique=207953473702&viewName=normal')
    
    driver.get(urls)

    time.sleep(45)
    
    for i in range(35): 
       driver.execute_script("window.scrollBy(0, 10000)")
       time.sleep(1)
    
    try:
        air = driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
        for i in air:
            airlines.append(i.text)
    except NoSuchElementException:
        airlines.append('-')
    
    try:
        dep = driver.find_elements_by_xpath('//div[@class="i-b pr"]')
        for d in dep:
            departure.append(d.text)
    except NoSuchElementException:
        departure.append('-')
        
    try:
        dur = driver.find_elements_by_xpath('//div[@class="stop-cont pl-13"]//p')
        for u in dur:
            duration.append(u.text)
    except NoSuchElementException:
        duration.append('-')
        
    try:
        stop = driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]//span')
        for s in stop:
            stops.append(s.text)
    except NoSuchElementException:
        stops.append('-')
        
        
    try:
        tcity = driver.find_elements_by_xpath('//div[@class="i-b pdd-0 text-left atime col-5"]//p[2]')
        for t in tcity:
            to_city.append(t.text)
    except NoSuchElementException:
        to_city.append('-')
        
    
    try:
        pri = driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
        for p in pri:
            price.append(p.text.replace(',',''))
    except NoSuchElementException:
        price.append('-')

In [4]:
get_yatra('DEL','BOM','27','10','2021','Economy')

In [5]:
x = pd.DataFrame({})
x['airlines'] = airlines
x['departure'] = departure
x['duration'] = duration
x['stops'] = stops
x['from_city'] = 'New Delhi'
x['to_city'] = to_city
x['price'] = price
x['journey_date'] = '2021-10-27'
x['fclass'] = 'Economy'
x

Empty DataFrame
Columns: [airlines, departure, duration, stops, from_city, to_city, price, journey_date, fclass]
Index: []

In [6]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','29','10','2021','Economy')

x1 = pd.DataFrame({})
x1['airlines'] = airlines
x1['departure'] = departure
x1['duration'] = duration
x1['stops'] = stops
x1['from_city'] = 'New Delhi'
x1['to_city'] = to_city
x1['price'] = price
x1['journey_date'] = '2021-10-29'
x1['fclass'] = 'Economy'
x1

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air Asia,09:25,6h 35m,1 Stop,New Delhi,Mumbai,5953,2021-10-29,Economy
1,Air Asia,12:40,7h 35m,1 Stop,New Delhi,Mumbai,5953,2021-10-29,Economy
2,Air Asia,11:55,8h 20m,1 Stop,New Delhi,Mumbai,5953,2021-10-29,Economy
3,Air Asia,05:20,14h 55m,1 Stop,New Delhi,Mumbai,5953,2021-10-29,Economy
4,Go First,18:50,1h 55m,Non Stop,New Delhi,Mumbai,5954,2021-10-29,Economy
...,...,...,...,...,...,...,...,...,...
147,Air India,16:35,17h 05m,1 Stop,New Delhi,Mumbai,19605,2021-10-29,Economy
148,Vistara,19:55,15h 55m,1 Stop,New Delhi,Mumbai,20655,2021-10-29,Economy
149,Air India,07:00,13h 15m,1 Stop,New Delhi,Mumbai,21705,2021-10-29,Economy
150,Vistara,17:35,5h 30m,1 Stop,New Delhi,Mumbai,22755,2021-10-29,Economy
151,Vistara,16:00,7h 05m,1 Stop,New Delhi,Mumbai,22755,2021-10-29,Economy

In [7]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','31','10','2021','Economy')

x2 = pd.DataFrame({})
x2['airlines'] = airlines
x2['departure'] = departure
x2['duration'] = duration
x2['stops'] = stops
x2['from_city'] = 'New Delhi'
x2['to_city'] = to_city
x2['price'] = price
x2['journey_date'] = '2021-10-31'
x2['fclass'] = 'Economy'
x2

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air Asia,21:25,9h 20m,1 Stop,New Delhi,Mumbai,5953,2021-10-31,Economy
1,Air Asia,21:25,9h 50m,1 Stop,New Delhi,Mumbai,5953,2021-10-31,Economy
2,Air Asia,18:35,12h 10m,1 Stop,New Delhi,Mumbai,5953,2021-10-31,Economy
3,Air Asia,18:35,12h 40m,1 Stop,New Delhi,Mumbai,5953,2021-10-31,Economy
4,Go First,07:00,2h 10m,Non Stop,New Delhi,Mumbai,5954,2021-10-31,Economy
...,...,...,...,...,...,...,...,...,...
149,Go First,11:50,5h 30m,1 Stop,New Delhi,Mumbai,20325,2021-10-31,Economy
150,Air India,10:55,21h 50m,1 Stop,New Delhi,Mumbai,21075,2021-10-31,Economy
151,Air India,14:10,8h 10m,1 Stop,New Delhi,Mumbai,24330,2021-10-31,Economy
152,Air India,10:55,5h 40m,1 Stop,New Delhi,Mumbai,25695,2021-10-31,Economy
153,Air India,10:55,11h 30m,1 Stop,New Delhi,Mumbai,25695,2021-10-31,Economy

In [8]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','1','11','2021','Economy')

x3 = pd.DataFrame({})
x3['airlines'] = airlines
x3['departure'] = departure
x3['duration'] = duration
x3['stops'] = stops
x3['from_city'] = 'New Delhi'
x3['to_city'] = to_city
x3['price'] = price
x3['journey_date'] = '2021-11-1'
x3['fclass'] = 'Economy'
x3

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air Asia,21:25,9h 20m,1 Stop,New Delhi,Mumbai,5953,2021-11-1,Economy
1,Air Asia,21:25,9h 50m,1 Stop,New Delhi,Mumbai,5953,2021-11-1,Economy
2,Air Asia,22:10,14h 15m,1 Stop,New Delhi,Mumbai,5953,2021-11-1,Economy
3,Go First,07:00,2h 10m,Non Stop,New Delhi,Mumbai,5954,2021-11-1,Economy
4,Go First,08:00,2h 10m,Non Stop,New Delhi,Mumbai,5954,2021-11-1,Economy
...,...,...,...,...,...,...,...,...,...
159,Vistara,17:30,6h 00m,1 Stop,New Delhi,Mumbai,13095,2021-11-1,Economy
160,Vistara,17:30,19h 30m,1 Stop,New Delhi,Mumbai,13095,2021-11-1,Economy
161,Vistara,17:30,26h 50m,1 Stop,New Delhi,Mumbai,13095,2021-11-1,Economy
162,Vistara,20:40,14h 45m,1 Stop,New Delhi,Mumbai,15353,2021-11-1,Economy
163,Go First,11:30,5h 30m,1 Stop,New Delhi,Mumbai,19711,2021-11-1,Economy

In [9]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','3','11','2021','Economy')

x4 = pd.DataFrame({})
x4['airlines'] = airlines
x4['departure'] = departure
x4['duration'] = duration
x4['stops'] = stops
x4['from_city'] = 'New Delhi'
x4['to_city'] = to_city
x4['price'] = price
x4['journey_date'] = '2021-11-3'
x4['fclass'] = 'Economy'
x4

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air Asia,22:10,14h 15m,1 Stop,New Delhi,Mumbai,5953,2021-11-3,Economy
1,Go First,07:00,2h 10m,Non Stop,New Delhi,Mumbai,5954,2021-11-3,Economy
2,Go First,08:00,2h 10m,Non Stop,New Delhi,Mumbai,5954,2021-11-3,Economy
3,Go First,02:00,2h 15m,Non Stop,New Delhi,Mumbai,5954,2021-11-3,Economy
4,Go First,14:20,2h 15m,Non Stop,New Delhi,Mumbai,5954,2021-11-3,Economy
...,...,...,...,...,...,...,...,...,...
149,IndiGo,20:20,9h 35m,1 Stop,New Delhi,Mumbai,16560,2021-11-3,Economy
150,Air India,14:10,8h 15m,1 Stop,New Delhi,Mumbai,16770,2021-11-3,Economy
151,Air India,13:15,24h 10m,2 Stop(s),New Delhi,Mumbai,17505,2021-11-3,Economy
152,Go First,11:30,5h 30m,1 Stop,New Delhi,Mumbai,19711,2021-11-3,Economy
153,SpiceJet,12:00,25h 15m,1 Stop,New Delhi,Mumbai,19762,2021-11-3,Economy

In [10]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','5','11','2021','Economy')

x5 = pd.DataFrame({})
x5['airlines'] = airlines
x5['departure'] = departure
x5['duration'] = duration
x5['stops'] = stops
x5['from_city'] = 'New Delhi'
x5['to_city'] = to_city
x5['price'] = price
x5['journey_date'] = '2021-11-5'
x5['fclass'] = 'Economy'
x5

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Go First,07:00,2h 10m,Non Stop,New Delhi,Mumbai,5954,2021-11-5,Economy
1,Go First,08:00,2h 10m,Non Stop,New Delhi,Mumbai,5954,2021-11-5,Economy
2,Go First,22:30,2h 10m,Non Stop,New Delhi,Mumbai,5954,2021-11-5,Economy
3,Go First,02:00,2h 15m,Non Stop,New Delhi,Mumbai,5954,2021-11-5,Economy
4,Go First,14:20,2h 15m,Non Stop,New Delhi,Mumbai,5954,2021-11-5,Economy
...,...,...,...,...,...,...,...,...,...
157,IndiGo,05:15,4h 50m,1 Stop,New Delhi,Mumbai,14985,2021-11-5,Economy
158,Go First,11:30,5h 30m,1 Stop,New Delhi,Mumbai,16245,2021-11-5,Economy
159,Go First,06:00,4h 40m,1 Stop,New Delhi,Mumbai,16533,2021-11-5,Economy
160,Go First,06:00,6h 30m,1 Stop,New Delhi,Mumbai,16533,2021-11-5,Economy
161,Go First,16:30,4h 55m,1 Stop,New Delhi,Mumbai,18003,2021-11-5,Economy

In [11]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','7','11','2021','Economy')

x6 = pd.DataFrame({})
x6['airlines'] = airlines
x6['departure'] = departure
x6['duration'] = duration
x6['stops'] = stops
x6['from_city'] = 'New Delhi'
x6['to_city'] = to_city
x6['price'] = price
x6['journey_date'] = '2021-11-7'
x6['fclass'] = 'Economy'
x6

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air Asia,22:10,14h 15m,1 Stop,New Delhi,Mumbai,5953,2021-11-7,Economy
1,Go First,02:00,2h 15m,Non Stop,New Delhi,Mumbai,5954,2021-11-7,Economy
2,Go First,09:00,6h 45m,1 Stop,New Delhi,Mumbai,5954,2021-11-7,Economy
3,SpiceJet,06:20,2h 20m,Non Stop,New Delhi,Mumbai,5955,2021-11-7,Economy
4,IndiGo,04:45,2h 25m,Non Stop,New Delhi,Mumbai,5955,2021-11-7,Economy
...,...,...,...,...,...,...,...,...,...
155,Go First,16:30,4h 55m,1 Stop,New Delhi,Mumbai,25669,2021-11-7,Economy
156,IndiGo,13:30,6h 50m,1 Stop,New Delhi,Mumbai,25695,2021-11-7,Economy
157,Vistara,07:30,5h 30m,1 Stop,New Delhi,Mumbai,25905,2021-11-7,Economy
158,Vistara,06:15,6h 45m,1 Stop,New Delhi,Mumbai,25905,2021-11-7,Economy
159,Vistara,07:30,12h 50m,1 Stop,New Delhi,Mumbai,25905,2021-11-7,Economy

In [12]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','9','11','2021','Economy')

x7 = pd.DataFrame({})
x7['airlines'] = airlines
x7['departure'] = departure
x7['duration'] = duration
x7['stops'] = stops
x7['from_city'] = 'New Delhi'
x7['to_city'] = to_city
x7['price'] = price
x7['journey_date'] = '2021-11-9'
x7['fclass'] = 'Economy'
x7

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air Asia,21:25,9h 20m,1 Stop,New Delhi,Mumbai,5953,2021-11-9,Economy
1,Air Asia,21:25,9h 50m,1 Stop,New Delhi,Mumbai,5953,2021-11-9,Economy
2,Air Asia,20:45,10h 00m,1 Stop,New Delhi,Mumbai,5953,2021-11-9,Economy
3,Air Asia,20:45,10h 30m,1 Stop,New Delhi,Mumbai,5953,2021-11-9,Economy
4,Air Asia,09:35,11h 00m,1 Stop,New Delhi,Mumbai,5953,2021-11-9,Economy
...,...,...,...,...,...,...,...,...,...
140,Air India,06:55,14h 20m,1 Stop,New Delhi,Mumbai,18765,2021-11-9,Economy
141,Vistara,13:40,7h 55m,1 Stop,New Delhi,Mumbai,18975,2021-11-9,Economy
142,Air India,14:30,7h 55m,1 Stop,New Delhi,Mumbai,19815,2021-11-9,Economy
143,Air India,16:55,19h 30m,1 Stop,New Delhi,Mumbai,25905,2021-11-9,Economy
144,Air India,20:15,16h 10m,1 Stop,New Delhi,Mumbai,26745,2021-11-9,Economy

In [14]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','11','11','2021','Economy')

x8 = pd.DataFrame({})
x8['airlines'] = airlines
x8['departure'] = departure
x8['duration'] = duration
x8['stops'] = stops
x8['from_city'] = 'New Delhi'
x8['to_city'] = to_city
x8['price'] = price
x8['journey_date'] = '2021-11-11'
x8['fclass'] = 'Economy'
x8

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air Asia,20:00,6h 25m,1 Stop,New Delhi,Mumbai,5953,2021-11-11,Economy
1,Air Asia,21:25,9h 20m,1 Stop,New Delhi,Mumbai,5953,2021-11-11,Economy
2,Air Asia,21:25,9h 50m,1 Stop,New Delhi,Mumbai,5953,2021-11-11,Economy
3,Air Asia,20:45,10h 00m,1 Stop,New Delhi,Mumbai,5953,2021-11-11,Economy
4,Air Asia,20:45,10h 30m,1 Stop,New Delhi,Mumbai,5953,2021-11-11,Economy
...,...,...,...,...,...,...,...,...,...
161,IndiGo,22:15,10h 10m,1 Stop,New Delhi,Mumbai,14255,2021-11-11,Economy
162,Go First,10:45,7h 35m,1 Stop,New Delhi,Mumbai,15249,2021-11-11,Economy
163,IndiGo,18:30,4h 40m,1 Stop,New Delhi,Mumbai,15720,2021-11-11,Economy
164,Go First,19:55,6h 05m,1 Stop,New Delhi,Mumbai,16533,2021-11-11,Economy
165,Go First,10:45,8h 55m,1 Stop,New Delhi,Mumbai,16929,2021-11-11,Economy

In [15]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','13','11','2021','Economy')

x9 = pd.DataFrame({})
x9['airlines'] = airlines
x9['departure'] = departure
x9['duration'] = duration
x9['stops'] = stops
x9['from_city'] = 'New Delhi'
x9['to_city'] = to_city
x9['price'] = price
x9['journey_date'] = '2021-11-13'
x9['fclass'] = 'Economy'
x9

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air India,07:00,2h 05m,Non Stop,New Delhi,Mumbai,4931,2021-11-13,Economy
1,Air India,10:40,2h 10m,Non Stop,New Delhi,Mumbai,4931,2021-11-13,Economy
2,Air India,09:00,2h 15m,Non Stop,New Delhi,Mumbai,4931,2021-11-13,Economy
3,Air India,08:00,2h 10m,Non Stop,New Delhi,Mumbai,5416,2021-11-13,Economy
4,Air India,17:50,3h 45m,1 Stop,New Delhi,Mumbai,5416,2021-11-13,Economy
...,...,...,...,...,...,...,...,...,...
161,Vistara,20:40,14h 45m,1 Stop,New Delhi,Mumbai,16718,2021-11-13,Economy
162,Vistara,19:50,15h 35m,1 Stop,New Delhi,Mumbai,16718,2021-11-13,Economy
163,Go First,11:30,5h 30m,1 Stop,New Delhi,Mumbai,20341,2021-11-13,Economy
164,Go First,10:45,6h 15m,1 Stop,New Delhi,Mumbai,20341,2021-11-13,Economy
165,Go First,09:00,8h 00m,1 Stop,New Delhi,Mumbai,20341,2021-11-13,Economy

In [16]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','15','11','2021','Economy')

x10 = pd.DataFrame({})
x10['airlines'] = airlines
x10['departure'] = departure
x10['duration'] = duration
x10['stops'] = stops
x10['from_city'] = 'New Delhi'
x10['to_city'] = to_city
x10['price'] = price
x10['journey_date'] = '2021-11-15'
x10['fclass'] = 'Economy'
x10

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air India,07:00,2h 05m,Non Stop,New Delhi,Mumbai,4931,2021-11-15,Economy
1,Air India,08:00,2h 10m,Non Stop,New Delhi,Mumbai,4931,2021-11-15,Economy
2,Air India,10:40,2h 10m,Non Stop,New Delhi,Mumbai,4931,2021-11-15,Economy
3,Air India,17:50,2h 10m,Non Stop,New Delhi,Mumbai,4931,2021-11-15,Economy
4,Air India,09:00,2h 15m,Non Stop,New Delhi,Mumbai,4931,2021-11-15,Economy
5,Air India,17:50,3h 45m,1 Stop,New Delhi,Mumbai,4931,2021-11-15,Economy
6,Air India,15:05,3h 10m,1 Stop,New Delhi,Mumbai,5416,2021-11-15,Economy
7,Air Asia,20:00,6h 25m,1 Stop,New Delhi,Mumbai,5953,2021-11-15,Economy
8,Air Asia,21:25,9h 20m,1 Stop,New Delhi,Mumbai,5953,2021-11-15,Economy
9,Air Asia,21:25,9h 50m,1 Stop,New Delhi,Mumbai,5953,2021-11-15,Economy
10,Air Asia,20:45,10h 00m,1 Stop,New Delhi,Mumbai,5953,2021-11-15,Economy
11,Air Asia,20:45,10h 30m,1 Stop,New Delhi,Mumbai,5953,2021-11-15,Economy
12,Air Asia,09:35,11h 00m,1 Stop,New Delhi,Mumbai,5953,2021-11-15,Economy
13,Air Asia,20:00,11h 40m,1 Stop,New Delhi,Mumbai,5953,2021-11-15,Economy
14,Air Asia,18:35,12h 10m,1 Stop,New Delhi,Mumbai,5953,2021-11-15,Economy
15,Air Asia,08:00,12h 35m,1 Stop,New Delhi,Mumbai,5953,2021-11-15,Economy
16,Air Asia,18:35,12h 40m,1 Stop,New Delhi,Mumbai,5953,2021-11-15,Economy
17,Go First,07:00,2h 10m,Non Stop,New Delhi,Mumbai,5954,2021-11-15,Economy
18,Go First,08:00,2h 10m,Non Stop,New Delhi,Mumbai,5954,2021-11-15,Economy
19,Go First,22:30,2h 10m,Non Stop,New Delhi,Mumbai,5954,2021-11-15,Economy
20,Go First,02:00,2h 15m,Non Stop,New Delhi,Mumbai,5954,2021-11-15,Economy
21,Go First,15:00,2h 15m,Non Stop,New Delhi,Mumbai,5954,2021-11-15,Economy
22,Go First,19:40,2h 15m,Non Stop,New Delhi,Mumbai,5954,2021-11-15,Economy
23,Go First,21:00,2h 15m,Non Stop,New Delhi,Mumbai,5954,2021-11-15,Economy
24,Go First,10:30,2h 20m,Non Stop,New Delhi,Mumbai,5954,2021-11-15,Economy
25,Go First,18:05,2h 20m,Non Stop,New Delhi,Mumbai,5954,2021-11-15,Economy
26,Go First,12:20,5h 50m,1 Stop,New Delhi,Mumbai,5954,2021-11-15,Economy
27,Go First,11:50,6h 20m,1 Stop,New Delhi,Mumbai,5954,2021-11-15,Economy
28,Go First,09:00,6h 45m,1 Stop,New Delhi,Mumbai,5954,2021-11-15,Economy
29,Go First,13:45,8h 35m,2 Stop(s),New Delhi,Mumbai,5954,2021-11-15,Economy
30,Go First,09:15,8h 55m,1 Stop,New Delhi,Mumbai,5954,2021-11-15,Economy
31,Vistara,06:00,2h 00m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
32,IndiGo,08:10,2h 10m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
33,Vistara,09:30,2h 10m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
34,Vistara,12:50,2h 10m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
35,Vistara,15:30,2h 10m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
36,Vistara,16:55,2h 10m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
37,SpiceJet,18:55,2h 10m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
38,Vistara,19:50,2h 10m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
39,Vistara,20:40,2h 10m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
40,Vistara,21:40,2h 10m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
41,SpiceJet,07:20,2h 15m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
42,Vistara,07:30,2h 15m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
43,Vistara,10:20,2h 15m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
44,SpiceJet,06:20,2h 20m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
45,Vistara,08:50,2h 20m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
46,Vistara,11:40,2h 20m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
47,Vistara,17:45,2h 20m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
48,Vistara,18:55,2h 20m,Non Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
49,SpiceJet,06:35,3h 40m,1 Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
50,SpiceJet,13:00,5h 00m,1 Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
51,IndiGo,17:55,5h 20m,1 Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
52,SpiceJet,11:20,6h 40m,1 Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
53,IndiGo,12:55,7h 50m,1 Stop,New Delhi,Mumbai,5955,2021-11-15,Economy
54,IndiGo,12:55,10h 30m,1 Stop,New Delhi,Mumbai,5955,2021-11-15,Economy

In [17]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','28','10','2021','Special')

y1 = pd.DataFrame({})
y1['airlines'] = airlines
y1['departure'] = departure
y1['duration'] = duration
y1['stops'] = stops
y1['from_city'] = 'New Delhi'
y1['to_city'] = to_city
y1['price'] = price
y1['journey_date'] = '2021-10-28'
y1['fclass'] = 'Special'
y1

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,21:40,2h 10m,Non Stop,New Delhi,Mumbai,7278,2021-10-28,Special
1,Vistara Premium Economy,20:35,14h 05m,1 Stop,New Delhi,Mumbai,11422,2021-10-28,Special
2,Vistara Premium Economy,20:35,18h 25m,1 Stop,New Delhi,Mumbai,11422,2021-10-28,Special
3,Vistara Premium Economy,19:45,2h 15m,Non Stop,New Delhi,Mumbai,12318,2021-10-28,Special
4,Vistara Premium Economy,18:55,2h 20m,Non Stop,New Delhi,Mumbai,12318,2021-10-28,Special
5,Vistara Premium Economy,20:35,26h 25m,1 Stop,New Delhi,Mumbai,14670,2021-10-28,Special
6,Vistara Premium Economy,20:30,26h 45m,1 Stop,New Delhi,Mumbai,15678,2021-10-28,Special
7,Vistara Premium Economy,20:40,11h 45m,1 Stop,New Delhi,Mumbai,17582,2021-10-28,Special
8,Vistara Premium Economy,19:50,12h 35m,1 Stop,New Delhi,Mumbai,17582,2021-10-28,Special
9,Vistara Premium Economy,20:40,14h 45m,1 Stop,New Delhi,Mumbai,17582,2021-10-28,Special
10,Vistara Premium Economy,19:50,15h 35m,1 Stop,New Delhi,Mumbai,17582,2021-10-28,Special
11,Vistara Premium Economy,20:40,26h 45m,1 Stop,New Delhi,Mumbai,24815,2021-10-28,Special
12,Vistara Premium Economy,19:50,27h 35m,1 Stop,New Delhi,Mumbai,24815,2021-10-28,Special
13,Vistara Premium Economy,20:40,23h 35m,1 Stop,New Delhi,Mumbai,29695,2021-10-28,Special
14,Vistara Premium Economy,19:50,24h 25m,1 Stop,New Delhi,Mumbai,29695,2021-10-28,Special
15,Vistara Premium Economy,20:40,25h 10m,1 Stop,New Delhi,Mumbai,29695,2021-10-28,Special
16,Vistara Premium Economy,19:50,26h 00m,1 Stop,New Delhi,Mumbai,29695,2021-10-28,Special

In [18]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','30','10','2021','Special')

y2 = pd.DataFrame({})
y2['airlines'] = airlines
y2['departure'] = departure
y2['duration'] = duration
y2['stops'] = stops
y2['from_city'] = 'New Delhi'
y2['to_city'] = to_city
y2['price'] = price
y2['journey_date'] = '2021-10-30'
y2['fclass'] = 'Special'
y2

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,15:10,2h 05m,Non Stop,New Delhi,Mumbai,6942,2021-10-30,Special
1,Vistara Premium Economy,21:40,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-10-30,Special
2,Vistara Premium Economy,22:40,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-10-30,Special
3,Vistara Premium Economy,19:45,2h 15m,Non Stop,New Delhi,Mumbai,6942,2021-10-30,Special
4,Vistara Premium Economy,06:00,2h 00m,Non Stop,New Delhi,Mumbai,7278,2021-10-30,Special
5,Vistara Premium Economy,17:45,2h 20m,Non Stop,New Delhi,Mumbai,7278,2021-10-30,Special
6,Vistara Premium Economy,17:10,4h 25m,1 Stop,New Delhi,Mumbai,10806,2021-10-30,Special
7,Vistara Premium Economy,17:10,17h 50m,1 Stop,New Delhi,Mumbai,10806,2021-10-30,Special
8,Vistara Premium Economy,20:35,13h 25m,1 Stop,New Delhi,Mumbai,11422,2021-10-30,Special
9,Vistara Premium Economy,20:35,26h 25m,1 Stop,New Delhi,Mumbai,11422,2021-10-30,Special
10,Vistara Premium Economy,07:10,26h 50m,1 Stop,New Delhi,Mumbai,11758,2021-10-30,Special
11,Vistara Premium Economy,07:10,15h 50m,1 Stop,New Delhi,Mumbai,12038,2021-10-30,Special
12,Vistara Premium Economy,09:30,2h 10m,Non Stop,New Delhi,Mumbai,12318,2021-10-30,Special
13,Vistara Premium Economy,16:55,2h 10m,Non Stop,New Delhi,Mumbai,12318,2021-10-30,Special
14,Vistara Premium Economy,08:50,2h 20m,Non Stop,New Delhi,Mumbai,12318,2021-10-30,Special
15,Vistara Premium Economy,18:55,2h 20m,Non Stop,New Delhi,Mumbai,12318,2021-10-30,Special
16,Vistara Premium Economy,17:10,4h 35m,1 Stop,New Delhi,Mumbai,13830,2021-10-30,Special
17,Vistara Premium Economy,13:20,26h 40m,1 Stop,New Delhi,Mumbai,14390,2021-10-30,Special
18,Vistara Premium Economy,20:40,11h 35m,1 Stop,New Delhi,Mumbai,14446,2021-10-30,Special
19,Vistara Premium Economy,19:50,12h 25m,1 Stop,New Delhi,Mumbai,14446,2021-10-30,Special
20,Vistara Premium Economy,17:35,14h 40m,1 Stop,New Delhi,Mumbai,14446,2021-10-30,Special
21,Vistara Premium Economy,20:40,26h 45m,1 Stop,New Delhi,Mumbai,14446,2021-10-30,Special
22,Vistara Premium Economy,19:50,27h 35m,1 Stop,New Delhi,Mumbai,14446,2021-10-30,Special
23,Vistara Premium Economy,13:40,7h 55m,1 Stop,New Delhi,Mumbai,14726,2021-10-30,Special
24,Vistara Premium Economy,13:40,21h 20m,1 Stop,New Delhi,Mumbai,14726,2021-10-30,Special
25,Vistara Premium Economy,07:10,7h 50m,1 Stop,New Delhi,Mumbai,15006,2021-10-30,Special
26,Vistara Premium Economy,08:10,24h 05m,1 Stop,New Delhi,Mumbai,17022,2021-10-30,Special
27,Vistara Premium Economy,17:45,16h 15m,1 Stop,New Delhi,Mumbai,17414,2021-10-30,Special
28,Vistara Premium Economy,14:45,19h 15m,1 Stop,New Delhi,Mumbai,17414,2021-10-30,Special
29,Vistara Premium Economy,17:35,5h 50m,1 Stop,New Delhi,Mumbai,17582,2021-10-30,Special
30,Vistara Premium Economy,20:40,23h 35m,1 Stop,New Delhi,Mumbai,17582,2021-10-30,Special
31,Vistara Premium Economy,20:40,24h 00m,1 Stop,New Delhi,Mumbai,17582,2021-10-30,Special
32,Vistara Premium Economy,19:50,24h 25m,1 Stop,New Delhi,Mumbai,17582,2021-10-30,Special
33,Vistara Premium Economy,19:50,24h 50m,1 Stop,New Delhi,Mumbai,17582,2021-10-30,Special
34,Vistara Premium Economy,20:40,25h 10m,1 Stop,New Delhi,Mumbai,17582,2021-10-30,Special
35,Vistara Premium Economy,19:50,26h 00m,1 Stop,New Delhi,Mumbai,17582,2021-10-30,Special
36,Vistara Premium Economy,17:35,26h 40m,1 Stop,New Delhi,Mumbai,17582,2021-10-30,Special
37,Vistara Premium Economy,17:35,27h 05m,1 Stop,New Delhi,Mumbai,17582,2021-10-30,Special
38,Vistara Premium Economy,17:45,5h 15m,1 Stop,New Delhi,Mumbai,17694,2021-10-30,Special
39,Vistara Premium Economy,14:45,8h 15m,1 Stop,New Delhi,Mumbai,17694,2021-10-30,Special
40,Vistara Premium Economy,13:20,5h 00m,1 Stop,New Delhi,Mumbai,18366,2021-10-30,Special
41,Vistara Premium Economy,16:05,16h 10m,1 Stop,New Delhi,Mumbai,19318,2021-10-30,Special
42,Vistara Premium Economy,06:20,6h 10m,1 Stop,New Delhi,Mumbai,20102,2021-10-30,Special
43,Vistara Premium Economy,08:10,13h 40m,1 Stop,New Delhi,Mumbai,20158,2021-10-30,Special
44,Vistara Premium Economy,08:10,15h 15m,1 Stop,New Delhi,Mumbai,20158,2021-10-30,Special
45,Vistara Premium Economy,17:10,21h 35m,1 Stop,New Delhi,Mumbai,21726,2021-10-30,Special
46,Vistara Premium Economy,16:05,5h 45m,1 Stop,New Delhi,Mumbai,22454,2021-10-30,Special
47,Vistara Premium Economy,16:05,7h 20m,1 Stop,New Delhi,Mumbai,22454,2021-10-30,Special
48,Vistara Premium Economy,08:10,12h 05m,1 Stop,New Delhi,Mumbai,22622,2021-10-30,Special
49,Vistara Premium Economy,14:10,18h 05m,1 Stop,New Delhi,Mumbai,22678,2021-10-30,Special
50,Vistara Premium Economy,20:40,14h 45m,1 Stop,New Delhi,Mumbai,25646,2021-10-30,Special
51,Vistara Premium Economy,19:50,15h 35m,1 Stop,New Delhi,Mumbai,25646,2021-10-30,Special
52,Vistara Premium Economy,17:35,17h 50m,1 Stop,New Delhi,Mumbai,25646,2021-10-30,Special
53,Vistara Premium Economy,14:10,7h 40m,1 Stop,New Delhi,Mumbai,25814,2021-10-30,Special
54,Vistara Premium Economy,14:10,9h 15m,1 Stop,New Delhi,Mumbai,25814,2021-10-30,Special
55,Vistara Premium Economy,11:10,10h 35m,1 Stop,New Delhi,Mumbai,28110,2021-10-30,Special
56,Vistara Premium Economy,14:10,6h 05m,1 Stop,New Delhi,Mumbai,28278,2021-10-30,Special
57,Vistara Premium Economy,11:10,27h 35m,1 Stop,New Delhi,Mumbai,36006,2021-10-30,Special

In [19]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','2','11','2021','Special')

y3 = pd.DataFrame({})
y3['airlines'] = airlines
y3['departure'] = departure
y3['duration'] = duration
y3['stops'] = stops
y3['from_city'] = 'New Delhi'
y3['to_city'] = to_city
y3['price'] = price
y3['journey_date'] = '2021-11-2'
y3['fclass'] = 'Special'
y3

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,06:00,2h 00m,Non Stop,New Delhi,Mumbai,6942,2021-11-2,Special
1,Vistara Premium Economy,09:30,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-2,Special
2,Vistara Premium Economy,16:55,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-2,Special
3,Vistara Premium Economy,19:50,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-2,Special
4,Vistara Premium Economy,20:40,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-2,Special
5,Vistara Premium Economy,21:40,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-2,Special
6,Vistara Premium Economy,07:30,2h 15m,Non Stop,New Delhi,Mumbai,6942,2021-11-2,Special
7,Vistara Premium Economy,10:20,2h 15m,Non Stop,New Delhi,Mumbai,6942,2021-11-2,Special
8,Vistara Premium Economy,08:50,2h 20m,Non Stop,New Delhi,Mumbai,6942,2021-11-2,Special
9,Vistara Premium Economy,11:40,2h 20m,Non Stop,New Delhi,Mumbai,6942,2021-11-2,Special
10,Vistara Premium Economy,17:45,2h 20m,Non Stop,New Delhi,Mumbai,6942,2021-11-2,Special
11,Vistara Premium Economy,18:55,2h 20m,Non Stop,New Delhi,Mumbai,6942,2021-11-2,Special
12,Vistara Premium Economy,12:50,2h 10m,Non Stop,New Delhi,Mumbai,7278,2021-11-2,Special
13,Vistara Premium Economy,13:20,26h 40m,1 Stop,New Delhi,Mumbai,10050,2021-11-2,Special
14,Vistara Premium Economy,17:10,4h 25m,1 Stop,New Delhi,Mumbai,10526,2021-11-2,Special
15,Vistara Premium Economy,17:10,18h 20m,1 Stop,New Delhi,Mumbai,10526,2021-11-2,Special
16,Vistara Premium Economy,14:45,8h 15m,1 Stop,New Delhi,Mumbai,11422,2021-11-2,Special
17,Vistara Premium Economy,20:35,13h 25m,1 Stop,New Delhi,Mumbai,11422,2021-11-2,Special
18,Vistara Premium Economy,07:05,15h 55m,1 Stop,New Delhi,Mumbai,11422,2021-11-2,Special
19,Vistara Premium Economy,14:45,19h 15m,1 Stop,New Delhi,Mumbai,11422,2021-11-2,Special
20,Vistara Premium Economy,20:35,26h 25m,1 Stop,New Delhi,Mumbai,11422,2021-11-2,Special
21,Vistara Premium Economy,07:05,26h 55m,1 Stop,New Delhi,Mumbai,11422,2021-11-2,Special
22,Vistara Premium Economy,13:40,25h 35m,1 Stop,New Delhi,Mumbai,11430,2021-11-2,Special
23,Vistara Premium Economy,17:40,5h 20m,1 Stop,New Delhi,Mumbai,11758,2021-11-2,Special
24,Vistara Premium Economy,17:40,16h 20m,1 Stop,New Delhi,Mumbai,11758,2021-11-2,Special
25,Vistara Premium Economy,15:30,2h 10m,Non Stop,New Delhi,Mumbai,12318,2021-11-2,Special
26,Vistara Premium Economy,13:40,7h 55m,1 Stop,New Delhi,Mumbai,13158,2021-11-2,Special
27,Vistara Premium Economy,13:40,21h 50m,1 Stop,New Delhi,Mumbai,13158,2021-11-2,Special
28,Vistara Premium Economy,16:05,5h 45m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
29,Vistara Premium Economy,17:35,5h 50m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
30,Vistara Premium Economy,14:15,6h 00m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
31,Vistara Premium Economy,14:15,6h 25m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
32,Vistara Premium Economy,16:05,7h 20m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
33,Vistara Premium Economy,14:15,7h 35m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
34,Vistara Premium Economy,14:15,9h 10m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
35,Vistara Premium Economy,20:40,11h 35m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
36,Vistara Premium Economy,08:05,12h 10m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
37,Vistara Premium Economy,08:05,12h 35m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
38,Vistara Premium Economy,20:40,13h 35m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
39,Vistara Premium Economy,08:05,13h 45m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
40,Vistara Premium Economy,17:35,14h 40m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
41,Vistara Premium Economy,08:05,15h 20m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
42,Vistara Premium Economy,16:05,16h 10m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
43,Vistara Premium Economy,17:35,16h 40m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
44,Vistara Premium Economy,14:15,18h 00m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
45,Vistara Premium Economy,20:40,23h 35m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
46,Vistara Premium Economy,08:05,24h 10m,1 Stop,New Delhi,Mumbai,14138,2021-11-2,Special
47,Vistara Premium Economy,13:20,5h 00m,1 Stop,New Delhi,Mumbai,15902,2021-11-2,Special
48,Vistara Premium Economy,20:40,14h 45m,1 Stop,New Delhi,Mumbai,17582,2021-11-2,Special
49,Vistara Premium Economy,17:35,17h 50m,1 Stop,New Delhi,Mumbai,17582,2021-11-2,Special
50,Vistara Premium Economy,11:10,27h 35m,1 Stop,New Delhi,Mumbai,23294,2021-11-2,Special

In [20]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','4','11','2021','Special')

y4 = pd.DataFrame({})
y4['airlines'] = airlines
y4['departure'] = departure
y4['duration'] = duration
y4['stops'] = stops
y4['from_city'] = 'New Delhi'
y4['to_city'] = to_city
y4['price'] = price
y4['journey_date'] = '2021-11-4'
y4['fclass'] = 'Special'
y4

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,06:00,2h 00m,Non Stop,New Delhi,Mumbai,6942,2021-11-4,Special
1,Vistara Premium Economy,09:30,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-4,Special
2,Vistara Premium Economy,12:50,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-4,Special
3,Vistara Premium Economy,15:30,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-4,Special
4,Vistara Premium Economy,16:55,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-4,Special
5,Vistara Premium Economy,07:30,2h 15m,Non Stop,New Delhi,Mumbai,6942,2021-11-4,Special
6,Vistara Premium Economy,10:20,2h 15m,Non Stop,New Delhi,Mumbai,6942,2021-11-4,Special
7,Vistara Premium Economy,08:50,2h 20m,Non Stop,New Delhi,Mumbai,6942,2021-11-4,Special
8,Vistara Premium Economy,11:40,2h 20m,Non Stop,New Delhi,Mumbai,6942,2021-11-4,Special
9,Vistara Premium Economy,17:45,2h 20m,Non Stop,New Delhi,Mumbai,6942,2021-11-4,Special
10,Vistara Premium Economy,13:20,26h 40m,1 Stop,New Delhi,Mumbai,10050,2021-11-4,Special
11,Vistara Premium Economy,13:40,7h 55m,1 Stop,New Delhi,Mumbai,10526,2021-11-4,Special
12,Vistara Premium Economy,13:40,21h 50m,1 Stop,New Delhi,Mumbai,10526,2021-11-4,Special
13,Vistara Premium Economy,20:35,13h 25m,1 Stop,New Delhi,Mumbai,11422,2021-11-4,Special
14,Vistara Premium Economy,07:05,26h 55m,1 Stop,New Delhi,Mumbai,11422,2021-11-4,Special
15,Vistara Premium Economy,13:40,25h 35m,1 Stop,New Delhi,Mumbai,11430,2021-11-4,Special
16,Vistara Premium Economy,14:15,6h 00m,1 Stop,New Delhi,Mumbai,14138,2021-11-4,Special
17,Vistara Premium Economy,14:15,6h 25m,1 Stop,New Delhi,Mumbai,14138,2021-11-4,Special
18,Vistara Premium Economy,08:05,12h 10m,1 Stop,New Delhi,Mumbai,14138,2021-11-4,Special
19,Vistara Premium Economy,08:05,12h 35m,1 Stop,New Delhi,Mumbai,14138,2021-11-4,Special
20,Vistara Premium Economy,06:15,14h 00m,1 Stop,New Delhi,Mumbai,14138,2021-11-4,Special
21,Vistara Premium Economy,06:15,14h 25m,1 Stop,New Delhi,Mumbai,14138,2021-11-4,Special
22,Vistara Premium Economy,16:05,18h 10m,1 Stop,New Delhi,Mumbai,14138,2021-11-4,Special
23,Vistara Premium Economy,16:05,19h 20m,1 Stop,New Delhi,Mumbai,14138,2021-11-4,Special
24,Vistara Premium Economy,14:15,20h 00m,1 Stop,New Delhi,Mumbai,14138,2021-11-4,Special
25,Vistara Premium Economy,14:15,21h 10m,1 Stop,New Delhi,Mumbai,14138,2021-11-4,Special
26,Vistara Premium Economy,08:05,26h 10m,1 Stop,New Delhi,Mumbai,14138,2021-11-4,Special
27,Vistara Premium Economy,08:05,27h 20m,1 Stop,New Delhi,Mumbai,14138,2021-11-4,Special
28,Vistara Premium Economy,06:15,28h 00m,1 Stop,New Delhi,Mumbai,14138,2021-11-4,Special
29,Vistara Premium Economy,16:05,28h 10m,1 Stop,New Delhi,Mumbai,14138,2021-11-4,Special
30,Vistara Premium Economy,13:20,5h 00m,1 Stop,New Delhi,Mumbai,15902,2021-11-4,Special
31,Vistara Premium Economy,11:10,27h 35m,1 Stop,New Delhi,Mumbai,19710,2021-11-4,Special

In [21]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','6','11','2021','Special')

y5 = pd.DataFrame({})
y5['airlines'] = airlines
y5['departure'] = departure
y5['duration'] = duration
y5['stops'] = stops
y5['from_city'] = 'New Delhi'
y5['to_city'] = to_city
y5['price'] = price
y5['journey_date'] = '2021-11-6'
y5['fclass'] = 'Special'
y5

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,06:00,2h 00m,Non Stop,New Delhi,Mumbai,6942,2021-11-6,Special
1,Vistara Premium Economy,09:30,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-6,Special
2,Vistara Premium Economy,19:50,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-6,Special
3,Vistara Premium Economy,20:40,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-6,Special
4,Vistara Premium Economy,21:40,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-6,Special
5,Vistara Premium Economy,07:30,2h 15m,Non Stop,New Delhi,Mumbai,6942,2021-11-6,Special
6,Vistara Premium Economy,10:20,2h 15m,Non Stop,New Delhi,Mumbai,6942,2021-11-6,Special
7,Vistara Premium Economy,08:50,2h 20m,Non Stop,New Delhi,Mumbai,6942,2021-11-6,Special
8,Vistara Premium Economy,18:55,2h 20m,Non Stop,New Delhi,Mumbai,6942,2021-11-6,Special
9,Vistara Premium Economy,12:50,2h 10m,Non Stop,New Delhi,Mumbai,7278,2021-11-6,Special
10,Vistara Premium Economy,15:30,2h 10m,Non Stop,New Delhi,Mumbai,7278,2021-11-6,Special
11,Vistara Premium Economy,11:40,2h 20m,Non Stop,New Delhi,Mumbai,7278,2021-11-6,Special
12,Vistara Premium Economy,17:45,2h 20m,Non Stop,New Delhi,Mumbai,7278,2021-11-6,Special
13,Vistara Premium Economy,17:40,5h 20m,1 Stop,New Delhi,Mumbai,11422,2021-11-6,Special
14,Vistara Premium Economy,07:05,7h 25m,1 Stop,New Delhi,Mumbai,11422,2021-11-6,Special
15,Vistara Premium Economy,20:35,13h 25m,1 Stop,New Delhi,Mumbai,11422,2021-11-6,Special
16,Vistara Premium Economy,07:05,15h 55m,1 Stop,New Delhi,Mumbai,11422,2021-11-6,Special
17,Vistara Premium Economy,17:40,16h 20m,1 Stop,New Delhi,Mumbai,11422,2021-11-6,Special
18,Vistara Premium Economy,07:05,26h 55m,1 Stop,New Delhi,Mumbai,11422,2021-11-6,Special
19,Vistara Premium Economy,14:45,8h 15m,1 Stop,New Delhi,Mumbai,11758,2021-11-6,Special
20,Vistara Premium Economy,14:45,19h 15m,1 Stop,New Delhi,Mumbai,11758,2021-11-6,Special
21,Vistara Premium Economy,16:55,2h 10m,Non Stop,New Delhi,Mumbai,12318,2021-11-6,Special
22,Vistara Premium Economy,06:15,14h 00m,1 Stop,New Delhi,Mumbai,14138,2021-11-6,Special
23,Vistara Premium Economy,06:15,14h 25m,1 Stop,New Delhi,Mumbai,14138,2021-11-6,Special
24,Vistara Premium Economy,06:15,15h 35m,1 Stop,New Delhi,Mumbai,14138,2021-11-6,Special
25,Vistara Premium Economy,06:15,17h 10m,1 Stop,New Delhi,Mumbai,14138,2021-11-6,Special
26,Vistara Premium Economy,06:15,26h 00m,1 Stop,New Delhi,Mumbai,14138,2021-11-6,Special
27,Vistara Premium Economy,06:15,28h 00m,1 Stop,New Delhi,Mumbai,14138,2021-11-6,Special
28,Vistara Premium Economy,20:35,17h 55m,1 Stop,New Delhi,Mumbai,14670,2021-11-6,Special
29,Vistara Premium Economy,17:40,20h 50m,1 Stop,New Delhi,Mumbai,14670,2021-11-6,Special
30,Vistara Premium Economy,20:35,26h 25m,1 Stop,New Delhi,Mumbai,14670,2021-11-6,Special
31,Vistara Premium Economy,13:40,25h 35m,1 Stop,New Delhi,Mumbai,14874,2021-11-6,Special
32,Vistara Premium Economy,14:45,23h 45m,1 Stop,New Delhi,Mumbai,15006,2021-11-6,Special
33,Vistara Premium Economy,13:20,5h 00m,1 Stop,New Delhi,Mumbai,15902,2021-11-6,Special
34,Vistara Premium Economy,08:05,12h 10m,1 Stop,New Delhi,Mumbai,16714,2021-11-6,Special
35,Vistara Premium Economy,08:05,12h 35m,1 Stop,New Delhi,Mumbai,16714,2021-11-6,Special
36,Vistara Premium Economy,08:05,13h 45m,1 Stop,New Delhi,Mumbai,16714,2021-11-6,Special
37,Vistara Premium Economy,08:05,15h 20m,1 Stop,New Delhi,Mumbai,16714,2021-11-6,Special
38,Vistara Premium Economy,08:05,24h 10m,1 Stop,New Delhi,Mumbai,16714,2021-11-6,Special
39,Vistara Premium Economy,08:05,26h 10m,1 Stop,New Delhi,Mumbai,16714,2021-11-6,Special
40,Vistara Premium Economy,16:05,5h 45m,1 Stop,New Delhi,Mumbai,19010,2021-11-6,Special
41,Vistara Premium Economy,17:35,5h 50m,1 Stop,New Delhi,Mumbai,19010,2021-11-6,Special
42,Vistara Premium Economy,16:05,7h 20m,1 Stop,New Delhi,Mumbai,19010,2021-11-6,Special
43,Vistara Premium Economy,20:40,11h 35m,1 Stop,New Delhi,Mumbai,19010,2021-11-6,Special
44,Vistara Premium Economy,19:50,12h 25m,1 Stop,New Delhi,Mumbai,19010,2021-11-6,Special

In [22]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','8','11','2021','Special')

y6 = pd.DataFrame({})
y6['airlines'] = airlines
y6['departure'] = departure
y6['duration'] = duration
y6['stops'] = stops
y6['from_city'] = 'New Delhi'
y6['to_city'] = to_city
y6['price'] = price
y6['journey_date'] = '2021-11-8'
y6['fclass'] = 'Special'
y6

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,06:00,2h 00m,Non Stop,New Delhi,Mumbai,6942,2021-11-8,Special
1,Vistara Premium Economy,09:30,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-8,Special
2,Vistara Premium Economy,12:50,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-8,Special
3,Vistara Premium Economy,16:55,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-8,Special
4,Vistara Premium Economy,19:50,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-8,Special
...,...,...,...,...,...,...,...,...,...
56,Vistara Premium Economy,16:05,16h 10m,1 Stop,New Delhi,Mumbai,22930,2021-11-8,Special
57,Vistara Premium Economy,11:10,27h 35m,1 Stop,New Delhi,Mumbai,25590,2021-11-8,Special
58,Vistara Premium Economy,08:05,12h 10m,1 Stop,New Delhi,Mumbai,30518,2021-11-8,Special
59,Vistara Premium Economy,06:15,14h 00m,1 Stop,New Delhi,Mumbai,30518,2021-11-8,Special
60,Vistara Premium Economy,14:15,6h 00m,1 Stop,New Delhi,Mumbai,33878,2021-11-8,Special

In [23]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','10','11','2021','Special')

y7 = pd.DataFrame({})
y7['airlines'] = airlines
y7['departure'] = departure
y7['duration'] = duration
y7['stops'] = stops
y7['from_city'] = 'New Delhi'
y7['to_city'] = to_city
y7['price'] = price
y7['journey_date'] = '2021-11-10'
y7['fclass'] = 'Special'
y7

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,06:00,2h 00m,Non Stop,New Delhi,Mumbai,6942,2021-11-10,Special
1,Vistara Premium Economy,09:30,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-10,Special
2,Vistara Premium Economy,12:50,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-10,Special
3,Vistara Premium Economy,15:30,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-10,Special
4,Vistara Premium Economy,16:55,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-10,Special
5,Vistara Premium Economy,19:50,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-10,Special
6,Vistara Premium Economy,20:40,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-10,Special
7,Vistara Premium Economy,21:40,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-10,Special
8,Vistara Premium Economy,07:30,2h 15m,Non Stop,New Delhi,Mumbai,6942,2021-11-10,Special
9,Vistara Premium Economy,10:20,2h 15m,Non Stop,New Delhi,Mumbai,6942,2021-11-10,Special
10,Vistara Premium Economy,08:50,2h 20m,Non Stop,New Delhi,Mumbai,6942,2021-11-10,Special
11,Vistara Premium Economy,11:40,2h 20m,Non Stop,New Delhi,Mumbai,6942,2021-11-10,Special
12,Vistara Premium Economy,17:45,2h 20m,Non Stop,New Delhi,Mumbai,7278,2021-11-10,Special
13,Vistara Premium Economy,18:55,2h 20m,Non Stop,New Delhi,Mumbai,7278,2021-11-10,Special
14,Vistara Premium Economy,17:10,18h 20m,1 Stop,New Delhi,Mumbai,10862,2021-11-10,Special
15,Vistara Premium Economy,13:40,21h 50m,1 Stop,New Delhi,Mumbai,10862,2021-11-10,Special
16,Vistara Premium Economy,07:05,7h 25m,1 Stop,New Delhi,Mumbai,11422,2021-11-10,Special
17,Vistara Premium Economy,20:35,13h 25m,1 Stop,New Delhi,Mumbai,11422,2021-11-10,Special
18,Vistara Premium Economy,07:05,15h 55m,1 Stop,New Delhi,Mumbai,11422,2021-11-10,Special
19,Vistara Premium Economy,20:35,17h 55m,1 Stop,New Delhi,Mumbai,11422,2021-11-10,Special
20,Vistara Premium Economy,20:35,26h 25m,1 Stop,New Delhi,Mumbai,11422,2021-11-10,Special
21,Vistara Premium Economy,07:05,26h 55m,1 Stop,New Delhi,Mumbai,11422,2021-11-10,Special
22,Vistara Premium Economy,13:40,25h 35m,1 Stop,New Delhi,Mumbai,11430,2021-11-10,Special
23,Vistara Premium Economy,14:45,8h 15m,1 Stop,New Delhi,Mumbai,11758,2021-11-10,Special
24,Vistara Premium Economy,14:45,19h 15m,1 Stop,New Delhi,Mumbai,11758,2021-11-10,Special
25,Vistara Premium Economy,14:45,23h 45m,1 Stop,New Delhi,Mumbai,11758,2021-11-10,Special
26,Vistara Premium Economy,13:20,5h 00m,1 Stop,New Delhi,Mumbai,12318,2021-11-10,Special
27,Vistara Premium Economy,16:05,5h 45m,1 Stop,New Delhi,Mumbai,14138,2021-11-10,Special
28,Vistara Premium Economy,17:35,5h 50m,1 Stop,New Delhi,Mumbai,14138,2021-11-10,Special
29,Vistara Premium Economy,14:15,6h 00m,1 Stop,New Delhi,Mumbai,14138,2021-11-10,Special
30,Vistara Premium Economy,14:15,6h 25m,1 Stop,New Delhi,Mumbai,14138,2021-11-10,Special
31,Vistara Premium Economy,16:05,7h 20m,1 Stop,New Delhi,Mumbai,14138,2021-11-10,Special
32,Vistara Premium Economy,14:15,7h 35m,1 Stop,New Delhi,Mumbai,14138,2021-11-10,Special
33,Vistara Premium Economy,14:15,9h 10m,1 Stop,New Delhi,Mumbai,14138,2021-11-10,Special
34,Vistara Premium Economy,20:40,11h 35m,1 Stop,New Delhi,Mumbai,14138,2021-11-10,Special

In [24]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','12','11','2021','Special')

y8 = pd.DataFrame({})
y8['airlines'] = airlines
y8['departure'] = departure
y8['duration'] = duration
y8['stops'] = stops
y8['from_city'] = 'New Delhi'
y8['to_city'] = to_city
y8['price'] = price
y8['journey_date'] = '2021-11-12'
y8['fclass'] = 'Special'
y8

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,06:00,2h 00m,Non Stop,New Delhi,Mumbai,6942,2021-11-12,Special
1,Vistara Premium Economy,09:30,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-12,Special
2,Vistara Premium Economy,12:50,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-12,Special
3,Vistara Premium Economy,15:30,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-12,Special
4,Vistara Premium Economy,16:55,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-12,Special
5,Vistara Premium Economy,19:50,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-12,Special
6,Vistara Premium Economy,20:40,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-12,Special
7,Vistara Premium Economy,21:40,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-12,Special
8,Vistara Premium Economy,07:30,2h 15m,Non Stop,New Delhi,Mumbai,6942,2021-11-12,Special
9,Vistara Premium Economy,10:20,2h 15m,Non Stop,New Delhi,Mumbai,6942,2021-11-12,Special
10,Vistara Premium Economy,08:50,2h 20m,Non Stop,New Delhi,Mumbai,6942,2021-11-12,Special
11,Vistara Premium Economy,11:40,2h 20m,Non Stop,New Delhi,Mumbai,6942,2021-11-12,Special
12,Vistara Premium Economy,18:55,2h 20m,Non Stop,New Delhi,Mumbai,6942,2021-11-12,Special
13,Vistara Premium Economy,07:05,7h 25m,1 Stop,New Delhi,Mumbai,11422,2021-11-12,Special
14,Vistara Premium Economy,14:45,8h 15m,1 Stop,New Delhi,Mumbai,11422,2021-11-12,Special
15,Vistara Premium Economy,07:05,15h 55m,1 Stop,New Delhi,Mumbai,11422,2021-11-12,Special
16,Vistara Premium Economy,14:45,19h 15m,1 Stop,New Delhi,Mumbai,11422,2021-11-12,Special
17,Vistara Premium Economy,14:45,23h 45m,1 Stop,New Delhi,Mumbai,11422,2021-11-12,Special
18,Vistara Premium Economy,07:05,26h 55m,1 Stop,New Delhi,Mumbai,11422,2021-11-12,Special
19,Vistara Premium Economy,17:40,5h 20m,1 Stop,New Delhi,Mumbai,11758,2021-11-12,Special
20,Vistara Premium Economy,20:35,13h 25m,1 Stop,New Delhi,Mumbai,11758,2021-11-12,Special
21,Vistara Premium Economy,17:40,16h 20m,1 Stop,New Delhi,Mumbai,11758,2021-11-12,Special
22,Vistara Premium Economy,20:35,17h 55m,1 Stop,New Delhi,Mumbai,11758,2021-11-12,Special
23,Vistara Premium Economy,17:40,20h 50m,1 Stop,New Delhi,Mumbai,11758,2021-11-12,Special
24,Vistara Premium Economy,20:35,26h 25m,1 Stop,New Delhi,Mumbai,11758,2021-11-12,Special
25,Vistara Premium Economy,17:45,2h 20m,Non Stop,New Delhi,Mumbai,12318,2021-11-12,Special
26,Vistara Premium Economy,13:20,5h 00m,1 Stop,New Delhi,Mumbai,12598,2021-11-12,Special
27,Vistara Premium Economy,17:35,5h 50m,1 Stop,New Delhi,Mumbai,14138,2021-11-12,Special
28,Vistara Premium Economy,20:40,11h 35m,1 Stop,New Delhi,Mumbai,14138,2021-11-12,Special
29,Vistara Premium Economy,19:50,12h 25m,1 Stop,New Delhi,Mumbai,14138,2021-11-12,Special
30,Vistara Premium Economy,06:15,14h 00m,1 Stop,New Delhi,Mumbai,14138,2021-11-12,Special
31,Vistara Premium Economy,06:15,14h 25m,1 Stop,New Delhi,Mumbai,14138,2021-11-12,Special
32,Vistara Premium Economy,17:35,14h 40m,1 Stop,New Delhi,Mumbai,14138,2021-11-12,Special
33,Vistara Premium Economy,06:15,15h 35m,1 Stop,New Delhi,Mumbai,14138,2021-11-12,Special
34,Vistara Premium Economy,06:15,17h 10m,1 Stop,New Delhi,Mumbai,14138,2021-11-12,Special
35,Vistara Premium Economy,17:10,18h 20m,1 Stop,New Delhi,Mumbai,14222,2021-11-12,Special
36,Vistara Premium Economy,13:20,26h 40m,1 Stop,New Delhi,Mumbai,14390,2021-11-12,Special
37,Vistara Premium Economy,08:05,12h 10m,1 Stop,New Delhi,Mumbai,15146,2021-11-12,Special
38,Vistara Premium Economy,08:05,12h 35m,1 Stop,New Delhi,Mumbai,15146,2021-11-12,Special
39,Vistara Premium Economy,08:05,13h 45m,1 Stop,New Delhi,Mumbai,15146,2021-11-12,Special
40,Vistara Premium Economy,08:05,15h 20m,1 Stop,New Delhi,Mumbai,15146,2021-11-12,Special
41,Vistara Premium Economy,17:10,4h 25m,1 Stop,New Delhi,Mumbai,16518,2021-11-12,Special
42,Vistara Premium Economy,14:15,6h 00m,1 Stop,New Delhi,Mumbai,16714,2021-11-12,Special
43,Vistara Premium Economy,14:15,6h 25m,1 Stop,New Delhi,Mumbai,16714,2021-11-12,Special
44,Vistara Premium Economy,14:15,7h 35m,1 Stop,New Delhi,Mumbai,16714,2021-11-12,Special
45,Vistara Premium Economy,14:15,9h 10m,1 Stop,New Delhi,Mumbai,16714,2021-11-12,Special
46,Vistara Premium Economy,14:15,18h 00m,1 Stop,New Delhi,Mumbai,16714,2021-11-12,Special
47,Vistara Premium Economy,13:40,21h 50m,1 Stop,New Delhi,Mumbai,16854,2021-11-12,Special
48,Vistara Premium Economy,20:40,13h 35m,1 Stop,New Delhi,Mumbai,17582,2021-11-12,Special
49,Vistara Premium Economy,19:50,14h 25m,1 Stop,New Delhi,Mumbai,17582,2021-11-12,Special
50,Vistara Premium Economy,20:40,14h 45m,1 Stop,New Delhi,Mumbai,17582,2021-11-12,Special
51,Vistara Premium Economy,19:50,15h 35m,1 Stop,New Delhi,Mumbai,17582,2021-11-12,Special
52,Vistara Premium Economy,17:35,16h 40m,1 Stop,New Delhi,Mumbai,17582,2021-11-12,Special
53,Vistara Premium Economy,17:35,17h 50m,1 Stop,New Delhi,Mumbai,17582,2021-11-12,Special
54,Vistara Premium Economy,16:05,5h 45m,1 Stop,New Delhi,Mumbai,19010,2021-11-12,Special
55,Vistara Premium Economy,16:05,7h 20m,1 Stop,New Delhi,Mumbai,19010,2021-11-12,Special
56,Vistara Premium Economy,16:05,16h 10m,1 Stop,New Delhi,Mumbai,19010,2021-11-12,Special
57,Vistara Premium Economy,13:40,7h 55m,1 Stop,New Delhi,Mumbai,19150,2021-11-12,Special
58,Vistara Premium Economy,11:10,27h 35m,1 Stop,New Delhi,Mumbai,31694,2021-11-12,Special

In [25]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','14','11','2021','Special')

y9 = pd.DataFrame({})
y9['airlines'] = airlines
y9['departure'] = departure
y9['duration'] = duration
y9['stops'] = stops
y9['from_city'] = 'New Delhi'
y9['to_city'] = to_city
y9['price'] = price
y9['journey_date'] = '2021-11-14'
y9['fclass'] = 'Special'
y9

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,09:30,2h 10m,Non Stop,New Delhi,Mumbai,6942,2021-11-14,Special
1,Vistara Premium Economy,10:20,2h 15m,Non Stop,New Delhi,Mumbai,6942,2021-11-14,Special
2,Vistara Premium Economy,11:40,2h 20m,Non Stop,New Delhi,Mumbai,6942,2021-11-14,Special
3,Vistara Premium Economy,12:50,2h 10m,Non Stop,New Delhi,Mumbai,7278,2021-11-14,Special
4,Vistara Premium Economy,07:30,2h 15m,Non Stop,New Delhi,Mumbai,7278,2021-11-14,Special
5,Vistara Premium Economy,13:40,25h 35m,1 Stop,New Delhi,Mumbai,9864,2021-11-14,Special
6,Vistara Premium Economy,21:40,2h 10m,Non Stop,New Delhi,Mumbai,10638,2021-11-14,Special
7,Vistara Premium Economy,07:05,7h 25m,1 Stop,New Delhi,Mumbai,11422,2021-11-14,Special
8,Vistara Premium Economy,07:05,15h 55m,1 Stop,New Delhi,Mumbai,11422,2021-11-14,Special
9,Vistara Premium Economy,07:05,26h 55m,1 Stop,New Delhi,Mumbai,11422,2021-11-14,Special
10,Vistara Premium Economy,20:35,13h 25m,1 Stop,New Delhi,Mumbai,11758,2021-11-14,Special
11,Vistara Premium Economy,20:35,17h 55m,1 Stop,New Delhi,Mumbai,11758,2021-11-14,Special
12,Vistara Premium Economy,20:35,26h 25m,1 Stop,New Delhi,Mumbai,11758,2021-11-14,Special
13,Vistara Premium Economy,15:30,2h 10m,Non Stop,New Delhi,Mumbai,12318,2021-11-14,Special
14,Vistara Premium Economy,16:55,2h 10m,Non Stop,New Delhi,Mumbai,12318,2021-11-14,Special
15,Vistara Premium Economy,19:50,2h 10m,Non Stop,New Delhi,Mumbai,12318,2021-11-14,Special
16,Vistara Premium Economy,08:50,2h 20m,Non Stop,New Delhi,Mumbai,12318,2021-11-14,Special
17,Vistara Premium Economy,17:45,2h 20m,Non Stop,New Delhi,Mumbai,12318,2021-11-14,Special
18,Vistara Premium Economy,18:55,2h 20m,Non Stop,New Delhi,Mumbai,12318,2021-11-14,Special
19,Vistara Premium Economy,06:15,14h 25m,1 Stop,New Delhi,Mumbai,14138,2021-11-14,Special
20,Vistara Premium Economy,06:15,26h 00m,1 Stop,New Delhi,Mumbai,14138,2021-11-14,Special
21,Vistara Premium Economy,06:15,28h 00m,1 Stop,New Delhi,Mumbai,14138,2021-11-14,Special
22,Vistara Premium Economy,17:10,18h 20m,1 Stop,New Delhi,Mumbai,14222,2021-11-14,Special
23,Vistara Premium Economy,06:15,15h 35m,1 Stop,New Delhi,Mumbai,14446,2021-11-14,Special
24,Vistara Premium Economy,06:15,17h 10m,1 Stop,New Delhi,Mumbai,14446,2021-11-14,Special
25,Vistara Premium Economy,13:40,21h 50m,1 Stop,New Delhi,Mumbai,14502,2021-11-14,Special
26,Vistara Premium Economy,20:40,11h 35m,1 Stop,New Delhi,Mumbai,15146,2021-11-14,Special
27,Vistara Premium Economy,19:50,12h 25m,1 Stop,New Delhi,Mumbai,15146,2021-11-14,Special
28,Vistara Premium Economy,20:40,13h 35m,1 Stop,New Delhi,Mumbai,15146,2021-11-14,Special
29,Vistara Premium Economy,19:50,14h 25m,1 Stop,New Delhi,Mumbai,15146,2021-11-14,Special
30,Vistara Premium Economy,20:40,23h 35m,1 Stop,New Delhi,Mumbai,15146,2021-11-14,Special
31,Vistara Premium Economy,17:40,5h 20m,1 Stop,New Delhi,Mumbai,15342,2021-11-14,Special
32,Vistara Premium Economy,14:45,8h 15m,1 Stop,New Delhi,Mumbai,15342,2021-11-14,Special
33,Vistara Premium Economy,17:40,16h 20m,1 Stop,New Delhi,Mumbai,15342,2021-11-14,Special
34,Vistara Premium Economy,14:45,19h 15m,1 Stop,New Delhi,Mumbai,15342,2021-11-14,Special
35,Vistara Premium Economy,17:40,20h 50m,1 Stop,New Delhi,Mumbai,15342,2021-11-14,Special
36,Vistara Premium Economy,20:40,14h 45m,1 Stop,New Delhi,Mumbai,15454,2021-11-14,Special
37,Vistara Premium Economy,19:50,15h 35m,1 Stop,New Delhi,Mumbai,15454,2021-11-14,Special
38,Vistara Premium Economy,13:20,5h 00m,1 Stop,New Delhi,Mumbai,15902,2021-11-14,Special
39,Vistara Premium Economy,13:20,26h 40m,1 Stop,New Delhi,Mumbai,16350,2021-11-14,Special
40,Vistara Premium Economy,06:15,14h 00m,1 Stop,New Delhi,Mumbai,17582,2021-11-14,Special
41,Vistara Premium Economy,14:15,6h 25m,1 Stop,New Delhi,Mumbai,19010,2021-11-14,Special
42,Vistara Premium Economy,08:05,12h 35m,1 Stop,New Delhi,Mumbai,19010,2021-11-14,Special
43,Vistara Premium Economy,17:35,14h 40m,1 Stop,New Delhi,Mumbai,19010,2021-11-14,Special
44,Vistara Premium Economy,16:05,16h 10m,1 Stop,New Delhi,Mumbai,19010,2021-11-14,Special
45,Vistara Premium Economy,17:35,16h 40m,1 Stop,New Delhi,Mumbai,19010,2021-11-14,Special
46,Vistara Premium Economy,16:05,5h 45m,1 Stop,New Delhi,Mumbai,19318,2021-11-14,Special
47,Vistara Premium Economy,17:35,5h 50m,1 Stop,New Delhi,Mumbai,19318,2021-11-14,Special
48,Vistara Premium Economy,16:05,7h 20m,1 Stop,New Delhi,Mumbai,19318,2021-11-14,Special
49,Vistara Premium Economy,14:15,7h 35m,1 Stop,New Delhi,Mumbai,19318,2021-11-14,Special
50,Vistara Premium Economy,14:15,9h 10m,1 Stop,New Delhi,Mumbai,19318,2021-11-14,Special
51,Vistara Premium Economy,08:05,13h 45m,1 Stop,New Delhi,Mumbai,19318,2021-11-14,Special
52,Vistara Premium Economy,08:05,15h 20m,1 Stop,New Delhi,Mumbai,19318,2021-11-14,Special
53,Vistara Premium Economy,17:35,17h 50m,1 Stop,New Delhi,Mumbai,19318,2021-11-14,Special
54,Vistara Premium Economy,14:15,6h 00m,1 Stop,New Delhi,Mumbai,22454,2021-11-14,Special
55,Vistara Premium Economy,08:05,12h 10m,1 Stop,New Delhi,Mumbai,22454,2021-11-14,Special
56,Vistara Premium Economy,17:10,4h 25m,1 Stop,New Delhi,Mumbai,22566,2021-11-14,Special
57,Vistara Premium Economy,13:40,7h 55m,1 Stop,New Delhi,Mumbai,22846,2021-11-14,Special
58,Vistara Premium Economy,07:10,7h 35m,1 Stop,New Delhi,Mumbai,23294,2021-11-14,Special
59,Vistara Premium Economy,11:10,27h 35m,1 Stop,New Delhi,Mumbai,30126,2021-11-14,Special

In [27]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','28','10','2021','Business')

z1 = pd.DataFrame({})
z1['airlines'] = airlines
z1['departure'] = departure
z1['duration'] = duration
z1['stops'] = stops
z1['from_city'] = 'New Delhi'
z1['to_city'] = to_city
z1['price'] = price
z1['journey_date'] = '2021-10-28'
z1['fclass'] = 'Business'
z1

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air India Business,20:10,23h 50m,1 Stop,New Delhi,Mumbai,29716,2021-10-28,Business
1,Air India Business,21:25,11h 25m,1 Stop,New Delhi,Mumbai,34622,2021-10-28,Business
2,Air India Business,21:25,12h 15m,1 Stop,New Delhi,Mumbai,34622,2021-10-28,Business
3,Air India Business,21:25,26h 05m,1 Stop,New Delhi,Mumbai,34622,2021-10-28,Business
4,Air India Business,20:00,13h 40m,1 Stop,New Delhi,Mumbai,39620,2021-10-28,Business
5,Vistara Business,20:35,14h 05m,1 Stop,New Delhi,Mumbai,39657,2021-10-28,Business
6,Vistara Business,20:35,26h 25m,1 Stop,New Delhi,Mumbai,39657,2021-10-28,Business
7,Air India Business,21:15,11h 20m,1 Stop,New Delhi,Mumbai,42622,2021-10-28,Business
8,Air India Business,21:15,13h 20m,1 Stop,New Delhi,Mumbai,42622,2021-10-28,Business
9,Air India Business,20:15,20h 30m,2 Stop(s),New Delhi,Mumbai,44622,2021-10-28,Business
10,Air India Business,20:15,24h 00m,1 Stop,New Delhi,Mumbai,44622,2021-10-28,Business
11,Air India Business,21:00,11h 05m,1 Stop,New Delhi,Mumbai,44754,2021-10-28,Business
12,Air India Business,21:15,23h 50m,1 Stop,New Delhi,Mumbai,47102,2021-10-28,Business
13,Vistara Business,20:40,11h 45m,1 Stop,New Delhi,Mumbai,49625,2021-10-28,Business
14,Vistara Business,19:50,12h 35m,1 Stop,New Delhi,Mumbai,49625,2021-10-28,Business
15,Vistara Business,20:30,16h 30m,1 Stop,New Delhi,Mumbai,51641,2021-10-28,Business
16,Vistara Business,20:35,18h 25m,1 Stop,New Delhi,Mumbai,53993,2021-10-28,Business
17,Vistara Business,19:45,2h 15m,Non Stop,New Delhi,Mumbai,58216,2021-10-28,Business
18,Vistara Business,19:55,15h 55m,1 Stop,New Delhi,Mumbai,58826,2021-10-28,Business
19,Vistara Business,19:55,27h 10m,1 Stop,New Delhi,Mumbai,60954,2021-10-28,Business
20,Air India Business,21:00,20h 05m,1 Stop,New Delhi,Mumbai,61678,2021-10-28,Business
21,Vistara Business,20:40,23h 35m,1 Stop,New Delhi,Mumbai,63065,2021-10-28,Business
22,Vistara Business,19:50,24h 25m,1 Stop,New Delhi,Mumbai,63065,2021-10-28,Business
23,Vistara Business,20:40,14h 45m,1 Stop,New Delhi,Mumbai,69785,2021-10-28,Business
24,Vistara Business,19:50,15h 35m,1 Stop,New Delhi,Mumbai,69785,2021-10-28,Business
25,Vistara Business,20:40,25h 10m,1 Stop,New Delhi,Mumbai,72025,2021-10-28,Business
26,Vistara Business,19:50,26h 00m,1 Stop,New Delhi,Mumbai,72025,2021-10-28,Business
27,Vistara Business,20:30,26h 45m,1 Stop,New Delhi,Mumbai,74489,2021-10-28,Business

In [28]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','30','10','2021','Business')

z2 = pd.DataFrame({})
z2['airlines'] = airlines
z2['departure'] = departure
z2['duration'] = duration
z2['stops'] = stops
z2['from_city'] = 'New Delhi'
z2['to_city'] = to_city
z2['price'] = price
z2['journey_date'] = '2021-10-30'
z2['fclass'] = 'Business'
z2

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air India Business,07:00,2h 05m,Non Stop,New Delhi,Mumbai,20012,2021-10-30,Business
1,Air India Business,08:00,2h 10m,Non Stop,New Delhi,Mumbai,20012,2021-10-30,Business
2,Air India Business,10:40,2h 10m,Non Stop,New Delhi,Mumbai,20012,2021-10-30,Business
3,Air India Business,09:00,2h 15m,Non Stop,New Delhi,Mumbai,20012,2021-10-30,Business
4,Air India Business,15:05,3h 10m,1 Stop,New Delhi,Mumbai,20012,2021-10-30,Business
5,Air India Business,18:00,3h 35m,1 Stop,New Delhi,Mumbai,20012,2021-10-30,Business
6,Vistara Business,06:00,2h 00m,Non Stop,New Delhi,Mumbai,20169,2021-10-30,Business
7,Vistara Business,21:40,2h 10m,Non Stop,New Delhi,Mumbai,20169,2021-10-30,Business
8,Vistara Business,09:30,2h 10m,Non Stop,New Delhi,Mumbai,22152,2021-10-30,Business
9,Vistara Business,19:45,2h 15m,Non Stop,New Delhi,Mumbai,22152,2021-10-30,Business
10,Vistara Business,22:40,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-10-30,Business
11,Vistara Business,08:50,2h 20m,Non Stop,New Delhi,Mumbai,24056,2021-10-30,Business
12,Vistara Business,17:45,2h 20m,Non Stop,New Delhi,Mumbai,24056,2021-10-30,Business
13,Vistara Business,18:55,2h 20m,Non Stop,New Delhi,Mumbai,24056,2021-10-30,Business
14,Vistara Business,10:20,2h 10m,Non Stop,New Delhi,Mumbai,27752,2021-10-30,Business
15,Air India Business,13:20,4h 30m,1 Stop,New Delhi,Mumbai,29628,2021-10-30,Business
16,Air India Business,20:10,23h 30m,1 Stop,New Delhi,Mumbai,29716,2021-10-30,Business
17,Air India Business,13:00,24h 35m,1 Stop,New Delhi,Mumbai,29776,2021-10-30,Business
18,Air India Business,12:50,6h 35m,1 Stop,New Delhi,Mumbai,29777,2021-10-30,Business
19,Air India Business,12:50,19h 05m,1 Stop,New Delhi,Mumbai,29777,2021-10-30,Business
20,Vistara Business,13:20,26h 40m,1 Stop,New Delhi,Mumbai,30249,2021-10-30,Business
21,Air India Business,12:10,20h 35m,1 Stop,New Delhi,Mumbai,31622,2021-10-30,Business
22,Air India Business,04:55,9h 30m,1 Stop,New Delhi,Mumbai,32212,2021-10-30,Business
23,Vistara Business,17:10,4h 35m,1 Stop,New Delhi,Mumbai,32377,2021-10-30,Business
24,Vistara Business,08:15,6h 30m,1 Stop,New Delhi,Mumbai,32377,2021-10-30,Business
25,Vistara Business,08:15,8h 15m,1 Stop,New Delhi,Mumbai,32377,2021-10-30,Business
26,Vistara Business,08:15,13h 30m,1 Stop,New Delhi,Mumbai,32377,2021-10-30,Business
27,Vistara Business,17:10,23h 45m,1 Stop,New Delhi,Mumbai,32377,2021-10-30,Business
28,Vistara Business,13:20,5h 00m,1 Stop,New Delhi,Mumbai,34617,2021-10-30,Business
29,Air India Business,21:25,12h 15m,1 Stop,New Delhi,Mumbai,34622,2021-10-30,Business
30,Air India Business,09:45,13h 45m,1 Stop,New Delhi,Mumbai,34622,2021-10-30,Business
31,Air India Business,08:20,15h 10m,1 Stop,New Delhi,Mumbai,34622,2021-10-30,Business
32,Air India Business,09:45,23h 55m,1 Stop,New Delhi,Mumbai,34622,2021-10-30,Business
33,Air India Business,08:20,25h 20m,1 Stop,New Delhi,Mumbai,34622,2021-10-30,Business
34,Air India Business,21:25,25h 55m,1 Stop,New Delhi,Mumbai,34622,2021-10-30,Business
35,Air India Business,12:10,27h 30m,2 Stop(s),New Delhi,Mumbai,34623,2021-10-30,Business
36,Air India Business,16:35,23h 50m,2 Stop(s),New Delhi,Mumbai,36212,2021-10-30,Business
37,Air India Business,16:45,24h 00m,1 Stop,New Delhi,Mumbai,37863,2021-10-30,Business
38,Air India Business,14:00,26h 45m,1 Stop,New Delhi,Mumbai,37863,2021-10-30,Business
39,Air India Business,12:10,5h 00m,1 Stop,New Delhi,Mumbai,39622,2021-10-30,Business
40,Air India Business,18:40,22h 45m,1 Stop,New Delhi,Mumbai,39622,2021-10-30,Business
41,Air India Business,15:00,25h 25m,1 Stop,New Delhi,Mumbai,39622,2021-10-30,Business
42,Vistara Business,07:10,7h 50m,1 Stop,New Delhi,Mumbai,39657,2021-10-30,Business
43,Vistara Business,20:35,26h 25m,1 Stop,New Delhi,Mumbai,39657,2021-10-30,Business
44,Vistara Business,20:35,13h 25m,1 Stop,New Delhi,Mumbai,43017,2021-10-30,Business
45,Vistara Business,17:45,16h 15m,1 Stop,New Delhi,Mumbai,43017,2021-10-30,Business
46,Vistara Business,14:45,19h 15m,1 Stop,New Delhi,Mumbai,43017,2021-10-30,Business
47,Vistara Business,16:55,2h 10m,Non Stop,New Delhi,Mumbai,45896,2021-10-30,Business
48,Vistara Business,17:45,5h 15m,1 Stop,New Delhi,Mumbai,50521,2021-10-30,Business
49,Vistara Business,14:45,8h 15m,1 Stop,New Delhi,Mumbai,50521,2021-10-30,Business
50,Vistara Business,07:10,15h 50m,1 Stop,New Delhi,Mumbai,50521,2021-10-30,Business
51,Vistara Business,15:10,2h 05m,Non Stop,New Delhi,Mumbai,51496,2021-10-30,Business
52,Vistara Business,12:45,2h 10m,Non Stop,New Delhi,Mumbai,51496,2021-10-30,Business
53,Vistara Business,11:10,5h 20m,1 Stop,New Delhi,Mumbai,62841,2021-10-30,Business
54,Vistara Business,11:10,10h 35m,1 Stop,New Delhi,Mumbai,62841,2021-10-30,Business

In [29]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','2','11','2021','Business')

z3 = pd.DataFrame({})
z3['airlines'] = airlines
z3['departure'] = departure
z3['duration'] = duration
z3['stops'] = stops
z3['from_city'] = 'New Delhi'
z3['to_city'] = to_city
z3['price'] = price
z3['journey_date'] = '2021-11-2'
z3['fclass'] = 'Business'
z3

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Business,20:40,2h 10m,Non Stop,New Delhi,Mumbai,22152,2021-11-2,Business
1,Air India Business,08:00,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-2,Business
2,Air India Business,10:40,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-2,Business
3,Air India Business,17:50,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-2,Business
4,Air India Business,20:00,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-2,Business
...,...,...,...,...,...,...,...,...,...
61,Vistara Business,14:45,8h 15m,1 Stop,New Delhi,Mumbai,56233,2021-11-2,Business
62,Vistara Business,14:45,19h 15m,1 Stop,New Delhi,Mumbai,56233,2021-11-2,Business
63,Vistara Business,07:05,15h 55m,1 Stop,New Delhi,Mumbai,63513,2021-11-2,Business
64,Vistara Business,11:10,5h 45m,1 Stop,New Delhi,Mumbai,68441,2021-11-2,Business
65,Vistara Business,11:10,12h 00m,1 Stop,New Delhi,Mumbai,68441,2021-11-2,Business

In [31]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','5','11','2021','Business')

z4 = pd.DataFrame({})
z4['airlines'] = airlines
z4['departure'] = departure
z4['duration'] = duration
z4['stops'] = stops
z4['from_city'] = 'New Delhi'
z4['to_city'] = to_city
z4['price'] = price
z4['journey_date'] = '2021-11-5'
z4['fclass'] = 'Business'
z4

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Business,20:40,2h 10m,Non Stop,New Delhi,Mumbai,22152,2021-11-5,Business
1,Air India Business,07:00,2h 05m,Non Stop,New Delhi,Mumbai,23496,2021-11-5,Business
2,Air India Business,08:00,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-5,Business
3,Air India Business,10:40,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-5,Business
4,Air India Business,17:50,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-5,Business
...,...,...,...,...,...,...,...,...,...
75,Vistara Business,08:05,13h 45m,1 Stop,New Delhi,Mumbai,59481,2021-11-5,Business
76,Vistara Business,16:05,16h 10m,1 Stop,New Delhi,Mumbai,59481,2021-11-5,Business
77,Vistara Business,14:15,6h 00m,1 Stop,New Delhi,Mumbai,62908,2021-11-5,Business
78,Vistara Business,08:05,12h 10m,1 Stop,New Delhi,Mumbai,68105,2021-11-5,Business
79,Vistara Business,11:10,5h 45m,1 Stop,New Delhi,Mumbai,68441,2021-11-5,Business

In [32]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','8','11','2021','Business')

z5 = pd.DataFrame({})
z5['airlines'] = airlines
z5['departure'] = departure
z5['duration'] = duration
z5['stops'] = stops
z5['from_city'] = 'New Delhi'
z5['to_city'] = to_city
z5['price'] = price
z5['journey_date'] = '2021-11-8'
z5['fclass'] = 'Business'
z5

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air India Business,07:00,2h 05m,Non Stop,New Delhi,Mumbai,23496,2021-11-8,Business
1,Air India Business,08:00,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-8,Business
2,Air India Business,10:40,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-8,Business
3,Air India Business,17:50,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-8,Business
4,Air India Business,09:00,2h 15m,Non Stop,New Delhi,Mumbai,23496,2021-11-8,Business
5,Air India Business,15:05,3h 10m,1 Stop,New Delhi,Mumbai,23496,2021-11-8,Business
6,Air India Business,17:50,3h 45m,1 Stop,New Delhi,Mumbai,23496,2021-11-8,Business
7,Vistara Business,20:40,2h 10m,Non Stop,New Delhi,Mumbai,29656,2021-11-8,Business
8,Air India Business,20:00,2h 10m,Non Stop,New Delhi,Mumbai,29697,2021-11-8,Business
9,Air India Business,05:55,3h 50m,1 Stop,New Delhi,Mumbai,33670,2021-11-8,Business
10,Air India Business,05:55,17h 30m,1 Stop,New Delhi,Mumbai,33670,2021-11-8,Business
11,Vistara Business,06:00,2h 00m,Non Stop,New Delhi,Mumbai,34472,2021-11-8,Business
12,Vistara Business,15:30,2h 10m,Non Stop,New Delhi,Mumbai,34472,2021-11-8,Business
13,Vistara Business,21:40,2h 10m,Non Stop,New Delhi,Mumbai,34472,2021-11-8,Business
14,Vistara Business,10:20,2h 15m,Non Stop,New Delhi,Mumbai,34472,2021-11-8,Business
15,Vistara Business,09:30,2h 10m,Non Stop,New Delhi,Mumbai,36376,2021-11-8,Business
16,Vistara Business,11:40,2h 20m,Non Stop,New Delhi,Mumbai,36376,2021-11-8,Business
17,Vistara Business,08:50,2h 20m,Non Stop,New Delhi,Mumbai,36712,2021-11-8,Business
18,Vistara Business,17:45,2h 20m,Non Stop,New Delhi,Mumbai,36712,2021-11-8,Business
19,Vistara Business,18:55,2h 20m,Non Stop,New Delhi,Mumbai,36712,2021-11-8,Business
20,Vistara Business,16:55,2h 10m,Non Stop,New Delhi,Mumbai,37496,2021-11-8,Business
21,Air India Business,16:45,4h 30m,1 Stop,New Delhi,Mumbai,38830,2021-11-8,Business
22,Air India Business,10:15,5h 25m,1 Stop,New Delhi,Mumbai,39310,2021-11-8,Business
23,Vistara Business,13:20,26h 40m,1 Stop,New Delhi,Mumbai,39495,2021-11-8,Business
24,Vistara Business,13:40,25h 35m,1 Stop,New Delhi,Mumbai,39536,2021-11-8,Business
25,Air India Business,13:00,26h 50m,1 Stop,New Delhi,Mumbai,39617,2021-11-8,Business
26,Air India Business,12:50,19h 00m,1 Stop,New Delhi,Mumbai,40323,2021-11-8,Business
27,Air India Business,13:00,24h 35m,1 Stop,New Delhi,Mumbai,40323,2021-11-8,Business
28,Air India Business,21:10,12h 30m,1 Stop,New Delhi,Mumbai,41449,2021-11-8,Business
29,Air India Business,09:45,14h 10m,1 Stop,New Delhi,Mumbai,41449,2021-11-8,Business
30,Air India Business,08:10,15h 45m,1 Stop,New Delhi,Mumbai,41449,2021-11-8,Business
31,Air India Business,09:45,23h 55m,1 Stop,New Delhi,Mumbai,41449,2021-11-8,Business
32,Air India Business,08:10,25h 30m,1 Stop,New Delhi,Mumbai,41449,2021-11-8,Business
33,Air India Business,16:45,23h 40m,2 Stop(s),New Delhi,Mumbai,41839,2021-11-8,Business
34,Vistara Business,12:50,2h 10m,Non Stop,New Delhi,Mumbai,41976,2021-11-8,Business
35,Vistara Business,19:50,2h 10m,Non Stop,New Delhi,Mumbai,42312,2021-11-8,Business
36,Vistara Business,17:40,5h 20m,1 Stop,New Delhi,Mumbai,42793,2021-11-8,Business
37,Vistara Business,14:45,8h 15m,1 Stop,New Delhi,Mumbai,42793,2021-11-8,Business
38,Vistara Business,20:35,13h 25m,1 Stop,New Delhi,Mumbai,42793,2021-11-8,Business
39,Vistara Business,17:40,16h 20m,1 Stop,New Delhi,Mumbai,42793,2021-11-8,Business
40,Vistara Business,20:35,17h 55m,1 Stop,New Delhi,Mumbai,42793,2021-11-8,Business
41,Vistara Business,14:45,19h 15m,1 Stop,New Delhi,Mumbai,42793,2021-11-8,Business
42,Vistara Business,17:40,20h 50m,1 Stop,New Delhi,Mumbai,42793,2021-11-8,Business
43,Vistara Business,14:45,23h 45m,1 Stop,New Delhi,Mumbai,42793,2021-11-8,Business
44,Vistara Business,20:35,26h 25m,1 Stop,New Delhi,Mumbai,42793,2021-11-8,Business
45,Vistara Business,07:05,7h 25m,1 Stop,New Delhi,Mumbai,43017,2021-11-8,Business
46,Vistara Business,07:05,15h 55m,1 Stop,New Delhi,Mumbai,43017,2021-11-8,Business
47,Vistara Business,07:05,26h 55m,1 Stop,New Delhi,Mumbai,43017,2021-11-8,Business
48,Air India Business,07:05,6h 20m,1 Stop,New Delhi,Mumbai,43926,2021-11-8,Business
49,Air India Business,18:30,18h 55m,1 Stop,New Delhi,Mumbai,43926,2021-11-8,Business
50,Vistara Business,17:10,18h 20m,1 Stop,New Delhi,Mumbai,43964,2021-11-8,Business
51,Vistara Business,07:30,2h 15m,Non Stop,New Delhi,Mumbai,44216,2021-11-8,Business
52,Air India Business,14:30,25h 55m,1 Stop,New Delhi,Mumbai,44408,2021-11-8,Business
53,Vistara Business,13:20,5h 00m,1 Stop,New Delhi,Mumbai,46265,2021-11-8,Business
54,Vistara Business,18:40,22h 15m,1 Stop,New Delhi,Mumbai,48337,2021-11-8,Business
55,Vistara Business,11:10,12h 00m,1 Stop,New Delhi,Mumbai,55001,2021-11-8,Business
56,Air India Business,05:30,10h 55m,1 Stop,New Delhi,Mumbai,55038,2021-11-8,Business
57,Vistara Business,11:10,5h 45m,1 Stop,New Delhi,Mumbai,58361,2021-11-8,Business
58,Vistara Business,17:10,4h 25m,1 Stop,New Delhi,Mumbai,59929,2021-11-8,Business
59,Vistara Business,13:40,7h 55m,1 Stop,New Delhi,Mumbai,70009,2021-11-8,Business

In [33]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','11','11','2021','Business')

z6 = pd.DataFrame({})
z6['airlines'] = airlines
z6['departure'] = departure
z6['duration'] = duration
z6['stops'] = stops
z6['from_city'] = 'New Delhi'
z6['to_city'] = to_city
z6['price'] = price
z6['journey_date'] = '2021-11-11'
z6['fclass'] = 'Business'
z6

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Business,20:40,2h 10m,Non Stop,New Delhi,Mumbai,22152,2021-11-11,Business
1,Air India Business,07:00,2h 05m,Non Stop,New Delhi,Mumbai,23496,2021-11-11,Business
2,Air India Business,08:00,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-11,Business
3,Air India Business,10:40,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-11,Business
4,Air India Business,17:50,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-11,Business
...,...,...,...,...,...,...,...,...,...
61,Vistara Business,19:55,15h 45m,1 Stop,New Delhi,Mumbai,50969,2021-11-11,Business
62,Vistara Business,17:25,18h 15m,1 Stop,New Delhi,Mumbai,50969,2021-11-11,Business
63,Vistara Business,19:55,18h 35m,1 Stop,New Delhi,Mumbai,50969,2021-11-11,Business
64,Vistara Business,13:30,19h 30m,1 Stop,New Delhi,Mumbai,50969,2021-11-11,Business
65,Vistara Business,17:25,21h 05m,1 Stop,New Delhi,Mumbai,50969,2021-11-11,Business

In [34]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BOM','14','11','2021','Business')

z7 = pd.DataFrame({})
z7['airlines'] = airlines
z7['departure'] = departure
z7['duration'] = duration
z7['stops'] = stops
z7['from_city'] = 'New Delhi'
z7['to_city'] = to_city
z7['price'] = price
z7['journey_date'] = '2021-11-14'
z7['fclass'] = 'Business'
z7

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Business,20:40,2h 10m,Non Stop,New Delhi,Mumbai,22152,2021-11-14,Business
1,Air India Business,07:00,2h 05m,Non Stop,New Delhi,Mumbai,23496,2021-11-14,Business
2,Air India Business,08:00,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-14,Business
3,Air India Business,10:40,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-14,Business
4,Air India Business,17:50,2h 10m,Non Stop,New Delhi,Mumbai,23496,2021-11-14,Business
...,...,...,...,...,...,...,...,...,...
65,Vistara Business,14:45,19h 15m,1 Stop,New Delhi,Mumbai,56457,2021-11-14,Business
66,Vistara Business,11:10,12h 00m,1 Stop,New Delhi,Mumbai,60041,2021-11-14,Business
67,Vistara Business,07:10,7h 35m,1 Stop,New Delhi,Mumbai,60433,2021-11-14,Business
68,Vistara Business,18:40,20h 05m,1 Stop,New Delhi,Mumbai,60433,2021-11-14,Business
69,Vistara Business,11:10,27h 35m,1 Stop,New Delhi,Mumbai,72137,2021-11-14,Business

In [35]:
del_mum = pd.concat([x,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,y1,y2,y3,y4,y5,y6,y7,y8,y9,z1,z2,z3,z4,z5,z6,z7], axis = 0)
del_mum.shape
del_mum.to_excel('delhimum.xlsx')

In [37]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','28','10','2021','Economy')

x1 = pd.DataFrame({})
x1['airlines'] = airlines
x1['departure'] = departure
x1['duration'] = duration
x1['stops'] = stops
x1['from_city'] = 'New Delhi'
x1['to_city'] = to_city
x1['price'] = price
x1['journey_date'] = '2021-10-28'
x1['fclass'] = 'Economy'
x1

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Go First,19:45,2h 35m,Non Stop,New Delhi,Bangalore,7424,2021-10-28,Economy
1,Go First,22:45,9h 00m,1 Stop,New Delhi,Bangalore,7424,2021-10-28,Economy
2,Go First,21:30,10h 15m,1 Stop,New Delhi,Bangalore,7424,2021-10-28,Economy
3,Vistara,20:40,2h 40m,Non Stop,New Delhi,Bangalore,7425,2021-10-28,Economy
4,SpiceJet,21:50,2h 45m,Non Stop,New Delhi,Bangalore,7425,2021-10-28,Economy
5,SpiceJet,22:40,2h 45m,Non Stop,New Delhi,Bangalore,7425,2021-10-28,Economy
6,Vistara,19:50,2h 50m,Non Stop,New Delhi,Bangalore,7425,2021-10-28,Economy
7,IndiGo,20:15,2h 50m,Non Stop,New Delhi,Bangalore,7425,2021-10-28,Economy
8,SpiceJet,20:05,3h 05m,Non Stop,New Delhi,Bangalore,7425,2021-10-28,Economy
9,IndiGo,22:00,8h 50m,1 Stop,New Delhi,Bangalore,7425,2021-10-28,Economy
10,IndiGo,22:00,10h 15m,1 Stop,New Delhi,Bangalore,7425,2021-10-28,Economy
11,IndiGo,22:00,11h 35m,1 Stop,New Delhi,Bangalore,7425,2021-10-28,Economy
12,IndiGo,22:20,2h 45m,Non Stop,New Delhi,Bangalore,7845,2021-10-28,Economy
13,Vistara,20:35,12h 15m,1 Stop,New Delhi,Bangalore,9840,2021-10-28,Economy
14,Air India,21:25,13h 55m,1 Stop,New Delhi,Bangalore,10260,2021-10-28,Economy
15,Air India,21:25,24h 55m,1 Stop,New Delhi,Bangalore,10260,2021-10-28,Economy
16,Air India,21:00,14h 20m,2 Stop(s),New Delhi,Bangalore,10470,2021-10-28,Economy
17,IndiGo,19:15,4h 50m,1 Stop,New Delhi,Bangalore,10654,2021-10-28,Economy
18,Air India,20:00,11h 55m,1 Stop,New Delhi,Bangalore,10680,2021-10-28,Economy
19,Air India,20:00,15h 10m,1 Stop,New Delhi,Bangalore,10680,2021-10-28,Economy
20,IndiGo,19:15,11h 35m,1 Stop,New Delhi,Bangalore,10785,2021-10-28,Economy
21,Vistara,21:40,20h 05m,1 Stop,New Delhi,Bangalore,11520,2021-10-28,Economy
22,Vistara,21:40,11h 10m,1 Stop,New Delhi,Bangalore,11730,2021-10-28,Economy
23,Vistara,21:40,13h 05m,1 Stop,New Delhi,Bangalore,11730,2021-10-28,Economy
24,Air India,20:00,23h 00m,1 Stop,New Delhi,Bangalore,12045,2021-10-28,Economy
25,Vistara,21:40,23h 15m,1 Stop,New Delhi,Bangalore,12308,2021-10-28,Economy
26,Vistara,21:40,25h 10m,1 Stop,New Delhi,Bangalore,12308,2021-10-28,Economy
27,Air India,20:15,21h 20m,1 Stop,New Delhi,Bangalore,12780,2021-10-28,Economy
28,Vistara,20:35,21h 10m,2 Stop(s),New Delhi,Bangalore,13024,2021-10-28,Economy
29,Vistara,20:35,21h 10m,2 Stop(s),New Delhi,Bangalore,13024,2021-10-28,Economy
30,Vistara,20:35,24h 20m,2 Stop(s),New Delhi,Bangalore,14200,2021-10-28,Economy
31,Vistara,20:30,21h 15m,2 Stop(s),New Delhi,Bangalore,16170,2021-10-28,Economy
32,Vistara,20:30,24h 25m,2 Stop(s),New Delhi,Bangalore,17911,2021-10-28,Economy
33,Vistara,20:30,26h 20m,2 Stop(s),New Delhi,Bangalore,17911,2021-10-28,Economy

In [38]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','29','10','2021','Economy')

x2 = pd.DataFrame({})
x2['airlines'] = airlines
x2['departure'] = departure
x2['duration'] = duration
x2['stops'] = stops
x2['from_city'] = 'New Delhi'
x2['to_city'] = to_city
x2['price'] = price
x2['journey_date'] = '2021-10-29'
x2['fclass'] = 'Economy'
x2

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air Asia,15:40,4h 55m,1 Stop,New Delhi,Bangalore,7423,2021-10-29,Economy
1,Air Asia,08:50,5h 10m,1 Stop,New Delhi,Bangalore,7423,2021-10-29,Economy
2,Air Asia,09:25,5h 15m,1 Stop,New Delhi,Bangalore,7423,2021-10-29,Economy
3,Air Asia,12:40,5h 40m,1 Stop,New Delhi,Bangalore,7423,2021-10-29,Economy
4,Air Asia,11:55,6h 25m,1 Stop,New Delhi,Bangalore,7423,2021-10-29,Economy
...,...,...,...,...,...,...,...,...,...
136,Air India,14:00,9h 40m,1 Stop,New Delhi,Bangalore,19951,2021-10-29,Economy
137,Air India,19:00,12h 55m,1 Stop,New Delhi,Bangalore,21075,2021-10-29,Economy
138,Air India,10:35,13h 05m,1 Stop,New Delhi,Bangalore,21526,2021-10-29,Economy
139,Air India,19:00,23h 30m,1 Stop,New Delhi,Bangalore,22965,2021-10-29,Economy
140,Air India,19:00,16h 10m,1 Stop,New Delhi,Bangalore,29580,2021-10-29,Economy

In [39]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','31','10','2021','Economy')

x3 = pd.DataFrame({})
x3['airlines'] = airlines
x3['departure'] = departure
x3['duration'] = duration
x3['stops'] = stops
x3['from_city'] = 'New Delhi'
x3['to_city'] = to_city
x3['price'] = price
x3['journey_date'] = '2021-10-31'
x3['fclass'] = 'Economy'
x3

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air Asia,16:05,4h 35m,1 Stop,New Delhi,Bangalore,7423,2021-10-31,Economy
1,Air Asia,15:40,6h 05m,1 Stop,New Delhi,Bangalore,7423,2021-10-31,Economy
2,Air Asia,05:00,6h 35m,1 Stop,New Delhi,Bangalore,7423,2021-10-31,Economy
3,Air Asia,07:10,6h 45m,1 Stop,New Delhi,Bangalore,7423,2021-10-31,Economy
4,Air Asia,07:10,7h 00m,1 Stop,New Delhi,Bangalore,7423,2021-10-31,Economy
...,...,...,...,...,...,...,...,...,...
156,Air India,21:10,17h 35m,2 Stop(s),New Delhi,Bangalore,18030,2021-10-31,Economy
157,Air India,20:15,20h 30m,1 Stop,New Delhi,Bangalore,19710,2021-10-31,Economy
158,Air India,16:55,6h 25m,1 Stop,New Delhi,Bangalore,21390,2021-10-31,Economy
159,Air India,10:40,7h 50m,1 Stop,New Delhi,Bangalore,21810,2021-10-31,Economy
160,Air India,09:25,13h 55m,2 Stop(s),New Delhi,Bangalore,30105,2021-10-31,Economy

In [40]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','2','11','2021','Economy')

x4 = pd.DataFrame({})
x4['airlines'] = airlines
x4['departure'] = departure
x4['duration'] = duration
x4['stops'] = stops
x4['from_city'] = 'New Delhi'
x4['to_city'] = to_city
x4['price'] = price
x4['journey_date'] = '2021-11-2'
x4['fclass'] = 'Economy'
x4

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air Asia,16:05,4h 35m,1 Stop,New Delhi,Bangalore,7423,2021-11-2,Economy
1,Air Asia,15:25,5h 15m,1 Stop,New Delhi,Bangalore,7423,2021-11-2,Economy
2,Air Asia,07:10,6h 50m,1 Stop,New Delhi,Bangalore,7423,2021-11-2,Economy
3,Air Asia,07:10,7h 00m,1 Stop,New Delhi,Bangalore,7423,2021-11-2,Economy
4,Air Asia,16:50,7h 30m,1 Stop,New Delhi,Bangalore,7423,2021-11-2,Economy
...,...,...,...,...,...,...,...,...,...
157,Air India,07:05,14h 40m,1 Stop,New Delhi,Bangalore,14670,2021-11-2,Economy
158,Air India,16:55,6h 25m,1 Stop,New Delhi,Bangalore,15510,2021-11-2,Economy
159,Air India,06:50,16h 30m,1 Stop,New Delhi,Bangalore,17295,2021-11-2,Economy
160,Go First,11:30,5h 40m,1 Stop,New Delhi,Bangalore,21181,2021-11-2,Economy
161,Air India,09:25,13h 55m,2 Stop(s),New Delhi,Bangalore,29055,2021-11-2,Economy

In [43]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','4','11','2021','Economy')

x5 = pd.DataFrame({})
x5['airlines'] = airlines
x5['departure'] = departure
x5['duration'] = duration
x5['stops'] = stops
x5['from_city'] = 'New Delhi'
x5['to_city'] = to_city
x5['price'] = price
x5['journey_date'] = '2021-11-4'
x5['fclass'] = 'Economy'
x5

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air Asia,16:05,4h 35m,1 Stop,New Delhi,Bangalore,7423,2021-11-4,Economy
1,Air Asia,09:25,5h 15m,1 Stop,New Delhi,Bangalore,7423,2021-11-4,Economy
2,Air Asia,05:00,6h 35m,1 Stop,New Delhi,Bangalore,7423,2021-11-4,Economy
3,Air Asia,07:10,6h 45m,1 Stop,New Delhi,Bangalore,7423,2021-11-4,Economy
4,Air Asia,07:10,7h 00m,1 Stop,New Delhi,Bangalore,7423,2021-11-4,Economy
...,...,...,...,...,...,...,...,...,...
155,Vistara,07:30,8h 30m,2 Stop(s),New Delhi,Bangalore,18608,2021-11-4,Economy
156,Vistara,06:00,10h 00m,2 Stop(s),New Delhi,Bangalore,18608,2021-11-4,Economy
157,Air India,16:45,7h 10m,1 Stop,New Delhi,Bangalore,19951,2021-11-4,Economy
158,Go First,11:30,5h 40m,1 Stop,New Delhi,Bangalore,21181,2021-11-4,Economy
159,SpiceJet,06:30,6h 20m,1 Stop,New Delhi,Bangalore,24434,2021-11-4,Economy

In [44]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','6','11','2021','Economy')

x6 = pd.DataFrame({})
x6['airlines'] = airlines
x6['departure'] = departure
x6['duration'] = duration
x6['stops'] = stops
x6['from_city'] = 'New Delhi'
x6['to_city'] = to_city
x6['price'] = price
x6['journey_date'] = '2021-11-6'
x6['fclass'] = 'Economy'
x6

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air Asia,15:40,6h 05m,1 Stop,New Delhi,Bangalore,7423,2021-11-6,Economy
1,Air Asia,05:00,6h 35m,1 Stop,New Delhi,Bangalore,7423,2021-11-6,Economy
2,Air Asia,16:50,7h 30m,1 Stop,New Delhi,Bangalore,7423,2021-11-6,Economy
3,Go First,05:35,4h 45m,1 Stop,New Delhi,Bangalore,7424,2021-11-6,Economy
4,Go First,02:00,5h 40m,1 Stop,New Delhi,Bangalore,7424,2021-11-6,Economy
...,...,...,...,...,...,...,...,...,...
165,Air India,16:55,6h 25m,1 Stop,New Delhi,Bangalore,24120,2021-11-6,Economy
166,SpiceJet,06:30,6h 20m,1 Stop,New Delhi,Bangalore,24540,2021-11-6,Economy
167,Air India,06:50,16h 30m,1 Stop,New Delhi,Bangalore,25590,2021-11-6,Economy
168,Air India,14:10,27h 45m,2 Stop(s),New Delhi,Bangalore,27585,2021-11-6,Economy
169,Vistara,17:10,25h 05m,1 Stop,New Delhi,Bangalore,28005,2021-11-6,Economy

In [45]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','8','11','2021','Economy')

x7 = pd.DataFrame({})
x7['airlines'] = airlines
x7['departure'] = departure
x7['duration'] = duration
x7['stops'] = stops
x7['from_city'] = 'New Delhi'
x7['to_city'] = to_city
x7['price'] = price
x7['journey_date'] = '2021-11-8'
x7['fclass'] = 'Economy'
x7

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air Asia,09:25,5h 15m,1 Stop,New Delhi,Bangalore,7423,2021-11-8,Economy
1,Air Asia,15:40,6h 05m,1 Stop,New Delhi,Bangalore,7423,2021-11-8,Economy
2,Air Asia,05:00,6h 35m,1 Stop,New Delhi,Bangalore,7423,2021-11-8,Economy
3,Air Asia,07:10,6h 45m,1 Stop,New Delhi,Bangalore,7423,2021-11-8,Economy
4,Air Asia,07:10,7h 00m,1 Stop,New Delhi,Bangalore,7423,2021-11-8,Economy
...,...,...,...,...,...,...,...,...,...
164,Air India,07:00,11h 30m,1 Stop,New Delhi,Bangalore,21075,2021-11-8,Economy
165,Go First,11:30,5h 40m,1 Stop,New Delhi,Bangalore,21181,2021-11-8,Economy
166,Air India,16:45,7h 10m,1 Stop,New Delhi,Bangalore,21526,2021-11-8,Economy
167,Air India,10:35,13h 20m,1 Stop,New Delhi,Bangalore,21526,2021-11-8,Economy
168,Air India,05:15,11h 30m,2 Stop(s),New Delhi,Bangalore,24120,2021-11-8,Economy

In [46]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','10','11','2021','Economy')

x8 = pd.DataFrame({})
x8['airlines'] = airlines
x8['departure'] = departure
x8['duration'] = duration
x8['stops'] = stops
x8['from_city'] = 'New Delhi'
x8['to_city'] = to_city
x8['price'] = price
x8['journey_date'] = '2021-11-10'
x8['fclass'] = 'Economy'
x8

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air Asia,09:25,5h 15m,1 Stop,New Delhi,Bangalore,7423,2021-11-10,Economy
1,Air Asia,15:40,6h 05m,1 Stop,New Delhi,Bangalore,7423,2021-11-10,Economy
2,Air Asia,05:00,6h 35m,1 Stop,New Delhi,Bangalore,7423,2021-11-10,Economy
3,Air Asia,07:10,6h 45m,1 Stop,New Delhi,Bangalore,7423,2021-11-10,Economy
4,Air Asia,07:10,7h 00m,1 Stop,New Delhi,Bangalore,7423,2021-11-10,Economy
...,...,...,...,...,...,...,...,...,...
158,Air India,20:15,20h 30m,1 Stop,New Delhi,Bangalore,16035,2021-11-10,Economy
159,Go First,10:45,4h 25m,1 Stop,New Delhi,Bangalore,16209,2021-11-10,Economy
160,Vistara,11:10,4h 50m,1 Stop,New Delhi,Bangalore,17400,2021-11-10,Economy
161,Go First,16:30,7h 10m,1 Stop,New Delhi,Bangalore,19683,2021-11-10,Economy
162,SpiceJet,12:00,21h 00m,1 Stop,New Delhi,Bangalore,24121,2021-11-10,Economy

In [47]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','12','11','2021','Economy')

x9 = pd.DataFrame({})
x9['airlines'] = airlines
x9['departure'] = departure
x9['duration'] = duration
x9['stops'] = stops
x9['from_city'] = 'New Delhi'
x9['to_city'] = to_city
x9['price'] = price
x9['journey_date'] = '2021-11-12'
x9['fclass'] = 'Economy'
x9

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air India,17:20,2h 45m,Non Stop,New Delhi,Bangalore,6739,2021-11-12,Economy
1,Air Asia,09:25,5h 15m,1 Stop,New Delhi,Bangalore,7423,2021-11-12,Economy
2,Air Asia,15:40,6h 05m,1 Stop,New Delhi,Bangalore,7423,2021-11-12,Economy
3,Air Asia,05:00,6h 35m,1 Stop,New Delhi,Bangalore,7423,2021-11-12,Economy
4,Air Asia,07:10,6h 45m,1 Stop,New Delhi,Bangalore,7423,2021-11-12,Economy
...,...,...,...,...,...,...,...,...,...
159,IndiGo,13:50,5h 10m,1 Stop,New Delhi,Bangalore,15195,2021-11-12,Economy
160,Vistara,18:15,18h 45m,1 Stop,New Delhi,Bangalore,15961,2021-11-12,Economy
161,Vistara,09:40,11h 05m,1 Stop,New Delhi,Bangalore,16140,2021-11-12,Economy
162,Vistara,11:10,4h 50m,1 Stop,New Delhi,Bangalore,21390,2021-11-12,Economy
163,Go First,10:45,4h 25m,1 Stop,New Delhi,Bangalore,26232,2021-11-12,Economy

In [48]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','14','11','2021','Economy')

x10 = pd.DataFrame({})
x10['airlines'] = airlines
x10['departure'] = departure
x10['duration'] = duration
x10['stops'] = stops
x10['from_city'] = 'New Delhi'
x10['to_city'] = to_city
x10['price'] = price
x10['journey_date'] = '2021-11-14'
x10['fclass'] = 'Economy'
x10

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air Asia,15:40,6h 05m,1 Stop,New Delhi,Bangalore,7423,2021-11-14,Economy
1,Air Asia,16:50,7h 30m,1 Stop,New Delhi,Bangalore,7423,2021-11-14,Economy
2,Go First,06:05,2h 35m,Non Stop,New Delhi,Bangalore,7424,2021-11-14,Economy
3,Go First,05:35,4h 45m,1 Stop,New Delhi,Bangalore,7424,2021-11-14,Economy
4,Go First,02:00,5h 40m,1 Stop,New Delhi,Bangalore,7424,2021-11-14,Economy
...,...,...,...,...,...,...,...,...,...
164,Go First,10:45,4h 25m,1 Stop,New Delhi,Bangalore,19450,2021-11-14,Economy
165,Go First,15:30,8h 10m,1 Stop,New Delhi,Bangalore,19683,2021-11-14,Economy
166,Go First,09:10,4h 20m,1 Stop,New Delhi,Bangalore,21444,2021-11-14,Economy
167,Air India,10:15,24h 55m,2 Stop(s),New Delhi,Bangalore,24190,2021-11-14,Economy
168,Air India,10:15,8h 15m,2 Stop(s),New Delhi,Bangalore,24764,2021-11-14,Economy

In [49]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','28','10','2021','Special')

y1 = pd.DataFrame({})
y1['airlines'] = airlines
y1['departure'] = departure
y1['duration'] = duration
y1['stops'] = stops
y1['from_city'] = 'New Delhi'
y1['to_city'] = to_city
y1['price'] = price
y1['journey_date'] = '2021-10-28'
y1['fclass'] = 'Special'
y1

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,20:40,2h 40m,Non Stop,New Delhi,Bangalore,8622,2021-10-28,Special
1,Vistara Premium Economy,19:50,2h 50m,Non Stop,New Delhi,Bangalore,8622,2021-10-28,Special
2,Vistara Premium Economy,21:40,11h 10m,1 Stop,New Delhi,Bangalore,12794,2021-10-28,Special
3,Vistara Premium Economy,21:40,20h 05m,1 Stop,New Delhi,Bangalore,12794,2021-10-28,Special
4,Vistara Premium Economy,21:40,23h 15m,1 Stop,New Delhi,Bangalore,13102,2021-10-28,Special
5,Vistara Premium Economy,20:35,21h 10m,2 Stop(s),New Delhi,Bangalore,16162,2021-10-28,Special
6,Vistara Premium Economy,20:35,21h 10m,2 Stop(s),New Delhi,Bangalore,16162,2021-10-28,Special
7,Vistara Premium Economy,21:40,13h 05m,1 Stop,New Delhi,Bangalore,16238,2021-10-28,Special
8,Vistara Premium Economy,21:40,25h 10m,1 Stop,New Delhi,Bangalore,16238,2021-10-28,Special
9,Vistara Premium Economy,19:45,13h 05m,1 Stop,New Delhi,Bangalore,17834,2021-10-28,Special
10,Vistara Premium Economy,19:45,22h 00m,1 Stop,New Delhi,Bangalore,17834,2021-10-28,Special
11,Vistara Premium Economy,19:45,25h 10m,1 Stop,New Delhi,Bangalore,18142,2021-10-28,Special
12,Vistara Premium Economy,19:45,15h 00m,1 Stop,New Delhi,Bangalore,21278,2021-10-28,Special
13,Vistara Premium Economy,19:45,27h 05m,1 Stop,New Delhi,Bangalore,21278,2021-10-28,Special

In [50]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','30','10','2021','Special')

y2 = pd.DataFrame({})
y2['airlines'] = airlines
y2['departure'] = departure
y2['duration'] = duration
y2['stops'] = stops
y2['from_city'] = 'New Delhi'
y2['to_city'] = to_city
y2['price'] = price
y2['journey_date'] = '2021-10-30'
y2['fclass'] = 'Special'
y2

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,20:40,2h 40m,Non Stop,New Delhi,Bangalore,8622,2021-10-30,Special
1,Vistara Premium Economy,17:35,2h 50m,Non Stop,New Delhi,Bangalore,8622,2021-10-30,Special
2,Vistara Premium Economy,19:50,2h 50m,Non Stop,New Delhi,Bangalore,8622,2021-10-30,Special
3,Vistara Premium Economy,08:10,2h 40m,Non Stop,New Delhi,Bangalore,11198,2021-10-30,Special
4,Vistara Premium Economy,15:10,7h 40m,1 Stop,New Delhi,Bangalore,12458,2021-10-30,Special
5,Vistara Premium Economy,22:40,12h 05m,1 Stop,New Delhi,Bangalore,12458,2021-10-30,Special
6,Vistara Premium Economy,21:40,13h 05m,1 Stop,New Delhi,Bangalore,12458,2021-10-30,Special
7,Vistara Premium Economy,19:45,15h 00m,1 Stop,New Delhi,Bangalore,12458,2021-10-30,Special
8,Vistara Premium Economy,15:10,19h 35m,1 Stop,New Delhi,Bangalore,12458,2021-10-30,Special
9,Vistara Premium Economy,22:40,20h 35m,1 Stop,New Delhi,Bangalore,12458,2021-10-30,Special
10,Vistara Premium Economy,21:40,21h 35m,1 Stop,New Delhi,Bangalore,12458,2021-10-30,Special
11,Vistara Premium Economy,22:40,22h 15m,1 Stop,New Delhi,Bangalore,12458,2021-10-30,Special
12,Vistara Premium Economy,21:40,23h 15m,1 Stop,New Delhi,Bangalore,12458,2021-10-30,Special
13,Vistara Premium Economy,19:45,23h 30m,1 Stop,New Delhi,Bangalore,12458,2021-10-30,Special
14,Vistara Premium Economy,22:40,24h 10m,1 Stop,New Delhi,Bangalore,12458,2021-10-30,Special
15,Vistara Premium Economy,19:45,25h 10m,1 Stop,New Delhi,Bangalore,12458,2021-10-30,Special
16,Vistara Premium Economy,21:40,25h 10m,1 Stop,New Delhi,Bangalore,12458,2021-10-30,Special
17,Vistara Premium Economy,19:45,27h 05m,1 Stop,New Delhi,Bangalore,12458,2021-10-30,Special
18,Vistara Premium Economy,15:10,5h 45m,1 Stop,New Delhi,Bangalore,12766,2021-10-30,Special
19,Vistara Premium Economy,17:45,5h 05m,1 Stop,New Delhi,Bangalore,12794,2021-10-30,Special
20,Vistara Premium Economy,06:00,16h 50m,1 Stop,New Delhi,Bangalore,12794,2021-10-30,Special
21,Vistara Premium Economy,17:45,17h 00m,1 Stop,New Delhi,Bangalore,12794,2021-10-30,Special
22,Vistara Premium Economy,17:45,25h 30m,1 Stop,New Delhi,Bangalore,12794,2021-10-30,Special
23,Vistara Premium Economy,17:45,27h 10m,1 Stop,New Delhi,Bangalore,12794,2021-10-30,Special
24,Vistara Premium Economy,06:00,14h 55m,1 Stop,New Delhi,Bangalore,13102,2021-10-30,Special
25,Vistara Premium Economy,16:05,2h 45m,Non Stop,New Delhi,Bangalore,13494,2021-10-30,Special
26,Vistara Premium Economy,17:10,25h 05m,1 Stop,New Delhi,Bangalore,14278,2021-10-30,Special
27,Vistara Premium Economy,17:10,17h 35m,2 Stop(s),New Delhi,Bangalore,15865,2021-10-30,Special
28,Vistara Premium Economy,17:10,26h 05m,2 Stop(s),New Delhi,Bangalore,15865,2021-10-30,Special
29,Vistara Premium Economy,17:10,26h 05m,2 Stop(s),New Delhi,Bangalore,15865,2021-10-30,Special
30,Vistara Premium Economy,17:10,27h 45m,2 Stop(s),New Delhi,Bangalore,15865,2021-10-30,Special
31,Vistara Premium Economy,17:10,27h 45m,2 Stop(s),New Delhi,Bangalore,15865,2021-10-30,Special
32,Vistara Premium Economy,17:10,29h 40m,2 Stop(s),New Delhi,Bangalore,15865,2021-10-30,Special
33,Vistara Premium Economy,17:10,29h 40m,2 Stop(s),New Delhi,Bangalore,15865,2021-10-30,Special
34,Vistara Premium Economy,06:00,4h 45m,1 Stop,New Delhi,Bangalore,16238,2021-10-30,Special
35,Vistara Premium Economy,06:00,11h 45m,1 Stop,New Delhi,Bangalore,16238,2021-10-30,Special
36,Vistara Premium Economy,14:10,2h 45m,Non Stop,New Delhi,Bangalore,16854,2021-10-30,Special
37,Vistara Premium Economy,16:55,5h 55m,1 Stop,New Delhi,Bangalore,17834,2021-10-30,Special
38,Vistara Premium Economy,09:30,13h 20m,1 Stop,New Delhi,Bangalore,17834,2021-10-30,Special
39,Vistara Premium Economy,13:40,4h 50m,1 Stop,New Delhi,Bangalore,18198,2021-10-30,Special
40,Vistara Premium Economy,13:40,21h 05m,2 Stop(s),New Delhi,Bangalore,19785,2021-10-30,Special
41,Vistara Premium Economy,13:40,29h 35m,2 Stop(s),New Delhi,Bangalore,19785,2021-10-30,Special
42,Vistara Premium Economy,13:40,29h 35m,2 Stop(s),New Delhi,Bangalore,19785,2021-10-30,Special
43,Vistara Premium Economy,13:40,31h 15m,2 Stop(s),New Delhi,Bangalore,19785,2021-10-30,Special
44,Vistara Premium Economy,13:40,31h 15m,2 Stop(s),New Delhi,Bangalore,19785,2021-10-30,Special
45,Vistara Premium Economy,13:40,33h 10m,2 Stop(s),New Delhi,Bangalore,19785,2021-10-30,Special
46,Vistara Premium Economy,13:40,33h 10m,2 Stop(s),New Delhi,Bangalore,19785,2021-10-30,Special
47,Vistara Premium Economy,09:30,8h 15m,1 Stop,New Delhi,Bangalore,21278,2021-10-30,Special
48,Vistara Premium Economy,13:20,9h 30m,2 Stop(s),New Delhi,Bangalore,23425,2021-10-30,Special

In [51]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','1','11','2021','Special')

y3 = pd.DataFrame({})
y3['airlines'] = airlines
y3['departure'] = departure
y3['duration'] = duration
y3['stops'] = stops
y3['from_city'] = 'New Delhi'
y3['to_city'] = to_city
y3['price'] = price
y3['journey_date'] = '2021-11-1'
y3['fclass'] = 'Special'
y3

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,20:40,2h 40m,Non Stop,New Delhi,Bangalore,8622,2021-11-1,Special
1,Vistara Premium Economy,06:15,2h 45m,Non Stop,New Delhi,Bangalore,8622,2021-11-1,Special
2,Vistara Premium Economy,08:05,2h 45m,Non Stop,New Delhi,Bangalore,8622,2021-11-1,Special
3,Vistara Premium Economy,14:15,2h 45m,Non Stop,New Delhi,Bangalore,8622,2021-11-1,Special
4,Vistara Premium Economy,16:05,2h 45m,Non Stop,New Delhi,Bangalore,8622,2021-11-1,Special
5,Vistara Premium Economy,17:35,2h 50m,Non Stop,New Delhi,Bangalore,8622,2021-11-1,Special
6,Vistara Premium Economy,19:50,2h 50m,Non Stop,New Delhi,Bangalore,8622,2021-11-1,Special
7,Vistara Premium Economy,06:00,4h 45m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
8,Vistara Premium Economy,17:45,5h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
9,Vistara Premium Economy,16:55,5h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
10,Vistara Premium Economy,11:40,6h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
11,Vistara Premium Economy,10:20,7h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
12,Vistara Premium Economy,11:40,7h 35m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
13,Vistara Premium Economy,09:30,8h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
14,Vistara Premium Economy,08:50,8h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
15,Vistara Premium Economy,10:20,8h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
16,Vistara Premium Economy,11:40,9h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
17,Vistara Premium Economy,09:30,9h 45m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
18,Vistara Premium Economy,21:40,10h 10m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
19,Vistara Premium Economy,07:30,10h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
20,Vistara Premium Economy,08:50,10h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
21,Vistara Premium Economy,10:20,10h 35m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
22,Vistara Premium Economy,11:40,11h 10m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
23,Vistara Premium Economy,20:40,11h 10m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
24,Vistara Premium Economy,09:30,11h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
25,Vistara Premium Economy,06:00,11h 45m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
26,Vistara Premium Economy,07:30,11h 45m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
27,Vistara Premium Economy,19:50,12h 00m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
28,Vistara Premium Economy,08:50,12h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-1,Special
29,Vistara Premium Economy,12:50,4h 55m,1 Stop,New Delhi,Bangalore,12794,2021-11-1,Special
30,Vistara Premium Economy,12:50,6h 25m,1 Stop,New Delhi,Bangalore,12794,2021-11-1,Special
31,Vistara Premium Economy,12:50,8h 05m,1 Stop,New Delhi,Bangalore,12794,2021-11-1,Special
32,Vistara Premium Economy,17:10,25h 05m,1 Stop,New Delhi,Bangalore,13998,2021-11-1,Special
33,Vistara Premium Economy,13:20,29h 55m,2 Stop(s),New Delhi,Bangalore,15348,2021-11-1,Special
34,Vistara Premium Economy,13:20,31h 35m,2 Stop(s),New Delhi,Bangalore,15348,2021-11-1,Special
35,Vistara Premium Economy,13:20,33h 30m,2 Stop(s),New Delhi,Bangalore,15348,2021-11-1,Special
36,Vistara Premium Economy,17:10,14h 40m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-1,Special
37,Vistara Premium Economy,17:10,17h 35m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-1,Special
38,Vistara Premium Economy,13:40,18h 10m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-1,Special
39,Vistara Premium Economy,13:40,21h 05m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-1,Special
40,Vistara Premium Economy,17:10,24h 35m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-1,Special
41,Vistara Premium Economy,17:10,24h 35m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-1,Special
42,Vistara Premium Economy,17:10,26h 05m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-1,Special
43,Vistara Premium Economy,17:10,26h 05m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-1,Special
44,Vistara Premium Economy,17:10,27h 45m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-1,Special
45,Vistara Premium Economy,17:10,27h 45m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-1,Special
46,Vistara Premium Economy,13:40,28h 05m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-1,Special
47,Vistara Premium Economy,13:40,28h 05m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-1,Special
48,Vistara Premium Economy,13:40,29h 35m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-1,Special

In [52]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','3','11','2021','Special')

y4 = pd.DataFrame({})
y4['airlines'] = airlines
y4['departure'] = departure
y4['duration'] = duration
y4['stops'] = stops
y4['from_city'] = 'New Delhi'
y4['to_city'] = to_city
y4['price'] = price
y4['journey_date'] = '2021-11-3'
y4['fclass'] = 'Special'
y4

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,20:40,2h 40m,Non Stop,New Delhi,Bangalore,8622,2021-11-3,Special
1,Vistara Premium Economy,08:05,2h 45m,Non Stop,New Delhi,Bangalore,8622,2021-11-3,Special
2,Vistara Premium Economy,14:15,2h 45m,Non Stop,New Delhi,Bangalore,8622,2021-11-3,Special
3,Vistara Premium Economy,16:05,2h 45m,Non Stop,New Delhi,Bangalore,8622,2021-11-3,Special
4,Vistara Premium Economy,17:35,2h 50m,Non Stop,New Delhi,Bangalore,8622,2021-11-3,Special
5,Vistara Premium Economy,19:50,2h 50m,Non Stop,New Delhi,Bangalore,8622,2021-11-3,Special
6,Vistara Premium Economy,06:00,4h 45m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
7,Vistara Premium Economy,12:50,4h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
8,Vistara Premium Economy,17:45,5h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
9,Vistara Premium Economy,16:55,5h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
10,Vistara Premium Economy,11:40,6h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
11,Vistara Premium Economy,12:50,6h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
12,Vistara Premium Economy,15:30,7h 20m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
13,Vistara Premium Economy,10:20,7h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
14,Vistara Premium Economy,11:40,7h 35m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
15,Vistara Premium Economy,09:30,8h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
16,Vistara Premium Economy,08:50,8h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
17,Vistara Premium Economy,10:20,8h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
18,Vistara Premium Economy,09:30,9h 45m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
19,Vistara Premium Economy,12:50,10h 00m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
20,Vistara Premium Economy,07:30,10h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
21,Vistara Premium Economy,08:50,10h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
22,Vistara Premium Economy,11:40,11h 10m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
23,Vistara Premium Economy,06:00,11h 45m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
24,Vistara Premium Economy,07:30,11h 45m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
25,Vistara Premium Economy,10:20,12h 30m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
26,Vistara Premium Economy,21:40,13h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
27,Vistara Premium Economy,06:00,13h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-3,Special
28,Vistara Premium Economy,15:30,5h 25m,1 Stop,New Delhi,Bangalore,12766,2021-11-3,Special
29,Vistara Premium Economy,12:50,8h 05m,1 Stop,New Delhi,Bangalore,12766,2021-11-3,Special
30,Vistara Premium Economy,11:40,9h 15m,1 Stop,New Delhi,Bangalore,12766,2021-11-3,Special
31,Vistara Premium Economy,10:20,10h 35m,1 Stop,New Delhi,Bangalore,12766,2021-11-3,Special
32,Vistara Premium Economy,09:30,11h 25m,1 Stop,New Delhi,Bangalore,12766,2021-11-3,Special
33,Vistara Premium Economy,17:10,25h 05m,1 Stop,New Delhi,Bangalore,13998,2021-11-3,Special
34,Vistara Premium Economy,13:20,29h 55m,2 Stop(s),New Delhi,Bangalore,15348,2021-11-3,Special
35,Vistara Premium Economy,17:10,17h 35m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-3,Special
36,Vistara Premium Economy,17:10,24h 35m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-3,Special
37,Vistara Premium Economy,17:10,24h 35m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-3,Special
38,Vistara Premium Economy,17:10,26h 05m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-3,Special
39,Vistara Premium Economy,17:10,26h 05m,2 Stop(s),New Delhi,Bangalore,15585,2021-11-3,Special
40,Vistara Premium Economy,13:20,9h 30m,2 Stop(s),New Delhi,Bangalore,20961,2021-11-3,Special
41,Vistara Premium Economy,13:20,21h 25m,2 Stop(s),New Delhi,Bangalore,20961,2021-11-3,Special
42,Vistara Premium Economy,13:20,28h 25m,2 Stop(s),New Delhi,Bangalore,20961,2021-11-3,Special
43,Vistara Premium Economy,13:20,29h 55m,2 Stop(s),New Delhi,Bangalore,20961,2021-11-3,Special
44,Vistara Premium Economy,13:40,21h 05m,2 Stop(s),New Delhi,Bangalore,24097,2021-11-3,Special
45,Vistara Premium Economy,13:40,28h 05m,2 Stop(s),New Delhi,Bangalore,24097,2021-11-3,Special
46,Vistara Premium Economy,13:40,28h 05m,2 Stop(s),New Delhi,Bangalore,24097,2021-11-3,Special
47,Vistara Premium Economy,13:40,29h 35m,2 Stop(s),New Delhi,Bangalore,24097,2021-11-3,Special
48,Vistara Premium Economy,13:40,29h 35m,2 Stop(s),New Delhi,Bangalore,24097,2021-11-3,Special

In [54]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','5','11','2021','Special')

y5 = pd.DataFrame({})
y5['airlines'] = airlines
y5['departure'] = departure
y5['duration'] = duration
y5['stops'] = stops
y5['from_city'] = 'New Delhi'
y5['to_city'] = to_city
y5['price'] = price
y5['journey_date'] = '2021-11-5'
y5['fclass'] = 'Special'
y5

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,20:40,2h 40m,Non Stop,New Delhi,Bangalore,8622,2021-11-5,Special
1,Vistara Premium Economy,19:50,2h 50m,Non Stop,New Delhi,Bangalore,9630,2021-11-5,Special
2,Vistara Premium Economy,14:15,2h 45m,Non Stop,New Delhi,Bangalore,11198,2021-11-5,Special
3,Vistara Premium Economy,12:50,4h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-5,Special
4,Vistara Premium Economy,15:30,5h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-5,Special
5,Vistara Premium Economy,11:40,6h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-5,Special
6,Vistara Premium Economy,10:20,7h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-5,Special
7,Vistara Premium Economy,12:50,8h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-5,Special
8,Vistara Premium Economy,09:30,8h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-5,Special
9,Vistara Premium Economy,08:50,8h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-5,Special
10,Vistara Premium Economy,11:40,9h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-5,Special
11,Vistara Premium Economy,07:30,10h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-5,Special
12,Vistara Premium Economy,10:20,10h 35m,1 Stop,New Delhi,Bangalore,12458,2021-11-5,Special
13,Vistara Premium Economy,09:30,11h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-5,Special
14,Vistara Premium Economy,06:00,11h 45m,1 Stop,New Delhi,Bangalore,12458,2021-11-5,Special
15,Vistara Premium Economy,08:50,12h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-5,Special
16,Vistara Premium Economy,07:30,13h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-5,Special
17,Vistara Premium Economy,06:00,14h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-5,Special
18,Vistara Premium Economy,12:50,6h 25m,1 Stop,New Delhi,Bangalore,12766,2021-11-5,Special
19,Vistara Premium Economy,11:40,7h 35m,1 Stop,New Delhi,Bangalore,12766,2021-11-5,Special
20,Vistara Premium Economy,10:20,8h 55m,1 Stop,New Delhi,Bangalore,12766,2021-11-5,Special
21,Vistara Premium Economy,09:30,9h 45m,1 Stop,New Delhi,Bangalore,12766,2021-11-5,Special
22,Vistara Premium Economy,08:50,10h 25m,1 Stop,New Delhi,Bangalore,12766,2021-11-5,Special
23,Vistara Premium Economy,07:30,11h 45m,1 Stop,New Delhi,Bangalore,12766,2021-11-5,Special
24,Vistara Premium Economy,06:00,13h 15m,1 Stop,New Delhi,Bangalore,12766,2021-11-5,Special
25,Vistara Premium Economy,08:05,2h 45m,Non Stop,New Delhi,Bangalore,13494,2021-11-5,Special
26,Vistara Premium Economy,16:05,2h 45m,Non Stop,New Delhi,Bangalore,13494,2021-11-5,Special
27,Vistara Premium Economy,17:35,2h 50m,Non Stop,New Delhi,Bangalore,13494,2021-11-5,Special
28,Vistara Premium Economy,06:00,4h 45m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
29,Vistara Premium Economy,21:40,10h 10m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
30,Vistara Premium Economy,20:40,11h 10m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
31,Vistara Premium Economy,19:50,12h 00m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
32,Vistara Premium Economy,18:55,12h 55m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
33,Vistara Premium Economy,21:40,13h 05m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
34,Vistara Premium Economy,17:45,14h 05m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
35,Vistara Premium Economy,20:40,14h 05m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
36,Vistara Premium Economy,16:55,14h 55m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
37,Vistara Premium Economy,19:50,14h 55m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
38,Vistara Premium Economy,18:55,15h 50m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
39,Vistara Premium Economy,15:30,16h 20m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
40,Vistara Premium Economy,17:45,17h 00m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
41,Vistara Premium Economy,16:55,17h 50m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
42,Vistara Premium Economy,21:40,20h 05m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
43,Vistara Premium Economy,20:40,21h 05m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
44,Vistara Premium Economy,21:40,21h 35m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
45,Vistara Premium Economy,19:50,21h 55m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
46,Vistara Premium Economy,20:40,22h 35m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
47,Vistara Premium Economy,18:55,22h 50m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
48,Vistara Premium Economy,19:50,23h 25m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
49,Vistara Premium Economy,17:45,24h 00m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
50,Vistara Premium Economy,18:55,24h 20m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
51,Vistara Premium Economy,16:55,24h 50m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
52,Vistara Premium Economy,17:45,25h 30m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
53,Vistara Premium Economy,16:55,26h 20m,1 Stop,New Delhi,Bangalore,15902,2021-11-5,Special
54,Vistara Premium Economy,13:20,7h 35m,2 Stop(s),New Delhi,Bangalore,20961,2021-11-5,Special
55,Vistara Premium Economy,17:10,25h 05m,1 Stop,New Delhi,Bangalore,24414,2021-11-5,Special

In [55]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','7','11','2021','Special')

y6 = pd.DataFrame({})
y6['airlines'] = airlines
y6['departure'] = departure
y6['duration'] = duration
y6['stops'] = stops
y6['from_city'] = 'New Delhi'
y6['to_city'] = to_city
y6['price'] = price
y6['journey_date'] = '2021-11-7'
y6['fclass'] = 'Special'
y6

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,07:30,24h 20m,1 Stop,New Delhi,Bangalore,12458,2021-11-7,Special
1,Vistara Premium Economy,20:40,2h 40m,Non Stop,New Delhi,Bangalore,13494,2021-11-7,Special
2,Vistara Premium Economy,06:15,2h 45m,Non Stop,New Delhi,Bangalore,13494,2021-11-7,Special
3,Vistara Premium Economy,19:50,2h 50m,Non Stop,New Delhi,Bangalore,13494,2021-11-7,Special
4,Vistara Premium Economy,07:30,13h 25m,1 Stop,New Delhi,Bangalore,15902,2021-11-7,Special
5,Vistara Premium Economy,07:30,15h 20m,1 Stop,New Delhi,Bangalore,15902,2021-11-7,Special
6,Vistara Premium Economy,07:30,25h 20m,1 Stop,New Delhi,Bangalore,15902,2021-11-7,Special
7,Vistara Premium Economy,07:30,27h 15m,1 Stop,New Delhi,Bangalore,15902,2021-11-7,Special
8,Vistara Premium Economy,08:05,2h 45m,Non Stop,New Delhi,Bangalore,16854,2021-11-7,Special
9,Vistara Premium Economy,16:05,2h 45m,Non Stop,New Delhi,Bangalore,17414,2021-11-7,Special
10,Vistara Premium Economy,17:35,2h 50m,Non Stop,New Delhi,Bangalore,17414,2021-11-7,Special
11,Vistara Premium Economy,19:50,12h 00m,1 Stop,New Delhi,Bangalore,17834,2021-11-7,Special
12,Vistara Premium Economy,19:50,21h 55m,1 Stop,New Delhi,Bangalore,17834,2021-11-7,Special
13,Vistara Premium Economy,09:30,22h 20m,1 Stop,New Delhi,Bangalore,17834,2021-11-7,Special
14,Vistara Premium Economy,08:50,23h 00m,1 Stop,New Delhi,Bangalore,17834,2021-11-7,Special
15,Vistara Premium Economy,19:50,23h 25m,1 Stop,New Delhi,Bangalore,17834,2021-11-7,Special
16,Vistara Premium Economy,19:50,25h 05m,1 Stop,New Delhi,Bangalore,17834,2021-11-7,Special
17,Vistara Premium Economy,19:50,27h 00m,1 Stop,New Delhi,Bangalore,17834,2021-11-7,Special
18,Vistara Premium Economy,07:30,10h 15m,1 Stop,New Delhi,Bangalore,18366,2021-11-7,Special
19,Vistara Premium Economy,07:30,11h 45m,1 Stop,New Delhi,Bangalore,18366,2021-11-7,Special
20,Vistara Premium Economy,21:40,10h 10m,1 Stop,New Delhi,Bangalore,18450,2021-11-7,Special
21,Vistara Premium Economy,21:40,20h 05m,1 Stop,New Delhi,Bangalore,18450,2021-11-7,Special
22,Vistara Premium Economy,21:40,21h 35m,1 Stop,New Delhi,Bangalore,18450,2021-11-7,Special
23,Vistara Premium Economy,21:40,23h 15m,1 Stop,New Delhi,Bangalore,18450,2021-11-7,Special
24,Vistara Premium Economy,21:40,25h 10m,1 Stop,New Delhi,Bangalore,18450,2021-11-7,Special
25,Vistara Premium Economy,17:10,25h 05m,1 Stop,New Delhi,Bangalore,20606,2021-11-7,Special
26,Vistara Premium Economy,16:55,14h 55m,1 Stop,New Delhi,Bangalore,21250,2021-11-7,Special
27,Vistara Premium Economy,16:55,24h 50m,1 Stop,New Delhi,Bangalore,21250,2021-11-7,Special
28,Vistara Premium Economy,09:30,11h 25m,1 Stop,New Delhi,Bangalore,21278,2021-11-7,Special
29,Vistara Premium Economy,08:50,12h 05m,1 Stop,New Delhi,Bangalore,21278,2021-11-7,Special
30,Vistara Premium Economy,19:50,13h 00m,1 Stop,New Delhi,Bangalore,21278,2021-11-7,Special
31,Vistara Premium Economy,09:30,13h 20m,1 Stop,New Delhi,Bangalore,21278,2021-11-7,Special
32,Vistara Premium Economy,21:40,11h 10m,1 Stop,New Delhi,Bangalore,21894,2021-11-7,Special
33,Vistara Premium Economy,21:40,13h 05m,1 Stop,New Delhi,Bangalore,21894,2021-11-7,Special
34,Vistara Premium Economy,09:30,8h 15m,1 Stop,New Delhi,Bangalore,23742,2021-11-7,Special
35,Vistara Premium Economy,08:50,8h 55m,1 Stop,New Delhi,Bangalore,23742,2021-11-7,Special
36,Vistara Premium Economy,09:30,9h 45m,1 Stop,New Delhi,Bangalore,23742,2021-11-7,Special
37,Vistara Premium Economy,08:50,10h 25m,1 Stop,New Delhi,Bangalore,23742,2021-11-7,Special
38,Vistara Premium Economy,14:15,2h 45m,Non Stop,New Delhi,Bangalore,23910,2021-11-7,Special
39,Vistara Premium Economy,16:55,5h 55m,1 Stop,New Delhi,Bangalore,24694,2021-11-7,Special
40,Vistara Premium Economy,18:55,12h 55m,1 Stop,New Delhi,Bangalore,27298,2021-11-7,Special
41,Vistara Premium Economy,17:45,5h 05m,1 Stop,New Delhi,Bangalore,30742,2021-11-7,Special
42,Vistara Premium Economy,15:30,5h 25m,1 Stop,New Delhi,Bangalore,30742,2021-11-7,Special
43,Vistara Premium Economy,15:30,7h 20m,1 Stop,New Delhi,Bangalore,30742,2021-11-7,Special
44,Vistara Premium Economy,12:50,8h 05m,1 Stop,New Delhi,Bangalore,30742,2021-11-7,Special
45,Vistara Premium Economy,11:40,9h 15m,1 Stop,New Delhi,Bangalore,30742,2021-11-7,Special
46,Vistara Premium Economy,12:50,10h 00m,1 Stop,New Delhi,Bangalore,30742,2021-11-7,Special
47,Vistara Premium Economy,10:20,10h 35m,1 Stop,New Delhi,Bangalore,30742,2021-11-7,Special
48,Vistara Premium Economy,11:40,11h 10m,1 Stop,New Delhi,Bangalore,30742,2021-11-7,Special
49,Vistara Premium Economy,10:20,12h 30m,1 Stop,New Delhi,Bangalore,30742,2021-11-7,Special
50,Vistara Premium Economy,18:55,13h 55m,1 Stop,New Delhi,Bangalore,30742,2021-11-7,Special
51,Vistara Premium Economy,12:50,4h 55m,1 Stop,New Delhi,Bangalore,33206,2021-11-7,Special
52,Vistara Premium Economy,11:40,6h 05m,1 Stop,New Delhi,Bangalore,33206,2021-11-7,Special
53,Vistara Premium Economy,12:50,6h 25m,1 Stop,New Delhi,Bangalore,33206,2021-11-7,Special
54,Vistara Premium Economy,10:20,7h 25m,1 Stop,New Delhi,Bangalore,33206,2021-11-7,Special
55,Vistara Premium Economy,11:40,7h 35m,1 Stop,New Delhi,Bangalore,33206,2021-11-7,Special
56,Vistara Premium Economy,10:20,8h 55m,1 Stop,New Delhi,Bangalore,33206,2021-11-7,Special

In [56]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','9','11','2021','Special')

y7 = pd.DataFrame({})
y7['airlines'] = airlines
y7['departure'] = departure
y7['duration'] = duration
y7['stops'] = stops
y7['from_city'] = 'New Delhi'
y7['to_city'] = to_city
y7['price'] = price
y7['journey_date'] = '2021-11-9'
y7['fclass'] = 'Special'
y7

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,20:40,2h 40m,Non Stop,New Delhi,Bangalore,8622,2021-11-9,Special
1,Vistara Premium Economy,06:15,2h 45m,Non Stop,New Delhi,Bangalore,8622,2021-11-9,Special
2,Vistara Premium Economy,14:15,2h 45m,Non Stop,New Delhi,Bangalore,8622,2021-11-9,Special
3,Vistara Premium Economy,17:35,2h 50m,Non Stop,New Delhi,Bangalore,8622,2021-11-9,Special
4,Vistara Premium Economy,19:50,2h 50m,Non Stop,New Delhi,Bangalore,8622,2021-11-9,Special
5,Vistara Premium Economy,16:05,2h 45m,Non Stop,New Delhi,Bangalore,9630,2021-11-9,Special
6,Vistara Premium Economy,10:20,7h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-9,Special
7,Vistara Premium Economy,08:50,8h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-9,Special
8,Vistara Premium Economy,10:20,8h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-9,Special
9,Vistara Premium Economy,08:50,10h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-9,Special
10,Vistara Premium Economy,10:20,10h 35m,1 Stop,New Delhi,Bangalore,12458,2021-11-9,Special
11,Vistara Premium Economy,08:50,12h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-9,Special
12,Vistara Premium Economy,10:20,12h 30m,1 Stop,New Delhi,Bangalore,12458,2021-11-9,Special
13,Vistara Premium Economy,08:50,14h 00m,1 Stop,New Delhi,Bangalore,12458,2021-11-9,Special
14,Vistara Premium Economy,17:45,5h 05m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
15,Vistara Premium Economy,15:30,5h 25m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
16,Vistara Premium Economy,15:30,7h 20m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
17,Vistara Premium Economy,21:40,10h 10m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
18,Vistara Premium Economy,07:30,10h 15m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
19,Vistara Premium Economy,20:40,11h 10m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
20,Vistara Premium Economy,21:40,11h 10m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
21,Vistara Premium Economy,06:00,11h 45m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
22,Vistara Premium Economy,07:30,11h 45m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
23,Vistara Premium Economy,19:50,12h 00m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
24,Vistara Premium Economy,20:40,12h 10m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
25,Vistara Premium Economy,18:55,12h 55m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
26,Vistara Premium Economy,19:50,13h 00m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
27,Vistara Premium Economy,21:40,13h 05m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
28,Vistara Premium Economy,06:00,13h 15m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
29,Vistara Premium Economy,07:30,13h 25m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
30,Vistara Premium Economy,18:55,13h 55m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
31,Vistara Premium Economy,17:45,14h 05m,1 Stop,New Delhi,Bangalore,12794,2021-11-9,Special
32,Vistara Premium Economy,06:00,4h 45m,1 Stop,New Delhi,Bangalore,13102,2021-11-9,Special
33,Vistara Premium Economy,08:05,2h 45m,Non Stop,New Delhi,Bangalore,13494,2021-11-9,Special
34,Vistara Premium Economy,17:10,25h 05m,1 Stop,New Delhi,Bangalore,14782,2021-11-9,Special
35,Vistara Premium Economy,13:20,7h 35m,2 Stop(s),New Delhi,Bangalore,17377,2021-11-9,Special
36,Vistara Premium Economy,13:20,9h 30m,2 Stop(s),New Delhi,Bangalore,17377,2021-11-9,Special
37,Vistara Premium Economy,13:20,18h 30m,2 Stop(s),New Delhi,Bangalore,17377,2021-11-9,Special
38,Vistara Premium Economy,13:20,19h 30m,2 Stop(s),New Delhi,Bangalore,17377,2021-11-9,Special
39,Vistara Premium Economy,13:20,21h 25m,2 Stop(s),New Delhi,Bangalore,17377,2021-11-9,Special
40,Vistara Premium Economy,13:20,28h 25m,2 Stop(s),New Delhi,Bangalore,17377,2021-11-9,Special
41,Vistara Premium Economy,12:50,4h 55m,1 Stop,New Delhi,Bangalore,17834,2021-11-9,Special
42,Vistara Premium Economy,16:55,5h 55m,1 Stop,New Delhi,Bangalore,17834,2021-11-9,Special
43,Vistara Premium Economy,11:40,6h 05m,1 Stop,New Delhi,Bangalore,17834,2021-11-9,Special
44,Vistara Premium Economy,12:50,6h 25m,1 Stop,New Delhi,Bangalore,17834,2021-11-9,Special
45,Vistara Premium Economy,11:40,7h 35m,1 Stop,New Delhi,Bangalore,17834,2021-11-9,Special
46,Vistara Premium Economy,12:50,8h 05m,1 Stop,New Delhi,Bangalore,17834,2021-11-9,Special
47,Vistara Premium Economy,09:30,8h 15m,1 Stop,New Delhi,Bangalore,17834,2021-11-9,Special
48,Vistara Premium Economy,11:40,9h 15m,1 Stop,New Delhi,Bangalore,17834,2021-11-9,Special
49,Vistara Premium Economy,09:30,9h 45m,1 Stop,New Delhi,Bangalore,17834,2021-11-9,Special
50,Vistara Premium Economy,12:50,10h 00m,1 Stop,New Delhi,Bangalore,17834,2021-11-9,Special
51,Vistara Premium Economy,11:40,11h 10m,1 Stop,New Delhi,Bangalore,17834,2021-11-9,Special
52,Vistara Premium Economy,09:30,11h 25m,1 Stop,New Delhi,Bangalore,17834,2021-11-9,Special
53,Vistara Premium Economy,09:30,13h 20m,1 Stop,New Delhi,Bangalore,17834,2021-11-9,Special

In [57]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','11','11','2021','Special')

y8 = pd.DataFrame({})
y8['airlines'] = airlines
y8['departure'] = departure
y8['duration'] = duration
y8['stops'] = stops
y8['from_city'] = 'New Delhi'
y8['to_city'] = to_city
y8['price'] = price
y8['journey_date'] = '2021-11-11'
y8['fclass'] = 'Special'
y8

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,20:40,2h 40m,Non Stop,New Delhi,Bangalore,8622,2021-11-11,Special
1,Vistara Premium Economy,06:15,2h 45m,Non Stop,New Delhi,Bangalore,8622,2021-11-11,Special
2,Vistara Premium Economy,08:05,2h 45m,Non Stop,New Delhi,Bangalore,8622,2021-11-11,Special
3,Vistara Premium Economy,14:15,2h 45m,Non Stop,New Delhi,Bangalore,8622,2021-11-11,Special
4,Vistara Premium Economy,16:05,2h 45m,Non Stop,New Delhi,Bangalore,8622,2021-11-11,Special
5,Vistara Premium Economy,17:35,2h 50m,Non Stop,New Delhi,Bangalore,8622,2021-11-11,Special
6,Vistara Premium Economy,19:50,2h 50m,Non Stop,New Delhi,Bangalore,8622,2021-11-11,Special
7,Vistara Premium Economy,06:00,4h 45m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
8,Vistara Premium Economy,12:50,4h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
9,Vistara Premium Economy,15:30,5h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
10,Vistara Premium Economy,16:55,5h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
11,Vistara Premium Economy,11:40,6h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
12,Vistara Premium Economy,12:50,6h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
13,Vistara Premium Economy,15:30,7h 20m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
14,Vistara Premium Economy,10:20,7h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
15,Vistara Premium Economy,11:40,7h 35m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
16,Vistara Premium Economy,12:50,8h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
17,Vistara Premium Economy,09:30,8h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
18,Vistara Premium Economy,08:50,8h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
19,Vistara Premium Economy,10:20,8h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
20,Vistara Premium Economy,11:40,9h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
21,Vistara Premium Economy,09:30,9h 45m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
22,Vistara Premium Economy,12:50,10h 00m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
23,Vistara Premium Economy,21:40,10h 10m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
24,Vistara Premium Economy,07:30,10h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
25,Vistara Premium Economy,08:50,10h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
26,Vistara Premium Economy,10:20,10h 35m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
27,Vistara Premium Economy,11:40,11h 10m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
28,Vistara Premium Economy,20:40,11h 10m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
29,Vistara Premium Economy,21:40,11h 10m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
30,Vistara Premium Economy,09:30,11h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
31,Vistara Premium Economy,06:00,11h 45m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
32,Vistara Premium Economy,07:30,11h 45m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
33,Vistara Premium Economy,19:50,12h 00m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
34,Vistara Premium Economy,08:50,12h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
35,Vistara Premium Economy,20:40,12h 10m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
36,Vistara Premium Economy,10:20,12h 30m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
37,Vistara Premium Economy,18:55,12h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
38,Vistara Premium Economy,19:50,13h 00m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
39,Vistara Premium Economy,21:40,13h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
40,Vistara Premium Economy,06:00,13h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
41,Vistara Premium Economy,09:30,13h 20m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
42,Vistara Premium Economy,07:30,13h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
43,Vistara Premium Economy,18:55,13h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
44,Vistara Premium Economy,08:50,14h 00m,1 Stop,New Delhi,Bangalore,12458,2021-11-11,Special
45,Vistara Premium Economy,17:45,5h 05m,1 Stop,New Delhi,Bangalore,12794,2021-11-11,Special
46,Vistara Premium Economy,17:45,14h 05m,1 Stop,New Delhi,Bangalore,12794,2021-11-11,Special
47,Vistara Premium Economy,17:10,25h 05m,1 Stop,New Delhi,Bangalore,14782,2021-11-11,Special
48,Vistara Premium Economy,13:20,7h 35m,2 Stop(s),New Delhi,Bangalore,17377,2021-11-11,Special
49,Vistara Premium Economy,13:20,9h 30m,2 Stop(s),New Delhi,Bangalore,17377,2021-11-11,Special
50,Vistara Premium Economy,13:20,18h 30m,2 Stop(s),New Delhi,Bangalore,17377,2021-11-11,Special
51,Vistara Premium Economy,13:20,19h 30m,2 Stop(s),New Delhi,Bangalore,17377,2021-11-11,Special
52,Vistara Premium Economy,13:20,21h 25m,2 Stop(s),New Delhi,Bangalore,17377,2021-11-11,Special
53,Vistara Premium Economy,13:20,28h 25m,2 Stop(s),New Delhi,Bangalore,17377,2021-11-11,Special

In [58]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','13','11','2021','Special')

y9 = pd.DataFrame({})
y9['airlines'] = airlines
y9['departure'] = departure
y9['duration'] = duration
y9['stops'] = stops
y9['from_city'] = 'New Delhi'
y9['to_city'] = to_city
y9['price'] = price
y9['journey_date'] = '2021-11-13'
y9['fclass'] = 'Special'
y9

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,06:15,2h 45m,Non Stop,New Delhi,Bangalore,8622,2021-11-13,Special
1,Vistara Premium Economy,20:40,2h 40m,Non Stop,New Delhi,Bangalore,9630,2021-11-13,Special
2,Vistara Premium Economy,16:05,2h 45m,Non Stop,New Delhi,Bangalore,9630,2021-11-13,Special
3,Vistara Premium Economy,19:50,2h 50m,Non Stop,New Delhi,Bangalore,9630,2021-11-13,Special
4,Vistara Premium Economy,08:05,2h 45m,Non Stop,New Delhi,Bangalore,11198,2021-11-13,Special
5,Vistara Premium Economy,12:50,4h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
6,Vistara Premium Economy,11:40,6h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
7,Vistara Premium Economy,12:50,6h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
8,Vistara Premium Economy,10:20,7h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
9,Vistara Premium Economy,11:40,7h 35m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
10,Vistara Premium Economy,12:50,8h 05m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
11,Vistara Premium Economy,09:30,8h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
12,Vistara Premium Economy,10:20,8h 55m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
13,Vistara Premium Economy,11:40,9h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
14,Vistara Premium Economy,09:30,9h 45m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
15,Vistara Premium Economy,12:50,10h 00m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
16,Vistara Premium Economy,07:30,10h 15m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
17,Vistara Premium Economy,10:20,10h 35m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
18,Vistara Premium Economy,11:40,11h 10m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
19,Vistara Premium Economy,09:30,11h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
20,Vistara Premium Economy,07:30,11h 45m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
21,Vistara Premium Economy,10:20,12h 30m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
22,Vistara Premium Economy,09:30,13h 20m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
23,Vistara Premium Economy,07:30,13h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
24,Vistara Premium Economy,07:30,15h 20m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
25,Vistara Premium Economy,21:40,21h 35m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
26,Vistara Premium Economy,20:40,22h 35m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
27,Vistara Premium Economy,19:50,23h 25m,1 Stop,New Delhi,Bangalore,12458,2021-11-13,Special
28,Vistara Premium Economy,21:40,13h 05m,1 Stop,New Delhi,Bangalore,12766,2021-11-13,Special
29,Vistara Premium Economy,20:40,14h 05m,1 Stop,New Delhi,Bangalore,12766,2021-11-13,Special
30,Vistara Premium Economy,19:50,14h 55m,1 Stop,New Delhi,Bangalore,12766,2021-11-13,Special
31,Vistara Premium Economy,21:40,20h 05m,1 Stop,New Delhi,Bangalore,12766,2021-11-13,Special
32,Vistara Premium Economy,20:40,21h 05m,1 Stop,New Delhi,Bangalore,12766,2021-11-13,Special
33,Vistara Premium Economy,19:50,21h 55m,1 Stop,New Delhi,Bangalore,12766,2021-11-13,Special
34,Vistara Premium Economy,06:00,4h 45m,1 Stop,New Delhi,Bangalore,12794,2021-11-13,Special
35,Vistara Premium Economy,08:50,8h 55m,1 Stop,New Delhi,Bangalore,12794,2021-11-13,Special
36,Vistara Premium Economy,08:50,10h 25m,1 Stop,New Delhi,Bangalore,12794,2021-11-13,Special
37,Vistara Premium Economy,06:00,11h 45m,1 Stop,New Delhi,Bangalore,12794,2021-11-13,Special
38,Vistara Premium Economy,08:50,12h 05m,1 Stop,New Delhi,Bangalore,12794,2021-11-13,Special
39,Vistara Premium Economy,06:00,13h 15m,1 Stop,New Delhi,Bangalore,12794,2021-11-13,Special
40,Vistara Premium Economy,08:50,14h 00m,1 Stop,New Delhi,Bangalore,12794,2021-11-13,Special
41,Vistara Premium Economy,06:00,14h 55m,1 Stop,New Delhi,Bangalore,12794,2021-11-13,Special
42,Vistara Premium Economy,14:15,2h 45m,Non Stop,New Delhi,Bangalore,13494,2021-11-13,Special
43,Vistara Premium Economy,17:35,2h 50m,Non Stop,New Delhi,Bangalore,13494,2021-11-13,Special
44,Vistara Premium Economy,13:20,7h 35m,2 Stop(s),New Delhi,Bangalore,17657,2021-11-13,Special
45,Vistara Premium Economy,13:20,9h 30m,2 Stop(s),New Delhi,Bangalore,17657,2021-11-13,Special
46,Vistara Premium Economy,17:45,5h 05m,1 Stop,New Delhi,Bangalore,17834,2021-11-13,Special
47,Vistara Premium Economy,15:30,5h 25m,1 Stop,New Delhi,Bangalore,17834,2021-11-13,Special
48,Vistara Premium Economy,16:55,5h 55m,1 Stop,New Delhi,Bangalore,17834,2021-11-13,Special
49,Vistara Premium Economy,15:30,7h 20m,1 Stop,New Delhi,Bangalore,17834,2021-11-13,Special
50,Vistara Premium Economy,18:55,24h 20m,1 Stop,New Delhi,Bangalore,17834,2021-11-13,Special
51,Vistara Premium Economy,18:55,15h 50m,1 Stop,New Delhi,Bangalore,18142,2021-11-13,Special
52,Vistara Premium Economy,17:45,17h 00m,1 Stop,New Delhi,Bangalore,18142,2021-11-13,Special
53,Vistara Premium Economy,16:55,17h 50m,1 Stop,New Delhi,Bangalore,18142,2021-11-13,Special
54,Vistara Premium Economy,18:55,22h 50m,1 Stop,New Delhi,Bangalore,18142,2021-11-13,Special
55,Vistara Premium Economy,17:10,25h 05m,1 Stop,New Delhi,Bangalore,20606,2021-11-13,Special

In [59]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','28','10','2021','Business')

z1 = pd.DataFrame({})
z1['airlines'] = airlines
z1['departure'] = departure
z1['duration'] = duration
z1['stops'] = stops
z1['from_city'] = 'New Delhi'
z1['to_city'] = to_city
z1['price'] = price
z1['journey_date'] = '2021-10-28'
z1['fclass'] = 'Business'
z1

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Business,20:40,2h 40m,Non Stop,New Delhi,Bangalore,25736,2021-10-28,Business
1,Air India Business,21:25,13h 55m,1 Stop,New Delhi,Bangalore,31546,2021-10-28,Business
2,Air India Business,22:00,2h 40m,Non Stop,New Delhi,Bangalore,31720,2021-10-28,Business
3,Air India Business,21:00,14h 20m,2 Stop(s),New Delhi,Bangalore,36754,2021-10-28,Business
4,Air India Business,20:15,21h 20m,1 Stop,New Delhi,Bangalore,44546,2021-10-28,Business
5,Vistara Business,20:30,21h 15m,2 Stop(s),New Delhi,Bangalore,75531,2021-10-28,Business
6,Vistara Business,20:30,24h 25m,2 Stop(s),New Delhi,Bangalore,75531,2021-10-28,Business
7,Vistara Business,20:30,26h 20m,2 Stop(s),New Delhi,Bangalore,75531,2021-10-28,Business

In [60]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','31','10','2021','Business')

z2 = pd.DataFrame({})
z2['airlines'] = airlines
z2['departure'] = departure
z2['duration'] = duration
z2['stops'] = stops
z2['from_city'] = 'New Delhi'
z2['to_city'] = to_city
z2['price'] = price
z2['journey_date'] = '2021-10-31'
z2['fclass'] = 'Business'
z2

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air India Business,21:15,2h 40m,Non Stop,New Delhi,Bangalore,25000,2021-10-31,Business
1,Air India Business,06:10,2h 45m,Non Stop,New Delhi,Bangalore,25000,2021-10-31,Business
2,Air India Business,09:45,2h 45m,Non Stop,New Delhi,Bangalore,25000,2021-10-31,Business
3,Air India Business,13:30,2h 45m,Non Stop,New Delhi,Bangalore,25000,2021-10-31,Business
4,Air India Business,17:20,2h 45m,Non Stop,New Delhi,Bangalore,25000,2021-10-31,Business
...,...,...,...,...,...,...,...,...,...
75,Vistara Business,12:50,8h 05m,1 Stop,New Delhi,Bangalore,48057,2021-10-31,Business
76,Vistara Business,12:50,10h 00m,1 Stop,New Delhi,Bangalore,48057,2021-10-31,Business
77,Vistara Business,17:10,25h 05m,1 Stop,New Delhi,Bangalore,48841,2021-10-31,Business
78,Air India Business,09:25,13h 55m,2 Stop(s),New Delhi,Bangalore,49845,2021-10-31,Business
79,Air India Business,15:05,16h 50m,2 Stop(s),New Delhi,Bangalore,65966,2021-10-31,Business

In [61]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','3','11','2021','Business')

z3 = pd.DataFrame({})
z3['airlines'] = airlines
z3['departure'] = departure
z3['duration'] = duration
z3['stops'] = stops
z3['from_city'] = 'New Delhi'
z3['to_city'] = to_city
z3['price'] = price
z3['journey_date'] = '2021-11-3'
z3['fclass'] = 'Business'
z3

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air India Business,21:15,2h 40m,Non Stop,New Delhi,Bangalore,33464,2021-11-3,Business
1,Air India Business,06:10,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-3,Business
2,Air India Business,09:45,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-3,Business
3,Air India Business,13:30,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-3,Business
4,Air India Business,17:20,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-3,Business
...,...,...,...,...,...,...,...,...,...
65,Vistara Business,10:20,7h 25m,1 Stop,New Delhi,Bangalore,74041,2021-11-3,Business
66,Vistara Business,06:00,11h 45m,1 Stop,New Delhi,Bangalore,74041,2021-11-3,Business
67,Vistara Business,19:50,14h 55m,1 Stop,New Delhi,Bangalore,75385,2021-11-3,Business
68,Vistara Business,08:50,8h 55m,1 Stop,New Delhi,Bangalore,76281,2021-11-3,Business
69,Vistara Business,07:30,10h 15m,1 Stop,New Delhi,Bangalore,76281,2021-11-3,Business

In [62]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','6','11','2021','Business')

z4 = pd.DataFrame({})
z4['airlines'] = airlines
z4['departure'] = departure
z4['duration'] = duration
z4['stops'] = stops
z4['from_city'] = 'New Delhi'
z4['to_city'] = to_city
z4['price'] = price
z4['journey_date'] = '2021-11-6'
z4['fclass'] = 'Business'
z4

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air India Business,21:15,2h 40m,Non Stop,New Delhi,Bangalore,33464,2021-11-6,Business
1,Air India Business,06:10,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-6,Business
2,Air India Business,09:45,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-6,Business
3,Air India Business,13:30,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-6,Business
4,Air India Business,17:20,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-6,Business
5,Vistara Business,20:40,2h 40m,Non Stop,New Delhi,Bangalore,39176,2021-11-6,Business
6,Vistara Business,06:15,2h 45m,Non Stop,New Delhi,Bangalore,39176,2021-11-6,Business
7,Vistara Business,08:05,2h 45m,Non Stop,New Delhi,Bangalore,39176,2021-11-6,Business
8,Vistara Business,14:15,2h 45m,Non Stop,New Delhi,Bangalore,39176,2021-11-6,Business
9,Vistara Business,17:35,2h 50m,Non Stop,New Delhi,Bangalore,39176,2021-11-6,Business
10,Vistara Business,19:50,2h 50m,Non Stop,New Delhi,Bangalore,39176,2021-11-6,Business
11,Air India Business,11:55,24h 55m,1 Stop,New Delhi,Bangalore,42291,2021-11-6,Business
12,Vistara Business,20:40,11h 10m,1 Stop,New Delhi,Bangalore,42457,2021-11-6,Business
13,Vistara Business,20:40,12h 10m,1 Stop,New Delhi,Bangalore,42457,2021-11-6,Business
14,Air India Business,20:00,22h 30m,1 Stop,New Delhi,Bangalore,46041,2021-11-6,Business
15,Air India Business,17:50,24h 40m,1 Stop,New Delhi,Bangalore,46041,2021-11-6,Business
16,Air India Business,15:05,27h 25m,2 Stop(s),New Delhi,Bangalore,46041,2021-11-6,Business
17,Air India Business,09:45,4h 40m,1 Stop,New Delhi,Bangalore,46255,2021-11-6,Business
18,Air India Business,06:05,8h 20m,1 Stop,New Delhi,Bangalore,46255,2021-11-6,Business
19,Air India Business,18:40,22h 25m,1 Stop,New Delhi,Bangalore,49089,2021-11-6,Business
20,Vistara Business,11:40,6h 05m,1 Stop,New Delhi,Bangalore,49177,2021-11-6,Business
21,Vistara Business,11:40,7h 35m,1 Stop,New Delhi,Bangalore,49177,2021-11-6,Business
22,Vistara Business,09:30,8h 15m,1 Stop,New Delhi,Bangalore,49177,2021-11-6,Business
23,Vistara Business,11:40,9h 15m,1 Stop,New Delhi,Bangalore,49177,2021-11-6,Business
24,Vistara Business,09:30,9h 45m,1 Stop,New Delhi,Bangalore,49177,2021-11-6,Business
25,Vistara Business,11:40,11h 10m,1 Stop,New Delhi,Bangalore,49177,2021-11-6,Business
26,Vistara Business,09:30,11h 25m,1 Stop,New Delhi,Bangalore,49177,2021-11-6,Business
27,Vistara Business,09:30,13h 20m,1 Stop,New Delhi,Bangalore,49177,2021-11-6,Business
28,Air India Business,16:55,6h 25m,1 Stop,New Delhi,Bangalore,53310,2021-11-6,Business
29,Air India Business,12:10,11h 10m,1 Stop,New Delhi,Bangalore,53310,2021-11-6,Business
30,Air India Business,06:50,16h 30m,1 Stop,New Delhi,Bangalore,53310,2021-11-6,Business
31,Air India Business,20:15,27h 05m,1 Stop,New Delhi,Bangalore,53310,2021-11-6,Business
32,Vistara Business,20:40,14h 05m,1 Stop,New Delhi,Bangalore,53881,2021-11-6,Business
33,Vistara Business,12:50,4h 55m,1 Stop,New Delhi,Bangalore,54777,2021-11-6,Business
34,Vistara Business,15:30,5h 25m,1 Stop,New Delhi,Bangalore,54777,2021-11-6,Business
35,Vistara Business,12:50,6h 25m,1 Stop,New Delhi,Bangalore,54777,2021-11-6,Business
36,Vistara Business,15:30,7h 20m,1 Stop,New Delhi,Bangalore,54777,2021-11-6,Business
37,Vistara Business,10:20,7h 25m,1 Stop,New Delhi,Bangalore,54777,2021-11-6,Business
38,Vistara Business,12:50,8h 05m,1 Stop,New Delhi,Bangalore,54777,2021-11-6,Business
39,Vistara Business,10:20,8h 55m,1 Stop,New Delhi,Bangalore,54777,2021-11-6,Business
40,Vistara Business,12:50,10h 00m,1 Stop,New Delhi,Bangalore,54777,2021-11-6,Business
41,Vistara Business,21:40,10h 10m,1 Stop,New Delhi,Bangalore,54777,2021-11-6,Business
42,Vistara Business,10:20,10h 35m,1 Stop,New Delhi,Bangalore,54777,2021-11-6,Business
43,Vistara Business,21:40,11h 10m,1 Stop,New Delhi,Bangalore,54777,2021-11-6,Business
44,Vistara Business,10:20,12h 30m,1 Stop,New Delhi,Bangalore,54777,2021-11-6,Business
45,Vistara Business,15:30,16h 20m,1 Stop,New Delhi,Bangalore,54777,2021-11-6,Business
46,Vistara Business,17:10,25h 05m,1 Stop,New Delhi,Bangalore,55001,2021-11-6,Business
47,Vistara Business,17:45,5h 05m,1 Stop,New Delhi,Bangalore,57017,2021-11-6,Business
48,Vistara Business,08:50,8h 55m,1 Stop,New Delhi,Bangalore,57017,2021-11-6,Business
49,Vistara Business,07:30,10h 15m,1 Stop,New Delhi,Bangalore,57017,2021-11-6,Business
50,Vistara Business,08:50,10h 25m,1 Stop,New Delhi,Bangalore,57017,2021-11-6,Business
51,Vistara Business,07:30,11h 45m,1 Stop,New Delhi,Bangalore,57017,2021-11-6,Business
52,Vistara Business,08:50,12h 05m,1 Stop,New Delhi,Bangalore,57017,2021-11-6,Business
53,Vistara Business,18:55,12h 55m,1 Stop,New Delhi,Bangalore,57017,2021-11-6,Business
54,Vistara Business,07:30,13h 25m,1 Stop,New Delhi,Bangalore,57017,2021-11-6,Business

In [63]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','9','11','2021','Business')

z5 = pd.DataFrame({})
z5['airlines'] = airlines
z5['departure'] = departure
z5['duration'] = duration
z5['stops'] = stops
z5['from_city'] = 'New Delhi'
z5['to_city'] = to_city
z5['price'] = price
z5['journey_date'] = '2021-11-9'
z5['fclass'] = 'Business'
z5

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air India Business,09:30,2h 35m,Non Stop,New Delhi,Bangalore,33464,2021-11-9,Business
1,Air India Business,21:15,2h 40m,Non Stop,New Delhi,Bangalore,33464,2021-11-9,Business
2,Air India Business,06:10,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-9,Business
3,Air India Business,17:20,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-9,Business
4,Vistara Business,20:40,2h 40m,Non Stop,New Delhi,Bangalore,33979,2021-11-9,Business
5,Vistara Business,14:15,2h 45m,Non Stop,New Delhi,Bangalore,33979,2021-11-9,Business
6,Vistara Business,16:05,2h 45m,Non Stop,New Delhi,Bangalore,33979,2021-11-9,Business
7,Vistara Business,17:35,2h 50m,Non Stop,New Delhi,Bangalore,33979,2021-11-9,Business
8,Vistara Business,19:50,2h 50m,Non Stop,New Delhi,Bangalore,33979,2021-11-9,Business
9,Air India Business,07:05,14h 40m,1 Stop,New Delhi,Bangalore,43926,2021-11-9,Business
10,Air India Business,10:40,7h 50m,1 Stop,New Delhi,Bangalore,46041,2021-11-9,Business
11,Air India Business,08:00,10h 30m,1 Stop,New Delhi,Bangalore,46041,2021-11-9,Business
12,Air India Business,07:00,11h 30m,1 Stop,New Delhi,Bangalore,46041,2021-11-9,Business
13,Air India Business,20:00,15h 10m,1 Stop,New Delhi,Bangalore,46041,2021-11-9,Business
14,Air India Business,19:00,16h 10m,1 Stop,New Delhi,Bangalore,46041,2021-11-9,Business
15,Air India Business,17:50,17h 20m,1 Stop,New Delhi,Bangalore,46041,2021-11-9,Business
16,Air India Business,17:50,17h 20m,2 Stop(s),New Delhi,Bangalore,46041,2021-11-9,Business
17,Air India Business,15:05,20h 05m,2 Stop(s),New Delhi,Bangalore,46041,2021-11-9,Business
18,Air India Business,20:00,22h 30m,1 Stop,New Delhi,Bangalore,46041,2021-11-9,Business
19,Air India Business,19:00,23h 30m,1 Stop,New Delhi,Bangalore,46041,2021-11-9,Business
20,Air India Business,17:50,24h 40m,1 Stop,New Delhi,Bangalore,46041,2021-11-9,Business
21,Air India Business,17:50,24h 40m,2 Stop(s),New Delhi,Bangalore,46041,2021-11-9,Business
22,Air India Business,09:45,5h 35m,1 Stop,New Delhi,Bangalore,46255,2021-11-9,Business
23,Vistara Business,06:15,2h 45m,Non Stop,New Delhi,Bangalore,48511,2021-11-9,Business
24,Vistara Business,08:05,2h 45m,Non Stop,New Delhi,Bangalore,48511,2021-11-9,Business

In [64]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','12','11','2021','Business')

z6 = pd.DataFrame({})
z6['airlines'] = airlines
z6['departure'] = departure
z6['duration'] = duration
z6['stops'] = stops
z6['from_city'] = 'New Delhi'
z6['to_city'] = to_city
z6['price'] = price
z6['journey_date'] = '2021-11-12'
z6['fclass'] = 'Business'
z6

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air India Business,21:15,2h 40m,Non Stop,New Delhi,Bangalore,33464,2021-11-12,Business
1,Air India Business,06:10,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-12,Business
2,Air India Business,09:45,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-12,Business
3,Air India Business,13:30,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-12,Business
4,Air India Business,17:20,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-12,Business
...,...,...,...,...,...,...,...,...,...
73,Vistara Business,06:00,14h 55m,1 Stop,New Delhi,Bangalore,69561,2021-11-12,Business
74,Vistara Business,07:30,10h 15m,1 Stop,New Delhi,Bangalore,72921,2021-11-12,Business
75,Vistara Business,07:30,11h 45m,1 Stop,New Delhi,Bangalore,72921,2021-11-12,Business
76,Vistara Business,07:30,13h 25m,1 Stop,New Delhi,Bangalore,72921,2021-11-12,Business
77,Vistara Business,07:30,15h 20m,1 Stop,New Delhi,Bangalore,72921,2021-11-12,Business

In [65]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','BLR','15','11','2021','Business')

z7 = pd.DataFrame({})
z7['airlines'] = airlines
z7['departure'] = departure
z7['duration'] = duration
z7['stops'] = stops
z7['from_city'] = 'New Delhi'
z7['to_city'] = to_city
z7['price'] = price
z7['journey_date'] = '2021-11-15'
z7['fclass'] = 'Business'
z7

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air India Business,21:15,2h 40m,Non Stop,New Delhi,Bangalore,33464,2021-11-15,Business
1,Air India Business,06:10,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-15,Business
2,Air India Business,09:45,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-15,Business
3,Air India Business,13:30,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-15,Business
4,Air India Business,17:20,2h 45m,Non Stop,New Delhi,Bangalore,33464,2021-11-15,Business
5,Vistara Business,20:40,2h 40m,Non Stop,New Delhi,Bangalore,33979,2021-11-15,Business
6,Vistara Business,06:15,2h 45m,Non Stop,New Delhi,Bangalore,33979,2021-11-15,Business
7,Vistara Business,14:15,2h 45m,Non Stop,New Delhi,Bangalore,33979,2021-11-15,Business
8,Vistara Business,19:50,2h 50m,Non Stop,New Delhi,Bangalore,33979,2021-11-15,Business
9,Vistara Business,08:05,2h 45m,Non Stop,New Delhi,Bangalore,39176,2021-11-15,Business
10,Vistara Business,17:35,2h 50m,Non Stop,New Delhi,Bangalore,39176,2021-11-15,Business
11,Air India Business,18:30,27h 15m,1 Stop,New Delhi,Bangalore,43926,2021-11-15,Business
12,Air India Business,10:40,7h 50m,1 Stop,New Delhi,Bangalore,46041,2021-11-15,Business
13,Air India Business,09:00,9h 30m,1 Stop,New Delhi,Bangalore,46041,2021-11-15,Business
14,Air India Business,08:00,10h 30m,1 Stop,New Delhi,Bangalore,46041,2021-11-15,Business
15,Air India Business,07:00,11h 30m,1 Stop,New Delhi,Bangalore,46041,2021-11-15,Business
16,Air India Business,20:00,15h 10m,1 Stop,New Delhi,Bangalore,46041,2021-11-15,Business
17,Air India Business,17:50,17h 20m,1 Stop,New Delhi,Bangalore,46041,2021-11-15,Business
18,Air India Business,17:50,17h 20m,2 Stop(s),New Delhi,Bangalore,46041,2021-11-15,Business
19,Air India Business,15:05,20h 05m,2 Stop(s),New Delhi,Bangalore,46041,2021-11-15,Business
20,Air India Business,20:00,22h 30m,1 Stop,New Delhi,Bangalore,46041,2021-11-15,Business
21,Air India Business,17:50,24h 40m,1 Stop,New Delhi,Bangalore,46041,2021-11-15,Business
22,Air India Business,17:50,24h 40m,2 Stop(s),New Delhi,Bangalore,46041,2021-11-15,Business
23,Air India Business,20:40,18h 40m,1 Stop,New Delhi,Bangalore,46255,2021-11-15,Business
24,Vistara Business,11:40,6h 05m,1 Stop,New Delhi,Bangalore,49177,2021-11-15,Business

In [66]:
del_blr = pd.concat([x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,y1,y2,y3,y4,y5,y6,y7,y8,y9,z1,z2,z3,z4,z5,z6,z7], axis = 0)
del_blr.shape
del_blr.to_excel('delhiblr.xlsx')

In [67]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','28','10','2021','Economy')
get_yatra('DEL','CCU','28','10','2021','Economy')
get_yatra('DEL','HYD','28','10','2021','Economy')
get_yatra('DEL','AMD','28','10','2021','Economy')
get_yatra('DEL','GOI','28','10','2021','Economy')

x1 = pd.DataFrame({})
x1['airlines'] = airlines
x1['departure'] = departure
x1['duration'] = duration
x1['stops'] = stops
x1['from_city'] = 'New Delhi'
x1['to_city'] = to_city
x1['price'] = price
x1['journey_date'] = '2021-10-28'
x1['fclass'] = 'Economy'
x1

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,IndiGo,22:30,2h 40m,Non Stop,New Delhi,Chennai,7425,2021-10-28,Economy
1,IndiGo,20:45,2h 50m,Non Stop,New Delhi,Chennai,7425,2021-10-28,Economy
2,Air India,21:00,2h 55m,Non Stop,New Delhi,Chennai,7425,2021-10-28,Economy
3,SpiceJet,22:40,8h 25m,1 Stop,New Delhi,Chennai,7425,2021-10-28,Economy
4,SpiceJet,21:50,9h 15m,1 Stop,New Delhi,Chennai,7425,2021-10-28,Economy
...,...,...,...,...,...,...,...,...,...
62,Vistara,20:40,16h 05m,2 Stop(s),New Delhi,Goa,16468,2021-10-28,Economy
63,Vistara,20:40,17h 10m,1 Stop,New Delhi,Goa,17033,2021-10-28,Economy
64,Vistara,20:35,17h 15m,2 Stop(s),New Delhi,Goa,19448,2021-10-28,Economy
65,Vistara,21:40,16h 10m,2 Stop(s),New Delhi,Goa,21653,2021-10-28,Economy
66,Vistara,21:40,16h 10m,2 Stop(s),New Delhi,Goa,21653,2021-10-28,Economy

In [72]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','30','10','2021','Economy')
time.sleep(5)
get_yatra('DEL','CCU','30','10','2021','Economy')
time.sleep(5)
get_yatra('DEL','HYD','30','10','2021','Economy')
time.sleep(5)
get_yatra('DEL','AMD','30','10','2021','Economy')
time.sleep(5)
get_yatra('DEL','GOI','30','10','2021','Economy')

x2 = pd.DataFrame({})
x2['airlines'] = airlines
x2['departure'] = departure
x2['duration'] = duration
x2['stops'] = stops
x2['from_city'] = 'New Delhi'
x2['to_city'] = to_city
x2['price'] = price
x2['journey_date'] = '2021-10-30'
x2['fclass'] = 'Economy'
x2

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara,15:30,2h 45m,Non Stop,New Delhi,Chennai,7425,2021-10-30,Economy
1,Vistara,07:20,2h 50m,Non Stop,New Delhi,Chennai,7425,2021-10-30,Economy
2,IndiGo,08:30,2h 55m,Non Stop,New Delhi,Chennai,7425,2021-10-30,Economy
3,IndiGo,06:25,3h 00m,Non Stop,New Delhi,Chennai,7425,2021-10-30,Economy
4,IndiGo,07:10,4h 35m,1 Stop,New Delhi,Chennai,7425,2021-10-30,Economy
...,...,...,...,...,...,...,...,...,...
484,IndiGo,06:05,6h 25m,1 Stop,New Delhi,Goa,18923,2021-10-30,Economy
485,Air Asia,08:00,10h 25m,2 Stop(s),New Delhi,Goa,19528,2021-10-30,Economy
486,Air India,10:40,9h 50m,1 Stop,New Delhi,Goa,19973,2021-10-30,Economy
487,Air Asia,07:10,11h 15m,2 Stop(s),New Delhi,Goa,21572,2021-10-30,Economy
488,Air Asia,06:10,12h 15m,2 Stop(s),New Delhi,Goa,21572,2021-10-30,Economy

In [69]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','1','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','CCU','1','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','HYD','1','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','AMD','1','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','GOI','1','11','2021','Economy')

x3 = pd.DataFrame({})
x3['airlines'] = airlines
x3['departure'] = departure
x3['duration'] = duration
x3['stops'] = stops
x3['from_city'] = 'New Delhi'
x3['to_city'] = to_city
x3['price'] = price
x3['journey_date'] = '2021-11-1'
x3['fclass'] = 'Economy'
x3

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,IndiGo,07:25,2h 45m,Non Stop,New Delhi,Chennai,7425,2021-11-1,Economy
1,Air India,06:05,2h 50m,Non Stop,New Delhi,Chennai,7425,2021-11-1,Economy
2,Vistara,07:10,2h 50m,Non Stop,New Delhi,Chennai,7425,2021-11-1,Economy
3,Vistara,13:30,2h 50m,Non Stop,New Delhi,Chennai,7425,2021-11-1,Economy
4,IndiGo,16:20,2h 50m,Non Stop,New Delhi,Chennai,7425,2021-11-1,Economy
...,...,...,...,...,...,...,...,...,...
256,Go First,02:00,10h 45m,1 Stop,New Delhi,Goa,7424,2021-11-1,Economy
257,SpiceJet,06:20,10h 45m,1 Stop,New Delhi,Goa,7424,2021-11-1,Economy
258,Go First,07:00,10h 45m,1 Stop,New Delhi,Goa,7424,2021-11-1,Economy
259,Go First,06:05,11h 05m,1 Stop,New Delhi,Goa,7424,2021-11-1,Economy
260,SpiceJet,05:55,14h 40m,1 Stop,New Delhi,Goa,7424,2021-11-1,Economy

In [74]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','3','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','CCU','3','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','HYD','3','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','AMD','3','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','GOI','3','11','2021','Economy')

x4 = pd.DataFrame({})
x4['airlines'] = airlines
x4['departure'] = departure
x4['duration'] = duration
x4['stops'] = stops
x4['from_city'] = 'New Delhi'
x4['to_city'] = to_city
x4['price'] = price
x4['journey_date'] = '2021-11-3'
x4['fclass'] = 'Economy'
x4

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,SpiceJet,05:45,2h 40m,Non Stop,New Delhi,Chennai,7425,2021-11-3,Economy
1,SpiceJet,17:55,2h 40m,Non Stop,New Delhi,Chennai,7425,2021-11-3,Economy
2,IndiGo,07:25,2h 45m,Non Stop,New Delhi,Chennai,7425,2021-11-3,Economy
3,SpiceJet,18:25,2h 45m,Non Stop,New Delhi,Chennai,7425,2021-11-3,Economy
4,Air India,06:05,2h 50m,Non Stop,New Delhi,Chennai,7425,2021-11-3,Economy
...,...,...,...,...,...,...,...,...,...
553,Go First,08:00,4h 45m,1 Stop,New Delhi,Goa,18589,2021-11-3,Economy
554,Go First,07:00,5h 45m,1 Stop,New Delhi,Goa,18589,2021-11-3,Economy
555,Go First,02:00,10h 45m,1 Stop,New Delhi,Goa,18589,2021-11-3,Economy
556,Air Asia,18:35,12h 25m,1 Stop,New Delhi,Goa,20157,2021-11-3,Economy
557,SpiceJet,05:45,12h 50m,1 Stop,New Delhi,Goa,27191,2021-11-3,Economy

In [75]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','5','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','CCU','5','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','HYD','5','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','AMD','5','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','GOI','5','11','2021','Economy')

x5 = pd.DataFrame({})
x5['airlines'] = airlines
x5['departure'] = departure
x5['duration'] = duration
x5['stops'] = stops
x5['from_city'] = 'New Delhi'
x5['to_city'] = to_city
x5['price'] = price
x5['journey_date'] = '2021-11-5'
x5['fclass'] = 'Economy'
x5

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,SpiceJet,05:45,2h 40m,Non Stop,New Delhi,Chennai,7425,2021-11-5,Economy
1,SpiceJet,17:55,2h 40m,Non Stop,New Delhi,Chennai,7425,2021-11-5,Economy
2,IndiGo,07:25,2h 45m,Non Stop,New Delhi,Chennai,7425,2021-11-5,Economy
3,SpiceJet,18:25,2h 45m,Non Stop,New Delhi,Chennai,7425,2021-11-5,Economy
4,Air India,06:05,2h 50m,Non Stop,New Delhi,Chennai,7425,2021-11-5,Economy
...,...,...,...,...,...,...,...,...,...
517,Vistara,12:50,26h 05m,1 Stop,New Delhi,Goa,14513,2021-11-5,Economy
518,Vistara,11:40,27h 15m,1 Stop,New Delhi,Goa,14513,2021-11-5,Economy
519,SpiceJet,19:45,17h 05m,1 Stop,New Delhi,Goa,14535,2021-11-5,Economy
520,SpiceJet,18:55,17h 55m,1 Stop,New Delhi,Goa,14535,2021-11-5,Economy
521,Air India,08:10,26h 05m,2 Stop(s),New Delhi,Goa,14828,2021-11-5,Economy

In [76]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','7','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','CCU','7','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','HYD','7','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','AMD','7','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','GOI','7','11','2021','Economy')

x7 = pd.DataFrame({})
x7['airlines'] = airlines
x7['departure'] = departure
x7['duration'] = duration
x7['stops'] = stops
x7['from_city'] = 'New Delhi'
x7['to_city'] = to_city
x7['price'] = price
x7['journey_date'] = '2021-11-7'
x7['fclass'] = 'Economy'
x7

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara,07:10,2h 50m,Non Stop,New Delhi,Chennai,7425,2021-11-7,Economy
1,IndiGo,23:05,6h 50m,1 Stop,New Delhi,Chennai,7425,2021-11-7,Economy
2,IndiGo,07:55,7h 10m,1 Stop,New Delhi,Chennai,7425,2021-11-7,Economy
3,SpiceJet,06:15,2h 55m,Non Stop,New Delhi,Chennai,7530,2021-11-7,Economy
4,SpiceJet,06:20,25h 40m,1 Stop,New Delhi,Chennai,7635,2021-11-7,Economy
...,...,...,...,...,...,...,...,...,...
257,Air India,08:00,22h 50m,1 Stop,New Delhi,Goa,11205,2021-11-7,Economy
258,Air India,07:00,23h 50m,1 Stop,New Delhi,Goa,11205,2021-11-7,Economy
259,IndiGo,06:10,5h 20m,1 Stop,New Delhi,Goa,11300,2021-11-7,Economy
260,IndiGo,11:00,6h 25m,1 Stop,New Delhi,Goa,11300,2021-11-7,Economy
261,Go First,21:00,9h 50m,1 Stop,New Delhi,Goa,11488,2021-11-7,Economy

In [78]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','9','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','CCU','9','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','HYD','9','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','AMD','9','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','GOI','9','11','2021','Economy')

x6 = pd.DataFrame({})
x6['airlines'] = airlines
x6['departure'] = departure
x6['duration'] = duration
x6['stops'] = stops
x6['from_city'] = 'New Delhi'
x6['to_city'] = to_city
x6['price'] = price
x6['journey_date'] = '2021-11-9'
x6['fclass'] = 'Economy'
x6

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,SpiceJet,18:25,2h 45m,Non Stop,New Delhi,Chennai,7425,2021-11-9,Economy
1,Vistara,13:30,2h 50m,Non Stop,New Delhi,Chennai,7425,2021-11-9,Economy
2,SpiceJet,06:15,2h 55m,Non Stop,New Delhi,Chennai,7425,2021-11-9,Economy
3,Air India,09:45,2h 55m,Non Stop,New Delhi,Chennai,7425,2021-11-9,Economy
4,Air India,20:40,2h 55m,Non Stop,New Delhi,Chennai,7425,2021-11-9,Economy
...,...,...,...,...,...,...,...,...,...
514,Air India,20:00,10h 50m,1 Stop,New Delhi,Goa,19605,2021-11-9,Economy
515,SpiceJet,18:10,18h 25m,1 Stop,New Delhi,Goa,19658,2021-11-9,Economy
516,SpiceJet,20:10,11h 35m,1 Stop,New Delhi,Goa,22623,2021-11-9,Economy
517,Air India,20:00,18h 45m,1 Stop,New Delhi,Goa,22965,2021-11-9,Economy
518,Air India,10:35,9h 55m,2 Stop(s),New Delhi,Goa,25674,2021-11-9,Economy

In [79]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','11','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','CCU','11','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','HYD','11','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','AMD','11','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','GOI','11','11','2021','Economy')

x8 = pd.DataFrame({})
x8['airlines'] = airlines
x8['departure'] = departure
x8['duration'] = duration
x8['stops'] = stops
x8['from_city'] = 'New Delhi'
x8['to_city'] = to_city
x8['price'] = price
x8['journey_date'] = '2021-11-11'
x8['fclass'] = 'Economy'
x8

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,IndiGo,07:25,2h 45m,Non Stop,New Delhi,Chennai,7425,2021-11-11,Economy
1,SpiceJet,18:25,2h 45m,Non Stop,New Delhi,Chennai,7425,2021-11-11,Economy
2,Air India,06:05,2h 50m,Non Stop,New Delhi,Chennai,7425,2021-11-11,Economy
3,Vistara,07:10,2h 50m,Non Stop,New Delhi,Chennai,7425,2021-11-11,Economy
4,Vistara,13:30,2h 50m,Non Stop,New Delhi,Chennai,7425,2021-11-11,Economy
...,...,...,...,...,...,...,...,...,...
411,Vistara,17:35,20h 15m,1 Stop,New Delhi,Goa,18975,2021-11-11,Economy
412,Vistara,16:05,21h 45m,1 Stop,New Delhi,Goa,18975,2021-11-11,Economy
413,Vistara,14:15,23h 35m,1 Stop,New Delhi,Goa,18975,2021-11-11,Economy
414,IndiGo,09:55,2h 35m,Non Stop,New Delhi,Goa,20340,2021-11-11,Economy
415,SpiceJet,18:10,18h 25m,1 Stop,New Delhi,Goa,25432,2021-11-11,Economy

In [80]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','13','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','CCU','13','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','HYD','13','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','AMD','13','11','2021','Economy')
time.sleep(5)
get_yatra('DEL','GOI','13','11','2021','Economy')

x9 = pd.DataFrame({})
x9['airlines'] = airlines
x9['departure'] = departure
x9['duration'] = duration
x9['stops'] = stops
x9['from_city'] = 'New Delhi'
x9['to_city'] = to_city
x9['price'] = price
x9['journey_date'] = '2021-11-13'
x9['fclass'] = 'Economy'
x9

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air India,09:45,2h 55m,Non Stop,New Delhi,Chennai,6122,2021-11-13,Economy
1,IndiGo,07:25,2h 45m,Non Stop,New Delhi,Chennai,7425,2021-11-13,Economy
2,Air India,06:05,2h 50m,Non Stop,New Delhi,Chennai,7425,2021-11-13,Economy
3,IndiGo,20:30,2h 50m,Non Stop,New Delhi,Chennai,7425,2021-11-13,Economy
4,SpiceJet,06:15,2h 55m,Non Stop,New Delhi,Chennai,7425,2021-11-13,Economy
...,...,...,...,...,...,...,...,...,...
266,Go First,16:35,8h 00m,1 Stop,New Delhi,Ahmedabad,15983,2021-11-13,Economy
267,Air India,19:00,22h 50m,2 Stop(s),New Delhi,Ahmedabad,17085,2021-11-13,Economy
268,Air India,13:20,28h 30m,2 Stop(s),New Delhi,Ahmedabad,18135,2021-11-13,Economy
269,Air India,18:30,23h 20m,2 Stop(s),New Delhi,Ahmedabad,20580,2021-11-13,Economy
270,Air India,13:15,28h 35m,3 Stop(s),New Delhi,Ahmedabad,23438,2021-11-13,Economy

In [81]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','29','10','2021','Special')
time.sleep(5)
get_yatra('DEL','CCU','29','10','2021','Special')
time.sleep(5)
get_yatra('DEL','HYD','29','10','2021','Special')
time.sleep(5)
get_yatra('DEL','AMD','29','10','2021','Special')
time.sleep(5)
get_yatra('DEL','GOI','29','10','2021','Special')

y1 = pd.DataFrame({})
y1['airlines'] = airlines
y1['departure'] = departure
y1['duration'] = duration
y1['stops'] = stops
y1['from_city'] = 'New Delhi'
y1['to_city'] = to_city
y1['price'] = price
y1['journey_date'] = '2021-10-29'
y1['fclass'] = 'Special'
y1

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,06:20,2h 00m,Non Stop,New Delhi,Kolkata,6998,2021-10-29,Special
1,Vistara Premium Economy,17:30,2h 05m,Non Stop,New Delhi,Kolkata,7726,2021-10-29,Special
2,Vistara Premium Economy,20:30,2h 15m,Non Stop,New Delhi,Kolkata,10638,2021-10-29,Special
3,Vistara Premium Economy,07:15,2h 20m,Non Stop,New Delhi,Kolkata,10638,2021-10-29,Special
4,Vistara Premium Economy,06:40,26h 35m,1 Stop,New Delhi,Kolkata,12684,2021-10-29,Special
...,...,...,...,...,...,...,...,...,...
70,Vistara Premium Economy,12:45,24h 00m,1 Stop,New Delhi,Goa,26878,2021-10-29,Special
71,Vistara Premium Economy,19:45,17h 00m,1 Stop,New Delhi,Goa,30294,2021-10-29,Special
72,Vistara Premium Economy,17:45,19h 00m,1 Stop,New Delhi,Goa,30294,2021-10-29,Special
73,Vistara Premium Economy,16:55,19h 50m,1 Stop,New Delhi,Goa,30294,2021-10-29,Special
74,Vistara Premium Economy,21:40,15h 05m,1 Stop,New Delhi,Goa,33542,2021-10-29,Special

In [82]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','31','10','2021','Special')
time.sleep(5)
get_yatra('DEL','CCU','31','10','2021','Special')
time.sleep(5)
get_yatra('DEL','HYD','31','10','2021','Special')
time.sleep(5)
get_yatra('DEL','AMD','31','10','2021','Special')
time.sleep(5)
get_yatra('DEL','GOI','31','10','2021','Special')

y2 = pd.DataFrame({})
y2['airlines'] = airlines
y2['departure'] = departure
y2['duration'] = duration
y2['stops'] = stops
y2['from_city'] = 'New Delhi'
y2['to_city'] = to_city
y2['price'] = price
y2['journey_date'] = '2021-10-31'
y2['fclass'] = 'Special'
y2

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,07:10,2h 50m,Non Stop,New Delhi,Chennai,8566,2021-10-31,Special
1,Vistara Premium Economy,19:55,2h 50m,Non Stop,New Delhi,Chennai,8566,2021-10-31,Special
2,Vistara Premium Economy,17:25,2h 50m,Non Stop,New Delhi,Chennai,9070,2021-10-31,Special
3,Vistara Premium Economy,13:30,2h 50m,Non Stop,New Delhi,Chennai,23910,2021-10-31,Special
4,Vistara Premium Economy,06:15,2h 05m,Non Stop,New Delhi,Kolkata,6998,2021-10-31,Special
5,Vistara Premium Economy,20:30,2h 15m,Non Stop,New Delhi,Kolkata,6998,2021-10-31,Special
6,Vistara Premium Economy,07:20,2h 05m,Non Stop,New Delhi,Kolkata,7726,2021-10-31,Special
7,Vistara Premium Economy,17:30,2h 05m,Non Stop,New Delhi,Kolkata,7726,2021-10-31,Special
8,Vistara Premium Economy,17:40,2h 10m,Non Stop,New Delhi,Hyderabad,6942,2021-10-31,Special
9,Vistara Premium Economy,07:05,2h 20m,Non Stop,New Delhi,Hyderabad,6942,2021-10-31,Special
10,Vistara Premium Economy,20:35,2h 20m,Non Stop,New Delhi,Hyderabad,6942,2021-10-31,Special
11,Vistara Premium Economy,21:40,10h 10m,1 Stop,New Delhi,Hyderabad,11422,2021-10-31,Special
12,Vistara Premium Economy,09:30,11h 25m,1 Stop,New Delhi,Hyderabad,11422,2021-10-31,Special
13,Vistara Premium Economy,19:50,12h 00m,1 Stop,New Delhi,Hyderabad,11422,2021-10-31,Special
14,Vistara Premium Economy,08:50,12h 05m,1 Stop,New Delhi,Hyderabad,11422,2021-10-31,Special
15,Vistara Premium Economy,18:55,12h 55m,1 Stop,New Delhi,Hyderabad,11422,2021-10-31,Special
16,Vistara Premium Economy,07:30,13h 25m,1 Stop,New Delhi,Hyderabad,11422,2021-10-31,Special
17,Vistara Premium Economy,17:45,14h 05m,1 Stop,New Delhi,Hyderabad,11422,2021-10-31,Special
18,Vistara Premium Economy,09:30,22h 20m,1 Stop,New Delhi,Hyderabad,11422,2021-10-31,Special
19,Vistara Premium Economy,08:50,23h 00m,1 Stop,New Delhi,Hyderabad,11422,2021-10-31,Special
20,Vistara Premium Economy,07:30,24h 20m,1 Stop,New Delhi,Hyderabad,11422,2021-10-31,Special
21,Vistara Premium Economy,11:40,9h 15m,1 Stop,New Delhi,Hyderabad,11758,2021-10-31,Special
22,Vistara Premium Economy,10:20,10h 35m,1 Stop,New Delhi,Hyderabad,11758,2021-10-31,Special
23,Vistara Premium Economy,11:40,20h 10m,1 Stop,New Delhi,Hyderabad,11758,2021-10-31,Special
24,Vistara Premium Economy,10:20,21h 30m,1 Stop,New Delhi,Hyderabad,11758,2021-10-31,Special
25,Vistara Premium Economy,15:30,5h 25m,1 Stop,New Delhi,Hyderabad,16798,2021-10-31,Special
26,Vistara Premium Economy,12:50,8h 05m,1 Stop,New Delhi,Hyderabad,16798,2021-10-31,Special
27,Vistara Premium Economy,16:55,14h 55m,1 Stop,New Delhi,Hyderabad,16798,2021-10-31,Special
28,Vistara Premium Economy,15:30,16h 20m,1 Stop,New Delhi,Hyderabad,16798,2021-10-31,Special
29,Vistara Premium Economy,12:50,19h 00m,1 Stop,New Delhi,Hyderabad,16798,2021-10-31,Special
30,Vistara Premium Economy,06:15,25h 35m,2 Stop(s),New Delhi,Hyderabad,17842,2021-10-31,Special
31,Vistara Premium Economy,15:00,16h 50m,2 Stop(s),New Delhi,Hyderabad,18850,2021-10-31,Special
32,Vistara Premium Economy,08:05,23h 45m,2 Stop(s),New Delhi,Hyderabad,18850,2021-10-31,Special
33,Vistara Premium Economy,14:45,2h 15m,Non Stop,New Delhi,Hyderabad,19206,2021-10-31,Special
34,Vistara Premium Economy,14:15,17h 35m,2 Stop(s),New Delhi,Hyderabad,20418,2021-10-31,Special
35,Vistara Premium Economy,11:10,2h 40m,Non Stop,New Delhi,Goa,9630,2021-10-31,Special
36,Vistara Premium Economy,07:30,5h 15m,1 Stop,New Delhi,Goa,14670,2021-10-31,Special
37,Vistara Premium Economy,21:40,15h 05m,1 Stop,New Delhi,Goa,14670,2021-10-31,Special
38,Vistara Premium Economy,19:50,16h 55m,1 Stop,New Delhi,Goa,14670,2021-10-31,Special
39,Vistara Premium Economy,18:55,17h 50m,1 Stop,New Delhi,Goa,14670,2021-10-31,Special
40,Vistara Premium Economy,17:45,19h 00m,1 Stop,New Delhi,Goa,14670,2021-10-31,Special
41,Vistara Premium Economy,09:30,27h 15m,1 Stop,New Delhi,Goa,14670,2021-10-31,Special
42,Vistara Premium Economy,11:40,25h 05m,1 Stop,New Delhi,Goa,15006,2021-10-31,Special
43,Vistara Premium Economy,10:20,26h 25m,1 Stop,New Delhi,Goa,15006,2021-10-31,Special
44,Vistara Premium Economy,16:55,19h 50m,1 Stop,New Delhi,Goa,20046,2021-10-31,Special
45,Vistara Premium Economy,15:30,21h 15m,1 Stop,New Delhi,Goa,20046,2021-10-31,Special
46,Vistara Premium Economy,12:50,23h 55m,1 Stop,New Delhi,Goa,20046,2021-10-31,Special

In [87]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','2','11','2021','Special')
time.sleep(5)
get_yatra('DEL','CCU','2','11','2021','Special')
time.sleep(5)
get_yatra('DEL','HYD','2','11','2021','Special')
time.sleep(5)
get_yatra('DEL','AMD','2','11','2021','Special')
time.sleep(5)
get_yatra('DEL','GOI','2','11','2021','Special')

y3 = pd.DataFrame({})
y3['airlines'] = airlines
y3['departure'] = departure
y3['duration'] = duration
y3['stops'] = stops
y3['from_city'] = 'New Delhi'
y3['to_city'] = to_city
y3['price'] = price
y3['journey_date'] = '2021-11-2'
y3['fclass'] = 'Special'
y3

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,07:10,2h 50m,Non Stop,New Delhi,Chennai,8566,2021-11-2,Special
1,Vistara Premium Economy,13:30,2h 50m,Non Stop,New Delhi,Chennai,8566,2021-11-2,Special
2,Vistara Premium Economy,17:25,2h 50m,Non Stop,New Delhi,Chennai,8566,2021-11-2,Special
3,Vistara Premium Economy,19:55,2h 50m,Non Stop,New Delhi,Chennai,8566,2021-11-2,Special
4,Vistara Premium Economy,06:15,2h 05m,Non Stop,New Delhi,Kolkata,6998,2021-11-2,Special
...,...,...,...,...,...,...,...,...,...
67,Vistara Premium Economy,11:40,25h 05m,1 Stop,New Delhi,Goa,16630,2021-11-2,Special
68,Vistara Premium Economy,10:20,26h 25m,1 Stop,New Delhi,Goa,16630,2021-11-2,Special
69,Vistara Premium Economy,09:30,27h 15m,1 Stop,New Delhi,Goa,16630,2021-11-2,Special
70,Vistara Premium Economy,12:50,23h 55m,1 Stop,New Delhi,Goa,16966,2021-11-2,Special
71,Vistara Premium Economy,15:30,21h 15m,1 Stop,New Delhi,Goa,22006,2021-11-2,Special

In [88]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','4','11','2021','Special')
time.sleep(5)
get_yatra('DEL','CCU','4','11','2021','Special')
time.sleep(5)
get_yatra('DEL','HYD','4','11','2021','Special')
time.sleep(5)
get_yatra('DEL','AMD','4','11','2021','Special')
time.sleep(5)
get_yatra('DEL','GOI','4','11','2021','Special')

y4 = pd.DataFrame({})
y4['airlines'] = airlines
y4['departure'] = departure
y4['duration'] = duration
y4['stops'] = stops
y4['from_city'] = 'New Delhi'
y4['to_city'] = to_city
y4['price'] = price
y4['journey_date'] = '2021-11-4'
y4['fclass'] = 'Special'
y4

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,07:10,2h 50m,Non Stop,New Delhi,Chennai,8566,2021-11-4,Special
1,Vistara Premium Economy,13:30,2h 50m,Non Stop,New Delhi,Chennai,8566,2021-11-4,Special
2,Vistara Premium Economy,17:25,2h 50m,Non Stop,New Delhi,Chennai,8566,2021-11-4,Special
3,Vistara Premium Economy,06:15,2h 05m,Non Stop,New Delhi,Kolkata,6998,2021-11-4,Special
4,Vistara Premium Economy,07:20,2h 05m,Non Stop,New Delhi,Kolkata,7726,2021-11-4,Special
5,Vistara Premium Economy,17:30,2h 05m,Non Stop,New Delhi,Kolkata,7726,2021-11-4,Special
6,Vistara Premium Economy,07:05,2h 20m,Non Stop,New Delhi,Hyderabad,6942,2021-11-4,Special
7,Vistara Premium Economy,20:35,2h 20m,Non Stop,New Delhi,Hyderabad,6942,2021-11-4,Special
8,Vistara Premium Economy,17:45,14h 05m,1 Stop,New Delhi,Hyderabad,14670,2021-11-4,Special
9,Vistara Premium Economy,16:55,14h 55m,1 Stop,New Delhi,Hyderabad,14670,2021-11-4,Special
10,Vistara Premium Economy,15:30,16h 20m,1 Stop,New Delhi,Hyderabad,14670,2021-11-4,Special
11,Vistara Premium Economy,12:50,19h 00m,1 Stop,New Delhi,Hyderabad,14670,2021-11-4,Special
12,Vistara Premium Economy,11:40,20h 10m,1 Stop,New Delhi,Hyderabad,14670,2021-11-4,Special
13,Vistara Premium Economy,10:20,21h 30m,1 Stop,New Delhi,Hyderabad,14670,2021-11-4,Special
14,Vistara Premium Economy,09:30,22h 20m,1 Stop,New Delhi,Hyderabad,14670,2021-11-4,Special
15,Vistara Premium Economy,08:50,23h 00m,1 Stop,New Delhi,Hyderabad,14670,2021-11-4,Special
16,Vistara Premium Economy,07:30,24h 20m,1 Stop,New Delhi,Hyderabad,14670,2021-11-4,Special
17,Vistara Premium Economy,06:00,25h 50m,1 Stop,New Delhi,Hyderabad,14670,2021-11-4,Special
18,Vistara Premium Economy,13:20,18h 30m,2 Stop(s),New Delhi,Hyderabad,23630,2021-11-4,Special
19,Vistara Premium Economy,06:30,1h 35m,Non Stop,New Delhi,Ahmedabad,5906,2021-11-4,Special
20,Vistara Premium Economy,08:45,1h 35m,Non Stop,New Delhi,Ahmedabad,5906,2021-11-4,Special
21,Vistara Premium Economy,18:00,1h 40m,Non Stop,New Delhi,Ahmedabad,5906,2021-11-4,Special
22,Vistara Premium Economy,11:10,2h 40m,Non Stop,New Delhi,Goa,13494,2021-11-4,Special
23,Vistara Premium Economy,07:30,5h 15m,1 Stop,New Delhi,Goa,16630,2021-11-4,Special
24,Vistara Premium Economy,06:00,6h 45m,1 Stop,New Delhi,Goa,16630,2021-11-4,Special
25,Vistara Premium Economy,17:45,19h 00m,1 Stop,New Delhi,Goa,21502,2021-11-4,Special
26,Vistara Premium Economy,16:55,19h 50m,1 Stop,New Delhi,Goa,21502,2021-11-4,Special
27,Vistara Premium Economy,15:30,21h 15m,1 Stop,New Delhi,Goa,21502,2021-11-4,Special
28,Vistara Premium Economy,12:50,23h 55m,1 Stop,New Delhi,Goa,21502,2021-11-4,Special
29,Vistara Premium Economy,11:40,25h 05m,1 Stop,New Delhi,Goa,21502,2021-11-4,Special
30,Vistara Premium Economy,10:20,26h 25m,1 Stop,New Delhi,Goa,21502,2021-11-4,Special
31,Vistara Premium Economy,09:30,27h 15m,1 Stop,New Delhi,Goa,21502,2021-11-4,Special

In [92]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','6','11','2021','Special')
time.sleep(5)
get_yatra('DEL','CCU','6','11','2021','Special')
time.sleep(5)
get_yatra('DEL','HYD','6','11','2021','Special')
time.sleep(5)
get_yatra('DEL','AMD','6','11','2021','Special')
time.sleep(5)
get_yatra('DEL','GOI','6','11','2021','Special')

y5 = pd.DataFrame({})
y5['airlines'] = airlines
y5['departure'] = departure
y5['duration'] = duration
y5['stops'] = stops
y5['from_city'] = 'New Delhi'
y5['to_city'] = to_city
y5['price'] = price
y5['journey_date'] = '2021-11-6'
y5['fclass'] = 'Special'
y5

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,07:10,2h 50m,Non Stop,New Delhi,Chennai,8566,2021-11-6,Special
1,Vistara Premium Economy,13:30,2h 50m,Non Stop,New Delhi,Chennai,8566,2021-11-6,Special
2,Vistara Premium Economy,17:25,2h 50m,Non Stop,New Delhi,Chennai,8566,2021-11-6,Special
3,Vistara Premium Economy,19:55,2h 50m,Non Stop,New Delhi,Chennai,9070,2021-11-6,Special
4,Vistara Premium Economy,06:15,2h 05m,Non Stop,New Delhi,Kolkata,6998,2021-11-6,Special
...,...,...,...,...,...,...,...,...,...
70,Vistara Premium Economy,17:45,19h 00m,1 Stop,New Delhi,Goa,21838,2021-11-6,Special
71,Vistara Premium Economy,15:30,21h 15m,1 Stop,New Delhi,Goa,21838,2021-11-6,Special
72,Vistara Premium Economy,12:50,23h 55m,1 Stop,New Delhi,Goa,21838,2021-11-6,Special
73,Vistara Premium Economy,11:40,25h 05m,1 Stop,New Delhi,Goa,21838,2021-11-6,Special
74,Vistara Premium Economy,16:55,19h 50m,1 Stop,New Delhi,Goa,26878,2021-11-6,Special

In [93]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','8','11','2021','Special')
time.sleep(5)
get_yatra('DEL','CCU','8','11','2021','Special')
time.sleep(5)
get_yatra('DEL','HYD','8','11','2021','Special')
time.sleep(5)
get_yatra('DEL','AMD','8','11','2021','Special')
time.sleep(5)
get_yatra('DEL','GOI','8','11','2021','Special')

y6 = pd.DataFrame({})
y6['airlines'] = airlines
y6['departure'] = departure
y6['duration'] = duration
y6['stops'] = stops
y6['from_city'] = 'New Delhi'
y6['to_city'] = to_city
y6['price'] = price
y6['journey_date'] = '2021-11-8'
y6['fclass'] = 'Special'
y6

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,06:15,2h 05m,Non Stop,New Delhi,Kolkata,6998,2021-11-8,Special
1,Vistara Premium Economy,20:30,2h 15m,Non Stop,New Delhi,Kolkata,6998,2021-11-8,Special
2,Vistara Premium Economy,07:20,2h 05m,Non Stop,New Delhi,Kolkata,7726,2021-11-8,Special
3,Vistara Premium Economy,17:30,2h 05m,Non Stop,New Delhi,Kolkata,10638,2021-11-8,Special
4,Vistara Premium Economy,06:40,27h 05m,1 Stop,New Delhi,Kolkata,12684,2021-11-8,Special
...,...,...,...,...,...,...,...,...,...
66,Vistara Premium Economy,21:40,15h 05m,1 Stop,New Delhi,Goa,18366,2021-11-8,Special
67,Vistara Premium Economy,17:45,19h 00m,1 Stop,New Delhi,Goa,20046,2021-11-8,Special
68,Vistara Premium Economy,15:30,21h 15m,1 Stop,New Delhi,Goa,20046,2021-11-8,Special
69,Vistara Premium Economy,06:00,6h 45m,1 Stop,New Delhi,Goa,21502,2021-11-8,Special
70,Vistara Premium Economy,07:30,5h 15m,1 Stop,New Delhi,Goa,26878,2021-11-8,Special

In [94]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','10','11','2021','Special')
time.sleep(5)
get_yatra('DEL','CCU','10','11','2021','Special')
time.sleep(5)
get_yatra('DEL','HYD','10','11','2021','Special')
time.sleep(5)
get_yatra('DEL','AMD','10','11','2021','Special')
time.sleep(5)
get_yatra('DEL','GOI','10','11','2021','Special')

y7 = pd.DataFrame({})
y7['airlines'] = airlines
y7['departure'] = departure
y7['duration'] = duration
y7['stops'] = stops
y7['from_city'] = 'New Delhi'
y7['to_city'] = to_city
y7['price'] = price
y7['journey_date'] = '2021-11-10'
y7['fclass'] = 'Special'
y7

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,06:15,2h 05m,Non Stop,New Delhi,Kolkata,6998,2021-11-10,Special
1,Vistara Premium Economy,20:30,2h 15m,Non Stop,New Delhi,Kolkata,6998,2021-11-10,Special
2,Vistara Premium Economy,07:20,2h 05m,Non Stop,New Delhi,Kolkata,7726,2021-11-10,Special
3,Vistara Premium Economy,17:30,2h 05m,Non Stop,New Delhi,Kolkata,7726,2021-11-10,Special
4,Vistara Premium Economy,06:40,27h 05m,1 Stop,New Delhi,Kolkata,12684,2021-11-10,Special
5,Vistara Premium Economy,18:00,15h 45m,1 Stop,New Delhi,Kolkata,16128,2021-11-10,Special
6,Vistara Premium Economy,17:40,2h 10m,Non Stop,New Delhi,Hyderabad,6942,2021-11-10,Special
7,Vistara Premium Economy,07:05,2h 20m,Non Stop,New Delhi,Hyderabad,6942,2021-11-10,Special
8,Vistara Premium Economy,20:35,2h 20m,Non Stop,New Delhi,Hyderabad,6942,2021-11-10,Special
9,Vistara Premium Economy,14:45,2h 15m,Non Stop,New Delhi,Hyderabad,7278,2021-11-10,Special
10,Vistara Premium Economy,07:30,4h 45m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
11,Vistara Premium Economy,15:30,5h 25m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
12,Vistara Premium Economy,06:00,6h 15m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
13,Vistara Premium Economy,12:50,8h 05m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
14,Vistara Premium Economy,11:40,9h 15m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
15,Vistara Premium Economy,21:40,10h 10m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
16,Vistara Premium Economy,10:20,10h 35m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
17,Vistara Premium Economy,20:40,11h 10m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
18,Vistara Premium Economy,09:30,11h 25m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
19,Vistara Premium Economy,19:50,12h 00m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
20,Vistara Premium Economy,08:50,12h 05m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
21,Vistara Premium Economy,07:30,13h 25m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
22,Vistara Premium Economy,21:40,14h 35m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
23,Vistara Premium Economy,06:00,14h 55m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
24,Vistara Premium Economy,16:55,14h 55m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
25,Vistara Premium Economy,20:40,15h 35m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
26,Vistara Premium Economy,15:30,16h 20m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
27,Vistara Premium Economy,19:50,16h 25m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
28,Vistara Premium Economy,12:50,19h 00m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
29,Vistara Premium Economy,16:55,19h 20m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
30,Vistara Premium Economy,11:40,20h 10m,1 Stop,New Delhi,Hyderabad,11422,2021-11-10,Special
31,Vistara Premium Economy,06:30,1h 35m,Non Stop,New Delhi,Ahmedabad,9350,2021-11-10,Special
32,Vistara Premium Economy,08:45,1h 35m,Non Stop,New Delhi,Ahmedabad,9350,2021-11-10,Special
33,Vistara Premium Economy,18:00,1h 40m,Non Stop,New Delhi,Ahmedabad,11814,2021-11-10,Special
34,Vistara Premium Economy,21:40,15h 05m,1 Stop,New Delhi,Goa,16630,2021-11-10,Special
35,Vistara Premium Economy,20:40,16h 05m,1 Stop,New Delhi,Goa,16630,2021-11-10,Special
36,Vistara Premium Economy,19:50,16h 55m,1 Stop,New Delhi,Goa,16630,2021-11-10,Special
37,Vistara Premium Economy,16:55,19h 50m,1 Stop,New Delhi,Goa,16630,2021-11-10,Special
38,Vistara Premium Economy,15:30,21h 15m,1 Stop,New Delhi,Goa,16630,2021-11-10,Special
39,Vistara Premium Economy,12:50,23h 55m,1 Stop,New Delhi,Goa,16630,2021-11-10,Special
40,Vistara Premium Economy,11:40,25h 05m,1 Stop,New Delhi,Goa,16630,2021-11-10,Special
41,Vistara Premium Economy,10:20,26h 25m,1 Stop,New Delhi,Goa,16630,2021-11-10,Special
42,Vistara Premium Economy,09:30,27h 15m,1 Stop,New Delhi,Goa,16630,2021-11-10,Special
43,Vistara Premium Economy,18:55,17h 50m,1 Stop,New Delhi,Goa,16966,2021-11-10,Special
44,Vistara Premium Economy,17:45,19h 00m,1 Stop,New Delhi,Goa,16966,2021-11-10,Special
45,Vistara Premium Economy,07:30,5h 15m,1 Stop,New Delhi,Goa,21502,2021-11-10,Special
46,Vistara Premium Economy,06:00,6h 45m,1 Stop,New Delhi,Goa,21502,2021-11-10,Special
47,Vistara Premium Economy,11:10,2h 40m,Non Stop,New Delhi,Goa,23910,2021-11-10,Special

In [95]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','12','11','2021','Special')
time.sleep(5)
get_yatra('DEL','CCU','12','11','2021','Special')
time.sleep(5)
get_yatra('DEL','HYD','12','11','2021','Special')
time.sleep(5)
get_yatra('DEL','AMD','12','11','2021','Special')
time.sleep(5)
get_yatra('DEL','GOI','12','11','2021','Special')

y8 = pd.DataFrame({})
y8['airlines'] = airlines
y8['departure'] = departure
y8['duration'] = duration
y8['stops'] = stops
y8['from_city'] = 'New Delhi'
y8['to_city'] = to_city
y8['price'] = price
y8['journey_date'] = '2021-11-12'
y8['fclass'] = 'Special'
y8

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,07:05,2h 20m,Non Stop,New Delhi,Hyderabad,6942,2021-11-12,Special
1,Vistara Premium Economy,17:40,2h 10m,Non Stop,New Delhi,Hyderabad,7278,2021-11-12,Special
2,Vistara Premium Economy,14:45,2h 15m,Non Stop,New Delhi,Hyderabad,7278,2021-11-12,Special
3,Vistara Premium Economy,20:35,2h 20m,Non Stop,New Delhi,Hyderabad,7278,2021-11-12,Special
4,Vistara Premium Economy,07:30,4h 45m,1 Stop,New Delhi,Hyderabad,11422,2021-11-12,Special
...,...,...,...,...,...,...,...,...,...
60,Vistara Premium Economy,09:30,27h 15m,1 Stop,New Delhi,Goa,14670,2021-11-12,Special
61,Vistara Premium Economy,17:45,19h 00m,1 Stop,New Delhi,Goa,20046,2021-11-12,Special
62,Vistara Premium Economy,07:30,5h 15m,1 Stop,New Delhi,Goa,21502,2021-11-12,Special
63,Vistara Premium Economy,06:00,6h 45m,1 Stop,New Delhi,Goa,21502,2021-11-12,Special
64,Vistara Premium Economy,11:10,2h 40m,Non Stop,New Delhi,Goa,23910,2021-11-12,Special

In [96]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','14','11','2021','Special')
time.sleep(5)
get_yatra('DEL','CCU','14','11','2021','Special')
time.sleep(5)
get_yatra('DEL','HYD','14','11','2021','Special')
time.sleep(5)
get_yatra('DEL','AMD','14','11','2021','Special')
time.sleep(5)
get_yatra('DEL','GOI','14','11','2021','Special')

y9 = pd.DataFrame({})
y9['airlines'] = airlines
y9['departure'] = departure
y9['duration'] = duration
y9['stops'] = stops
y9['from_city'] = 'New Delhi'
y9['to_city'] = to_city
y9['price'] = price
y9['journey_date'] = '2021-11-14'
y9['fclass'] = 'Special'
y9

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Premium Economy,07:10,2h 50m,Non Stop,New Delhi,Chennai,8566,2021-11-14,Special
1,Vistara Premium Economy,13:30,2h 50m,Non Stop,New Delhi,Chennai,9070,2021-11-14,Special
2,Vistara Premium Economy,17:25,2h 50m,Non Stop,New Delhi,Chennai,9070,2021-11-14,Special
3,Vistara Premium Economy,19:55,2h 50m,Non Stop,New Delhi,Chennai,9070,2021-11-14,Special
4,Vistara Premium Economy,06:15,2h 05m,Non Stop,New Delhi,Kolkata,6998,2021-11-14,Special
5,Vistara Premium Economy,20:30,2h 15m,Non Stop,New Delhi,Kolkata,6998,2021-11-14,Special
6,Vistara Premium Economy,07:20,2h 05m,Non Stop,New Delhi,Kolkata,8958,2021-11-14,Special
7,Vistara Premium Economy,17:30,2h 05m,Non Stop,New Delhi,Kolkata,8958,2021-11-14,Special
8,Vistara Premium Economy,06:30,1h 35m,Non Stop,New Delhi,Ahmedabad,9350,2021-11-14,Special
9,Vistara Premium Economy,18:00,1h 40m,Non Stop,New Delhi,Ahmedabad,11814,2021-11-14,Special
10,Vistara Premium Economy,07:10,2h 35m,Non Stop,New Delhi,Goa,11198,2021-11-14,Special
11,Vistara Premium Economy,07:30,5h 15m,1 Stop,New Delhi,Goa,15006,2021-11-14,Special
12,Vistara Premium Economy,11:40,25h 05m,1 Stop,New Delhi,Goa,16630,2021-11-14,Special
13,Vistara Premium Economy,10:20,26h 25m,1 Stop,New Delhi,Goa,16630,2021-11-14,Special
14,Vistara Premium Economy,09:30,27h 15m,1 Stop,New Delhi,Goa,16630,2021-11-14,Special
15,Vistara Premium Economy,12:50,23h 55m,1 Stop,New Delhi,Goa,16966,2021-11-14,Special
16,Vistara Premium Economy,21:40,15h 05m,1 Stop,New Delhi,Goa,20326,2021-11-14,Special
17,Vistara Premium Economy,19:50,16h 55m,1 Stop,New Delhi,Goa,22006,2021-11-14,Special
18,Vistara Premium Economy,18:55,17h 50m,1 Stop,New Delhi,Goa,22006,2021-11-14,Special
19,Vistara Premium Economy,17:45,19h 00m,1 Stop,New Delhi,Goa,22006,2021-11-14,Special
20,Vistara Premium Economy,16:55,19h 50m,1 Stop,New Delhi,Goa,22006,2021-11-14,Special
21,Vistara Premium Economy,15:30,21h 15m,1 Stop,New Delhi,Goa,22006,2021-11-14,Special
22,Vistara Premium Economy,11:10,2h 40m,Non Stop,New Delhi,Goa,23910,2021-11-14,Special

In [97]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','29','10','2021','Business')
time.sleep(5)
get_yatra('DEL','CCU','29','10','2021','Business')
time.sleep(5)
get_yatra('DEL','HYD','29','10','2021','Business')
time.sleep(5)
get_yatra('DEL','AMD','29','10','2021','Business')
time.sleep(5)
get_yatra('DEL','GOI','29','10','2021','Business')

z1 = pd.DataFrame({})
z1['airlines'] = airlines
z1['departure'] = departure
z1['duration'] = duration
z1['stops'] = stops
z1['from_city'] = 'New Delhi'
z1['to_city'] = to_city
z1['price'] = price
z1['journey_date'] = '2021-10-29'
z1['fclass'] = 'Business'
z1

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Air India Business,06:00,2h 55m,Non Stop,New Delhi,Chennai,25073,2021-10-29,Business
1,Vistara Business,17:35,2h 40m,Non Stop,New Delhi,Chennai,29000,2021-10-29,Business
2,Vistara Business,07:20,2h 50m,Non Stop,New Delhi,Chennai,29000,2021-10-29,Business
3,Vistara Business,16:00,2h 50m,Non Stop,New Delhi,Chennai,29000,2021-10-29,Business
4,Vistara Business,19:55,2h 50m,Non Stop,New Delhi,Chennai,29000,2021-10-29,Business
5,Air India Business,09:45,2h 55m,Non Stop,New Delhi,Chennai,31793,2021-10-29,Business
6,Air India Business,21:15,15h 35m,1 Stop,New Delhi,Chennai,36681,2021-10-29,Business
7,Air India Business,13:30,23h 20m,1 Stop,New Delhi,Chennai,36681,2021-10-29,Business
8,Air India Business,09:45,27h 05m,1 Stop,New Delhi,Chennai,36681,2021-10-29,Business
9,Air India Business,07:00,12h 40m,1 Stop,New Delhi,Chennai,39682,2021-10-29,Business
10,Air India Business,17:50,13h 40m,2 Stop(s),New Delhi,Chennai,39694,2021-10-29,Business
11,Air India Business,15:05,16h 25m,2 Stop(s),New Delhi,Chennai,39694,2021-10-29,Business
12,Air India Business,17:50,17h 05m,2 Stop(s),New Delhi,Chennai,39694,2021-10-29,Business
13,Air India Business,15:05,19h 50m,2 Stop(s),New Delhi,Chennai,39694,2021-10-29,Business
14,Air India Business,10:40,20h 50m,1 Stop,New Delhi,Chennai,39694,2021-10-29,Business
15,Air India Business,08:00,23h 30m,1 Stop,New Delhi,Chennai,39694,2021-10-29,Business
16,Air India Business,10:40,24h 15m,1 Stop,New Delhi,Chennai,39694,2021-10-29,Business
17,Air India Business,07:00,24h 30m,1 Stop,New Delhi,Chennai,39694,2021-10-29,Business
18,Air India Business,08:00,26h 55m,1 Stop,New Delhi,Chennai,39694,2021-10-29,Business
19,Air India Business,07:00,27h 55m,1 Stop,New Delhi,Chennai,39694,2021-10-29,Business
20,Air India Business,05:25,28h 45m,1 Stop,New Delhi,Chennai,44836,2021-10-29,Business
21,Vistara Business,13:30,2h 50m,Non Stop,New Delhi,Chennai,47800,2021-10-29,Business
22,Air India Business,20:40,2h 55m,Non Stop,New Delhi,Chennai,48419,2021-10-29,Business
23,Vistara Business,16:55,27h 30m,1 Stop,New Delhi,Chennai,51977,2021-10-29,Business
24,Vistara Business,16:55,16h 15m,1 Stop,New Delhi,Chennai,54105,2021-10-29,Business

In [99]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','1','11','2021','Business')
time.sleep(5)
get_yatra('DEL','CCU','1','11','2021','Business')
time.sleep(5)
get_yatra('DEL','HYD','1','11','2021','Business')
time.sleep(5)
get_yatra('DEL','AMD','1','11','2021','Business')
time.sleep(5)
get_yatra('DEL','GOI','1','11','2021','Business')

z2 = pd.DataFrame({})
z2['airlines'] = airlines
z2['departure'] = departure
z2['duration'] = duration
z2['stops'] = stops
z2['from_city'] = 'New Delhi'
z2['to_city'] = to_city
z2['price'] = price
z2['journey_date'] = '2021-11-1'
z2['fclass'] = 'Business'
z2

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Business,07:10,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-1,Business
1,Vistara Business,13:30,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-1,Business
2,Vistara Business,17:25,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-1,Business
3,Air India Business,06:05,2h 50m,Non Stop,New Delhi,Chennai,33016,2021-11-1,Business
4,Air India Business,09:45,2h 55m,Non Stop,New Delhi,Chennai,33016,2021-11-1,Business
...,...,...,...,...,...,...,...,...,...
188,Vistara Business,15:30,23h 25m,1 Stop,New Delhi,Goa,52537,2021-11-1,Business
189,Vistara Business,12:50,23h 55m,1 Stop,New Delhi,Goa,52537,2021-11-1,Business
190,Vistara Business,12:50,26h 05m,1 Stop,New Delhi,Goa,52537,2021-11-1,Business
191,Vistara Business,10:20,26h 25m,1 Stop,New Delhi,Goa,52537,2021-11-1,Business
192,Vistara Business,08:50,6h 05m,1 Stop,New Delhi,Goa,54777,2021-11-1,Business

In [101]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','3','11','2021','Business')
time.sleep(5)
get_yatra('DEL','CCU','3','11','2021','Business')
time.sleep(5)
get_yatra('DEL','HYD','3','11','2021','Business')
time.sleep(5)
get_yatra('DEL','AMD','3','11','2021','Business')
time.sleep(5)
get_yatra('DEL','GOI','3','11','2021','Business')

z3 = pd.DataFrame({})
z3['airlines'] = airlines
z3['departure'] = departure
z3['duration'] = duration
z3['stops'] = stops
z3['from_city'] = 'New Delhi'
z3['to_city'] = to_city
z3['price'] = price
z3['journey_date'] = '2021-11-3'
z3['fclass'] = 'Business'
z3

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Business,07:10,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-3,Business
1,Vistara Business,13:30,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-3,Business
2,Vistara Business,17:25,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-3,Business
3,Vistara Business,19:55,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-3,Business
4,Air India Business,06:05,2h 50m,Non Stop,New Delhi,Chennai,33016,2021-11-3,Business
...,...,...,...,...,...,...,...,...,...
124,Vistara Business,21:40,10h 10m,1 Stop,New Delhi,Hyderabad,53321,2021-11-3,Business
125,Air India Business,16:45,1h 25m,Non Stop,New Delhi,Ahmedabad,22264,2021-11-3,Business
126,Vistara Business,08:45,1h 35m,Non Stop,New Delhi,Ahmedabad,22264,2021-11-3,Business
127,Vistara Business,18:00,1h 40m,Non Stop,New Delhi,Ahmedabad,22264,2021-11-3,Business
128,Vistara Business,06:30,1h 35m,Non Stop,New Delhi,Ahmedabad,25400,2021-11-3,Business

In [102]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','5','11','2021','Business')
time.sleep(5)
get_yatra('DEL','CCU','5','11','2021','Business')
time.sleep(5)
get_yatra('DEL','HYD','5','11','2021','Business')
time.sleep(5)
get_yatra('DEL','AMD','5','11','2021','Business')
time.sleep(5)
get_yatra('DEL','GOI','5','11','2021','Business')

z4 = pd.DataFrame({})
z4['airlines'] = airlines
z4['departure'] = departure
z4['duration'] = duration
z4['stops'] = stops
z4['from_city'] = 'New Delhi'
z4['to_city'] = to_city
z4['price'] = price
z4['journey_date'] = '2021-11-5'
z4['fclass'] = 'Business'
z4

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Business,07:10,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-5,Business
1,Vistara Business,13:30,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-5,Business
2,Vistara Business,17:25,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-5,Business
3,Vistara Business,19:55,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-5,Business
4,Air India Business,06:05,2h 50m,Non Stop,New Delhi,Chennai,33016,2021-11-5,Business
...,...,...,...,...,...,...,...,...,...
183,Vistara Business,15:30,23h 25m,1 Stop,New Delhi,Goa,60041,2021-11-5,Business
184,Vistara Business,19:50,15h 50m,1 Stop,New Delhi,Goa,60377,2021-11-5,Business
185,Vistara Business,19:50,19h 05m,1 Stop,New Delhi,Goa,60377,2021-11-5,Business
186,Vistara Business,06:00,6h 45m,1 Stop,New Delhi,Goa,64633,2021-11-5,Business
187,Vistara Business,07:30,5h 15m,1 Stop,New Delhi,Goa,66873,2021-11-5,Business

In [103]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','7','11','2021','Business')
time.sleep(5)
get_yatra('DEL','CCU','7','11','2021','Business')
time.sleep(5)
get_yatra('DEL','HYD','7','11','2021','Business')
time.sleep(5)
get_yatra('DEL','AMD','7','11','2021','Business')
time.sleep(5)
get_yatra('DEL','GOI','7','11','2021','Business')

z5 = pd.DataFrame({})
z5['airlines'] = airlines
z5['departure'] = departure
z5['duration'] = duration
z5['stops'] = stops
z5['from_city'] = 'New Delhi'
z5['to_city'] = to_city
z5['price'] = price
z5['journey_date'] = '2021-11-7'
z5['fclass'] = 'Business'
z5

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Business,07:10,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-7,Business
1,Vistara Business,13:30,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-7,Business
2,Vistara Business,17:25,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-7,Business
3,Air India Business,06:05,2h 50m,Non Stop,New Delhi,Chennai,33016,2021-11-7,Business
4,Air India Business,09:45,2h 55m,Non Stop,New Delhi,Chennai,33016,2021-11-7,Business
...,...,...,...,...,...,...,...,...,...
143,Vistara Business,10:20,4h 35m,1 Stop,New Delhi,Goa,67321,2021-11-7,Business
144,Vistara Business,11:40,27h 15m,1 Stop,New Delhi,Goa,67321,2021-11-7,Business
145,Vistara Business,17:45,21h 10m,1 Stop,New Delhi,Goa,70681,2021-11-7,Business
146,Vistara Business,19:50,16h 55m,1 Stop,New Delhi,Goa,72473,2021-11-7,Business
147,Vistara Business,18:55,17h 50m,1 Stop,New Delhi,Goa,74377,2021-11-7,Business

In [104]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','10','11','2021','Business')
time.sleep(5)
get_yatra('DEL','CCU','10','11','2021','Business')
time.sleep(5)
get_yatra('DEL','HYD','10','11','2021','Business')
time.sleep(5)
get_yatra('DEL','AMD','10','11','2021','Business')
time.sleep(5)
get_yatra('DEL','GOI','10','11','2021','Business')

z6 = pd.DataFrame({})
z6['airlines'] = airlines
z6['departure'] = departure
z6['duration'] = duration
z6['stops'] = stops
z6['from_city'] = 'New Delhi'
z6['to_city'] = to_city
z6['price'] = price
z6['journey_date'] = '2021-11-10'
z6['fclass'] = 'Business'
z6

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Business,07:10,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-10,Business
1,Vistara Business,13:30,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-10,Business
2,Vistara Business,17:25,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-10,Business
3,Vistara Business,19:55,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-10,Business
4,Air India Business,06:05,2h 50m,Non Stop,New Delhi,Chennai,33016,2021-11-10,Business
...,...,...,...,...,...,...,...,...,...
207,Vistara Business,17:45,19h 00m,1 Stop,New Delhi,Goa,58137,2021-11-10,Business
208,Vistara Business,06:00,6h 45m,1 Stop,New Delhi,Goa,60377,2021-11-10,Business
209,Vistara Business,07:30,5h 15m,1 Stop,New Delhi,Goa,62617,2021-11-10,Business
210,Vistara Business,15:30,21h 15m,1 Stop,New Delhi,Goa,63401,2021-11-10,Business
211,Vistara Business,19:50,16h 55m,1 Stop,New Delhi,Goa,63737,2021-11-10,Business

In [105]:
airlines = []
departure = []
duration = []
stops = []
from_city = []
to_city = []
meals = []
price = []

get_yatra('DEL','MAA','13','11','2021','Business')
time.sleep(5)
get_yatra('DEL','CCU','13','11','2021','Business')
time.sleep(5)
get_yatra('DEL','HYD','13','11','2021','Business')
time.sleep(5)
get_yatra('DEL','AMD','13','11','2021','Business')
time.sleep(5)
get_yatra('DEL','GOI','13','11','2021','Business')

z7 = pd.DataFrame({})
z7['airlines'] = airlines
z7['departure'] = departure
z7['duration'] = duration
z7['stops'] = stops
z7['from_city'] = 'New Delhi'
z7['to_city'] = to_city
z7['price'] = price
z7['journey_date'] = '2021-11-13'
z7['fclass'] = 'Business'
z7

,airlines,departure,duration,stops,from_city,to_city,price,journey_date,fclass
0,Vistara Business,07:10,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-13,Business
1,Vistara Business,13:30,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-13,Business
2,Vistara Business,17:25,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-13,Business
3,Vistara Business,19:55,2h 50m,Non Stop,New Delhi,Chennai,27864,2021-11-13,Business
4,Air India Business,06:05,2h 50m,Non Stop,New Delhi,Chennai,33016,2021-11-13,Business
...,...,...,...,...,...,...,...,...,...
127,Air India Business,17:50,24h 00m,2 Stop(s),New Delhi,Ahmedabad,40062,2021-11-13,Business
128,Air India Business,15:05,26h 45m,2 Stop(s),New Delhi,Ahmedabad,40062,2021-11-13,Business
129,Air India Business,21:10,20h 40m,2 Stop(s),New Delhi,Ahmedabad,58015,2021-11-13,Business
130,Air India Business,18:30,23h 20m,2 Stop(s),New Delhi,Ahmedabad,60491,2021-11-13,Business
131,Air India Business,22:00,19h 50m,2 Stop(s),New Delhi,Ahmedabad,67087,2021-11-13,Business

In [106]:
del_oth = pd.concat([x1,x2,x3,x4,x5,x6,x7,x8,x9,y1,y2,y3,y4,y5,y6,y7,y8,y9,z1,z2,z3,z4,z5,z6,z7], axis = 0)
del_oth.shape
del_oth.to_excel('delhiother.xlsx')